-- =====================================================================
--  OVERWATCH -- PREFLIGHT_WAVE4.sql  (READ-ONLY; run BEFORE RUN_NEXT.sql, which applies V162-V165)
--  Next-Fifty wave 4. Changes nothing and sends nothing: SELECT / SHOW / DESC only, plus a session-only
--  TIMEZONE pin (the stored NTZ clocks -- RAISED_AT, NOTIFIED_AT, LOGGED_AT -- are Central). Every grid is
--  generated by outputs/gen_v162.py .. gen_v165.py from the SAME text as the migration it previews (only the
--  read windows are widened), so it lists exactly what each first run raises or escalates.
--  Paste every grid back; an empty grid is an answer ('no rows').
--
--  READ FIRST, before deciding to apply:
--    P162.1  takeover episodes over 30 days; IN_FIRST_RUN_WINDOW rows raise on the first hourly scan, and the
--            CRIT band (off-hours or an admin-role holder) is what can page at night.
--    P162.4  the CRITICAL takeovers V162's first hourly scan raises; with V164 they escalate about 2-3h after
--            the apply (P164.2 cannot see them: they do not exist yet). Acknowledge unwanted ones within 2h of
--            the first hourly scan, or seed ESCALATE_AFTER_MIN '0' first.
--    P163.1  per-user AI runaways (FIRST_RUN_RAISES = the first daily scan).
--    P164.1  can the escalation email go out? DEFAULT_RECIPIENTS_SET and SNOW_ACCOUNTADMINS_CAN_USE must be
--            TRUE, else set DEFAULT_RECIPIENTS in Snowsight or seed ESCALATE_EMAIL_INTEGRATION '' first.
--    P164.2  every EXISTING CRITICAL the first hourly notifier run would re-post and email. Acknowledge stale
--            ones, or seed ESCALATE_AFTER_MIN '0' first (RUN_NEXT.sql's header has both seeds, commented).
--  P165.3 at the very end is OPTIONAL and costs about 5 small Cortex calls: stop before it to skip it.
--  If a grid errors (a missing grant, a view this account does not expose), note the error and run the rest
--  from the next '-- P' header down.
-- =====================================================================

USE ROLE SNOW_ACCOUNTADMINS;
ALTER SESSION SET TIMEZONE = 'America/Chicago';   -- session only; the stored NTZ clocks are Central

-- #####################################################################
--  V162 PREFLIGHT  (from outputs/gen_v162.py; previews snowflake/migrations/V162__security_takeover_admin_grant.sql)
-- #####################################################################
-- ====================================================================================================
--  V162 PREFLIGHT (read-only; run BEFORE applying V162). Next-Fifty #39: SEC_LOGIN_TAKEOVER + SEC_ADMIN_GRANT.
--  Each grid runs the arm's OWN CTE chain (outputs/gen_v162.py) with the windows widened to 30 days.
--  IN_FIRST_RUN_WINDOW = TRUE rows are exactly what the first hourly scan after the apply raises. Changes nothing.
-- ====================================================================================================

-- P162.1 SEC_LOGIN_TAKEOVER: every takeover episode anchored in the last 30 days (arm [26], 27h -> 723h read,
-- 24h -> 720h anchor window). N = the rule's THRESHOLD_NUM, 5 until V162 seeds it. BAND CRIT = CRITICAL
-- (off-hours Central or an admin-tier role held directly at the login); WARN = the rule severity (HIGH).
-- WEEK_BAND_EPISODES = episodes in the same ISO week and band (the noise estimate per week).
WITH
        k AS (
            SELECT GREATEST(CEIL(COALESCE(MAX(c.THRESHOLD_NUM), 5)), 2) AS N
            FROM (SELECT 1 AS ONE) o
            LEFT JOIN DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG c ON c.RULE_ID = 'SEC_LOGIN_TAKEOVER'
        ),
        ev AS (
            SELECT USER_NAME, EVENT_ID, EVENT_TIMESTAMP, IS_SUCCESS, CLIENT_IP, REPORTED_CLIENT_TYPE,
                   FIRST_AUTHENTICATION_FACTOR, ERROR_MESSAGE
            FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
            WHERE EVENT_TIMESTAMP >= DATEADD('hour', -723, CURRENT_TIMESTAMP())
        ),
        fl AS (
            SELECT USER_NAME, EVENT_TIMESTAMP,
                   ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY EVENT_TIMESTAMP, EVENT_ID) AS RN
            FROM ev
            WHERE IS_SUCCESS = 'NO'
        ),
        bend AS (
            -- a failure that closes >= N failures by the same user inside 15 minutes (the one N-1 rows back is <= 15 min older)
            SELECT f2.USER_NAME, f2.EVENT_TIMESTAMP AS TS
            FROM fl f2
            CROSS JOIN k
            JOIN fl f1
              ON f1.USER_NAME = f2.USER_NAME
             AND f1.RN = f2.RN - (k.N - 1)
             AND f1.EVENT_TIMESTAMP >= DATEADD('minute', -15, f2.EVENT_TIMESTAMP)
        ),
        seq AS (
            -- one time-ordered stream per burst user: burst ends, then successes; LAST_BEND = newest burst end before the row
            SELECT s.USER_NAME, s.TS, s.IS_SUCC, s.EVENT_ID, s.CLIENT_IP, s.CLIENT_TYPE, s.AUTH_FACTOR,
                   MAX(IFF(s.IS_SUCC, NULL, s.TS)) OVER (PARTITION BY s.USER_NAME ORDER BY s.TS, s.IS_SUCC
                                                         ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS LAST_BEND
            FROM (
                SELECT USER_NAME, TS, FALSE AS IS_SUCC, NULL AS EVENT_ID, NULL AS CLIENT_IP, NULL AS CLIENT_TYPE,
                       NULL AS AUTH_FACTOR
                FROM bend
                UNION ALL
                SELECT USER_NAME, EVENT_TIMESTAMP, TRUE, EVENT_ID, CLIENT_IP, REPORTED_CLIENT_TYPE,
                       FIRST_AUTHENTICATION_FACTOR
                FROM ev
                WHERE IS_SUCCESS = 'YES'
                  AND USER_NAME IN (SELECT USER_NAME FROM bend)
            ) s
        ),
        brk AS (
            -- a success within 60 minutes after a burst ended; PREV_TS = the user's previous such success
            SELECT USER_NAME, TS, EVENT_ID, CLIENT_IP, CLIENT_TYPE, AUTH_FACTOR, LAST_BEND,
                   LAG(TS) OVER (PARTITION BY USER_NAME ORDER BY TS, EVENT_ID) AS PREV_TS
            FROM seq
            WHERE IS_SUCC
              AND LAST_BEND >= DATEADD('minute', -60, TS)
        ),
        anc AS (
            -- the episode anchor, raised only inside the alert window (its evidence lies wholly inside ev)
            SELECT USER_NAME, TS, EVENT_ID, CLIENT_IP, CLIENT_TYPE, AUTH_FACTOR, LAST_BEND,
                   CONVERT_TIMEZONE('America/Chicago', TS)::TIMESTAMP_NTZ AS TS_CT
            FROM brk
            WHERE (PREV_TS IS NULL OR PREV_TS < DATEADD('minute', -60, TS))
              AND TS >= DATEADD('hour', -720, CURRENT_TIMESTAMP())
        ),
        det AS (
            -- the anchor's evidence: every failure in the 75 minutes up to it (>= N by construction, a failure
            -- stamped in the same millisecond as the success included: seq orders it first)
            SELECT a.EVENT_ID, COUNT(*) AS N_FAIL, COUNT(DISTINCT f.CLIENT_IP) AS N_FAIL_IPS,
                   MIN(f.EVENT_TIMESTAMP) AS FIRST_FAIL, MAX(LEFT(COALESCE(f.ERROR_MESSAGE, ''), 200)) AS SAMPLE_ERROR
            FROM anc a
            JOIN ev f
              ON f.USER_NAME = a.USER_NAME
             AND f.IS_SUCCESS = 'NO'
             AND f.EVENT_TIMESTAMP <= a.TS
             AND f.EVENT_TIMESTAMP >= DATEADD('minute', -75, a.TS)
            GROUP BY a.EVENT_ID
        ),
        adm AS (
            -- admin-tier roles the user held AT the anchor (direct grants; owner list, same as SEC_ADMIN_GRANT)
            SELECT a.EVENT_ID, MIN(g.ROLE) AS ADMIN_ROLE, COUNT(DISTINCT g.ROLE) AS N_ADMIN_ROLES
            FROM anc a
            JOIN SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS g
              ON g.GRANTEE_NAME = a.USER_NAME
             AND g.ROLE IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'USERADMIN', 'ORGADMIN',
                            'SNOW_ACCOUNTADMINS', 'SNOW_SYSADMINS')
             AND g.CREATED_ON <= a.TS
             AND (g.DELETED_ON IS NULL OR g.DELETED_ON > a.TS)
            GROUP BY a.EVENT_ID
        ),
        x AS (
            SELECT a.USER_NAME, a.EVENT_ID, a.TS_CT, a.LAST_BEND, a.TS, a.CLIENT_IP, a.CLIENT_TYPE, a.AUTH_FACTOR,
                   d.N_FAIL, d.N_FAIL_IPS, d.FIRST_FAIL, d.SAMPLE_ERROR, m.ADMIN_ROLE, m.N_ADMIN_ROLES,
                   (HOUR(a.TS_CT) >= 20 OR HOUR(a.TS_CT) < 6 OR DAYOFWEEKISO(a.TS_CT) >= 6) AS OFF_HOURS
            FROM anc a
            JOIN det d ON d.EVENT_ID = a.EVENT_ID
            LEFT JOIN adm m ON m.EVENT_ID = a.EVENT_ID
        )
SELECT p.*, COUNT(*) OVER (PARTITION BY p.WEEK_START, p.BAND) AS WEEK_BAND_EPISODES
FROM (
    SELECT x.USER_NAME,
           IFF(x.OFF_HOURS OR x.ADMIN_ROLE IS NOT NULL, 'CRIT', 'WARN') AS BAND,
           TRIM(IFF(x.OFF_HOURS, 'off-hours ', '') || IFF(x.ADMIN_ROLE IS NOT NULL, 'admin role ' || x.ADMIN_ROLE, ''))
               AS CRIT_REASON,
           x.TS_CT AS SUCCESS_CENTRAL,
           DATEDIFF('minute', x.LAST_BEND, x.TS) AS MIN_AFTER_BURST,
           x.N_FAIL, x.N_FAIL_IPS, x.CLIENT_IP, x.CLIENT_TYPE, x.AUTH_FACTOR, x.SAMPLE_ERROR,
           TO_DATE(DATEADD('day', 1 - DAYOFWEEKISO(x.TS_CT), x.TS_CT)) AS WEEK_START,
           x.TS >= DATEADD('hour', -24, CURRENT_TIMESTAMP()) AS IN_FIRST_RUN_WINDOW,
           'SEC_LOGIN_TAKEOVER' || '|' || LEFT(x.USER_NAME, 200) || '|' || IFF(x.OFF_HOURS OR x.ADMIN_ROLE IS NOT NULL, 'CRIT', 'WARN') ||
                   '|' || TO_VARCHAR(CONVERT_TIMEZONE('UTC', x.TS)::TIMESTAMP_NTZ, 'YYYY-MM-DD HH24:MI:SS.FF3') AS DEDUPE_KEY_PREVIEW
    FROM x
) p
ORDER BY p.SUCCESS_CENTRAL DESC;

-- P162.2 SEC_ADMIN_GRANT: every direct admin-tier grant to a user in the last 30 days (arm [27], 26h -> 720h),
-- revoked or not, with the counts by role and by grantor (a SCIM / provisioning user shows up as one big grantor).
WITH
        ag AS (
            SELECT GRANTEE_NAME, ROLE, CREATED_ON, DELETED_ON, GRANTED_BY,
                   ROW_NUMBER() OVER (PARTITION BY GRANTEE_NAME, ROLE ORDER BY CREATED_ON) - 1 AS PRIOR_GRANTS,
                   CONVERT_TIMEZONE('America/Chicago', CREATED_ON)::TIMESTAMP_NTZ AS CREATED_CT
            FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
            WHERE ROLE IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'USERADMIN', 'ORGADMIN',
                           'SNOW_ACCOUNTADMINS', 'SNOW_SYSADMINS')
        )
SELECT q.*,
       COUNT(*) OVER (PARTITION BY q.ROLE) AS GRANTS_OF_ROLE_30D,
       COUNT(*) OVER (PARTITION BY q.GRANTED_BY) AS GRANTS_BY_GRANTOR_30D
FROM (
    SELECT g.GRANTEE_NAME, g.ROLE, g.GRANTED_BY, g.CREATED_CT AS GRANTED_CENTRAL,
           CONVERT_TIMEZONE('America/Chicago', g.DELETED_ON)::TIMESTAMP_NTZ AS REVOKED_CENTRAL,
           (HOUR(g.CREATED_CT) >= 20 OR HOUR(g.CREATED_CT) < 6 OR DAYOFWEEKISO(g.CREATED_CT) >= 6) AS OFF_HOURS,
           g.PRIOR_GRANTS = 0 AS FIRST_TIME, g.PRIOR_GRANTS,
           g.CREATED_ON >= DATEADD('hour', -26, CURRENT_TIMESTAMP()) AS IN_FIRST_RUN_WINDOW,
           LEFT('Admin role ' || g.ROLE || ' granted to ' || g.GRANTEE_NAME ||
                    IFF(HOUR(g.CREATED_CT) >= 20 OR HOUR(g.CREATED_CT) < 6 OR DAYOFWEEKISO(g.CREATED_CT) >= 6,
                        ' (off-hours)', '') ||
                    IFF(g.PRIOR_GRANTS = 0, ' - first time', ''), 300) AS TITLE_PREVIEW,
           'SEC_ADMIN_GRANT' || '|' || LEFT(g.GRANTEE_NAME, 200) || '|' || g.ROLE || '|' ||
                   TO_VARCHAR(g.CREATED_CT, 'YYYY-MM-DD HH24:MI:SS.FF3') AS DEDUPE_KEY_PREVIEW
    FROM ag g
    WHERE g.CREATED_ON >= DATEADD('hour', -720, CURRENT_TIMESTAMP())
) q
ORDER BY q.GRANTED_CENTRAL DESC;

-- P162.3 What SP_INCIDENT_AUTODECLARE sees now: OPEN/ACK CRITICAL events of the last 24h by rule and company, and
-- whether each rule still auto-declares after V162 (the two identity rules never do). INCIDENT_AUTO_DECLARE_CRITICAL
-- is the global switch (absent = TRUE).
SELECT e.RULE_ID, e.COMPANY, COUNT(*) AS OPEN_OR_ACK_CRITICAL_24H,
       COUNT_IF(m.REF_ID IS NULL) AS NOT_LINKED_TO_AN_INCIDENT,
       MIN(e.RAISED_AT) AS FIRST_RAISED, MAX(e.RAISED_AT) AS LAST_RAISED,
       IFF(e.RULE_ID IN ('SEC_LOGIN_TAKEOVER', 'SEC_ADMIN_GRANT'), 'never (V162)', 'yes') AS AUTO_DECLARES_AFTER_V162,
       MAX(sw.SWITCH_VALUE) AS INCIDENT_AUTO_DECLARE_CRITICAL
FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e
LEFT JOIN (SELECT DISTINCT REF_ID FROM DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS WHERE MEMBER_KIND = 'ALERT') m
       ON m.REF_ID = e.EVENT_ID
CROSS JOIN (SELECT COALESCE(MAX(VALUE), 'TRUE') AS SWITCH_VALUE FROM DBA_MAINT_DB.OVERWATCH.SETTINGS
            WHERE KEY = 'INCIDENT_AUTO_DECLARE_CRITICAL') sw
WHERE UPPER(e.SEVERITY) = 'CRITICAL'
  AND e.STATUS IN ('OPEN', 'ACK')
  AND e.RAISED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
GROUP BY e.RULE_ID, e.COMPANY
ORDER BY OPEN_OR_ACK_CRITICAL_24H DESC, e.RULE_ID;

-- P162.4 The CRITICAL takeovers the FIRST hourly scan after the apply raises: arm [26] with its OWN windows
-- (27h read, 24h anchors), so these are P162.1's BAND = CRIT, IN_FIRST_RUN_WINDOW = TRUE rows as of now.
-- V164's escalation census P164.2 cannot list them -- they do not exist until V162's first scan (the next :07
-- Central chain). Once V164 is applied, each one nobody acknowledges is re-posted to the Teams route that delivered
-- it (and emailed when the email leg is on) 120 minutes after its notification, about 2-3h after the apply. Read
-- these WITH P164.2: seed ('ESCALATE_AFTER_MIN', '0') before the apply and turn escalation on after triage, or
-- acknowledge / resolve these events within 2h of the first hourly scan.
WITH
        k AS (
            SELECT GREATEST(CEIL(COALESCE(MAX(c.THRESHOLD_NUM), 5)), 2) AS N
            FROM (SELECT 1 AS ONE) o
            LEFT JOIN DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG c ON c.RULE_ID = 'SEC_LOGIN_TAKEOVER'
        ),
        ev AS (
            SELECT USER_NAME, EVENT_ID, EVENT_TIMESTAMP, IS_SUCCESS, CLIENT_IP, REPORTED_CLIENT_TYPE,
                   FIRST_AUTHENTICATION_FACTOR, ERROR_MESSAGE
            FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
            WHERE EVENT_TIMESTAMP >= DATEADD('hour', -27, CURRENT_TIMESTAMP())
        ),
        fl AS (
            SELECT USER_NAME, EVENT_TIMESTAMP,
                   ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY EVENT_TIMESTAMP, EVENT_ID) AS RN
            FROM ev
            WHERE IS_SUCCESS = 'NO'
        ),
        bend AS (
            -- a failure that closes >= N failures by the same user inside 15 minutes (the one N-1 rows back is <= 15 min older)
            SELECT f2.USER_NAME, f2.EVENT_TIMESTAMP AS TS
            FROM fl f2
            CROSS JOIN k
            JOIN fl f1
              ON f1.USER_NAME = f2.USER_NAME
             AND f1.RN = f2.RN - (k.N - 1)
             AND f1.EVENT_TIMESTAMP >= DATEADD('minute', -15, f2.EVENT_TIMESTAMP)
        ),
        seq AS (
            -- one time-ordered stream per burst user: burst ends, then successes; LAST_BEND = newest burst end before the row
            SELECT s.USER_NAME, s.TS, s.IS_SUCC, s.EVENT_ID, s.CLIENT_IP, s.CLIENT_TYPE, s.AUTH_FACTOR,
                   MAX(IFF(s.IS_SUCC, NULL, s.TS)) OVER (PARTITION BY s.USER_NAME ORDER BY s.TS, s.IS_SUCC
                                                         ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS LAST_BEND
            FROM (
                SELECT USER_NAME, TS, FALSE AS IS_SUCC, NULL AS EVENT_ID, NULL AS CLIENT_IP, NULL AS CLIENT_TYPE,
                       NULL AS AUTH_FACTOR
                FROM bend
                UNION ALL
                SELECT USER_NAME, EVENT_TIMESTAMP, TRUE, EVENT_ID, CLIENT_IP, REPORTED_CLIENT_TYPE,
                       FIRST_AUTHENTICATION_FACTOR
                FROM ev
                WHERE IS_SUCCESS = 'YES'
                  AND USER_NAME IN (SELECT USER_NAME FROM bend)
            ) s
        ),
        brk AS (
            -- a success within 60 minutes after a burst ended; PREV_TS = the user's previous such success
            SELECT USER_NAME, TS, EVENT_ID, CLIENT_IP, CLIENT_TYPE, AUTH_FACTOR, LAST_BEND,
                   LAG(TS) OVER (PARTITION BY USER_NAME ORDER BY TS, EVENT_ID) AS PREV_TS
            FROM seq
            WHERE IS_SUCC
              AND LAST_BEND >= DATEADD('minute', -60, TS)
        ),
        anc AS (
            -- the episode anchor, raised only inside the alert window (its evidence lies wholly inside ev)
            SELECT USER_NAME, TS, EVENT_ID, CLIENT_IP, CLIENT_TYPE, AUTH_FACTOR, LAST_BEND,
                   CONVERT_TIMEZONE('America/Chicago', TS)::TIMESTAMP_NTZ AS TS_CT
            FROM brk
            WHERE (PREV_TS IS NULL OR PREV_TS < DATEADD('minute', -60, TS))
              AND TS >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
        ),
        det AS (
            -- the anchor's evidence: every failure in the 75 minutes up to it (>= N by construction, a failure
            -- stamped in the same millisecond as the success included: seq orders it first)
            SELECT a.EVENT_ID, COUNT(*) AS N_FAIL, COUNT(DISTINCT f.CLIENT_IP) AS N_FAIL_IPS,
                   MIN(f.EVENT_TIMESTAMP) AS FIRST_FAIL, MAX(LEFT(COALESCE(f.ERROR_MESSAGE, ''), 200)) AS SAMPLE_ERROR
            FROM anc a
            JOIN ev f
              ON f.USER_NAME = a.USER_NAME
             AND f.IS_SUCCESS = 'NO'
             AND f.EVENT_TIMESTAMP <= a.TS
             AND f.EVENT_TIMESTAMP >= DATEADD('minute', -75, a.TS)
            GROUP BY a.EVENT_ID
        ),
        adm AS (
            -- admin-tier roles the user held AT the anchor (direct grants; owner list, same as SEC_ADMIN_GRANT)
            SELECT a.EVENT_ID, MIN(g.ROLE) AS ADMIN_ROLE, COUNT(DISTINCT g.ROLE) AS N_ADMIN_ROLES
            FROM anc a
            JOIN SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS g
              ON g.GRANTEE_NAME = a.USER_NAME
             AND g.ROLE IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'USERADMIN', 'ORGADMIN',
                            'SNOW_ACCOUNTADMINS', 'SNOW_SYSADMINS')
             AND g.CREATED_ON <= a.TS
             AND (g.DELETED_ON IS NULL OR g.DELETED_ON > a.TS)
            GROUP BY a.EVENT_ID
        ),
        x AS (
            SELECT a.USER_NAME, a.EVENT_ID, a.TS_CT, a.LAST_BEND, a.TS, a.CLIENT_IP, a.CLIENT_TYPE, a.AUTH_FACTOR,
                   d.N_FAIL, d.N_FAIL_IPS, d.FIRST_FAIL, d.SAMPLE_ERROR, m.ADMIN_ROLE, m.N_ADMIN_ROLES,
                   (HOUR(a.TS_CT) >= 20 OR HOUR(a.TS_CT) < 6 OR DAYOFWEEKISO(a.TS_CT) >= 6) AS OFF_HOURS
            FROM anc a
            JOIN det d ON d.EVENT_ID = a.EVENT_ID
            LEFT JOIN adm m ON m.EVENT_ID = a.EVENT_ID
        )
SELECT x.USER_NAME,
       TRIM(IFF(x.OFF_HOURS, 'off-hours ', '') || IFF(x.ADMIN_ROLE IS NOT NULL, 'admin role ' || x.ADMIN_ROLE, ''))
           AS CRIT_REASON,
       x.TS_CT AS SUCCESS_CENTRAL, x.N_FAIL, x.CLIENT_IP,
       'raised by the first hourly scan after V162; escalates about 2-3h after the apply unless acknowledged'
           AS AFTER_APPLY,
       'SEC_LOGIN_TAKEOVER' || '|' || LEFT(x.USER_NAME, 200) || '|' || IFF(x.OFF_HOURS OR x.ADMIN_ROLE IS NOT NULL, 'CRIT', 'WARN') ||
                   '|' || TO_VARCHAR(CONVERT_TIMEZONE('UTC', x.TS)::TIMESTAMP_NTZ, 'YYYY-MM-DD HH24:MI:SS.FF3') AS DEDUPE_KEY_PREVIEW
FROM x
WHERE x.OFF_HOURS OR x.ADMIN_ROLE IS NOT NULL
ORDER BY x.TS_CT DESC;

-- #####################################################################
--  V163 PREFLIGHT  (from outputs/gen_v163.py; previews snowflake/migrations/V163__ai_runaway_trust_regression.sql)
-- #####################################################################
-- PREFLIGHT V163 (P163.1-P163.3) -- READ-ONLY preview of V163's two new daily rules. Changes nothing.
-- Run BEFORE applying V163 (or any time). Built from the scan's own arm text: only the read windows move, and
-- the rule rows and settings fall back to their seed values (2x the cap, z 3.5, Functions off) until V163 seeds
-- them.

-- P163.1 COST_AI_USER_RUNAWAY replayed over EVERY complete day of the last 90 (the arm itself scores the last 3), one row
--        per user: days over 1x and 2x the COCO_DAILY_CAP_CREDITS cap, WOULD_RAISE (both signals, or the cap alone
--        with no baseline), FIRST_RUN_RAISES (what the first scan after the apply raises: the last 3 days), the
--        USD of the would-raise days, and EVENT_COMPANY (the company the event would carry).
WITH cfg AS (     -- the rule row as seeded by V163, or its seed values before the apply
            SELECT 'COST_AI_USER_RUNAWAY' AS RULE_ID,
                   COALESCE(MAX(IFF(c.ENABLED, c.THRESHOLD_NUM, NULL)), 2) AS THRESHOLD_NUM
            FROM (SELECT 1 AS ONE) o
            LEFT JOIN DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG c ON c.RULE_ID = 'COST_AI_USER_RUNAWAY'
        ),
        clk AS (
            SELECT CONVERT_TIMEZONE('America/Chicago', CURRENT_TIMESTAMP())::DATE AS TODAY
        ),
        knob AS (
            SELECT COALESCE(NULLIF(GREATEST(COALESCE(TRY_TO_DOUBLE(MAX(IFF(KEY = 'COCO_DAILY_CAP_CREDITS', VALUE, NULL))), 15), 0), 0), 15) AS CAP_CR,
                   COALESCE(TRY_TO_DOUBLE(MAX(IFF(KEY = 'AI_RUNAWAY_ROBUST_Z', VALUE, NULL))), 3.5) AS Z_MIN,
                   COALESCE(TRY_TO_BOOLEAN(MAX(IFF(KEY = 'AI_RUNAWAY_INCLUDE_FUNCTIONS', VALUE, NULL))), FALSE) AS INCL_FN
            FROM DBA_MAINT_DB.OVERWATCH.SETTINGS
        ),
        px AS (      -- the scan's own AI price read (SP_ALERT_SCAN_DAILY, V160)
            SELECT COALESCE(TRY_TO_DOUBLE(MAX(IFF(KEY = 'AI_CREDIT_PRICE_USD', VALUE, NULL))), 2.20) AS AI_PRICE
            FROM DBA_MAINT_DB.OVERWATCH.SETTINGS
        ),
        ud AS (
            SELECT f.USER_NAME, f.DAY, SUM(f.CREDITS) AS CR,
                   LISTAGG(DISTINCT f.SOURCE, '+') WITHIN GROUP (ORDER BY f.SOURCE) AS SOURCES
            FROM DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY f
            CROSS JOIN clk k
            CROSS JOIN knob n
            WHERE f.DAY >= DATEADD('day', -183, k.TODAY) AND f.DAY < k.TODAY
              AND f.USER_NAME NOT IN ('ACCOUNT', 'UNKNOWN')
              AND (f.SOURCE <> 'Functions' OR n.INCL_FN)
            GROUP BY f.USER_NAME, f.DAY
            HAVING SUM(f.CREDITS) > 0
        ),
        cand AS (    -- every complete day of the last 90 (the arm scores the last 3, above the cap leg)
            SELECT u.USER_NAME, u.DAY, u.CR, u.SOURCES
            FROM ud u
            CROSS JOIN clk k
            WHERE u.DAY >= DATEADD('day', -90, k.TODAY)
        ),
        hist AS (
            SELECT c.USER_NAME, c.DAY, h.CR AS HCR
            FROM cand c
            JOIN ud h ON h.USER_NAME = c.USER_NAME AND h.DAY < c.DAY AND h.DAY >= DATEADD('day', -90, c.DAY)
        ),
        med AS (
            SELECT USER_NAME, DAY, MEDIAN(HCR) AS MED, COUNT(*) AS N_HIST
            FROM hist GROUP BY USER_NAME, DAY
        ),
        disp AS (
            SELECT h.USER_NAME, h.DAY, m.MED, m.N_HIST,
                   MEDIAN(ABS(h.HCR - m.MED)) AS MAD, AVG(ABS(h.HCR - m.MED)) AS MEAN_AD
            FROM hist h
            JOIN med m ON m.USER_NAME = h.USER_NAME AND m.DAY = h.DAY
            GROUP BY h.USER_NAME, h.DAY, m.MED, m.N_HIST
        ),
        scored AS (
            SELECT c.USER_NAME, c.DAY, c.CR, c.SOURCES, d.MED, COALESCE(d.N_HIST, 0) AS N_HIST,
                   CASE WHEN COALESCE(d.N_HIST, 0) < 5 THEN NULL
                        WHEN d.MAD > 0 THEN 0.6745 * (c.CR - d.MED) / d.MAD
                        WHEN d.MEAN_AD > 0 THEN 0.7979 * (c.CR - d.MED) / d.MEAN_AD
                        ELSE IFF(c.CR > d.MED, 999, 0) END AS Z
            FROM cand c
            LEFT JOIN disp d ON d.USER_NAME = c.USER_NAME AND d.DAY = c.DAY
        ),
        agg AS (
            SELECT s.USER_NAME,
                   COUNT(*) AS ACTIVE_DAYS_90,
                   COUNT_IF(s.CR > n.CAP_CR) AS OVER_CAP_1X,
                   COUNT_IF(s.CR > n.CAP_CR * 2) AS OVER_CAP_2X,
                   COUNT_IF(s.CR > n.CAP_CR * COALESCE(c.THRESHOLD_NUM, 2) AND (s.Z IS NULL OR s.Z >= n.Z_MIN)) AS WOULD_RAISE,
                   COUNT_IF(s.CR > n.CAP_CR * COALESCE(c.THRESHOLD_NUM, 2) AND (s.Z IS NULL OR s.Z >= n.Z_MIN) AND s.Z IS NULL) AS WOULD_RAISE_NO_BASELINE,
                   COUNT_IF(s.CR > n.CAP_CR * COALESCE(c.THRESHOLD_NUM, 2) AND (s.Z IS NULL OR s.Z >= n.Z_MIN) AND s.DAY >= DATEADD('day', -3, k.TODAY)) AS FIRST_RUN_RAISES,
                   ROUND(MAX(s.CR), 2) AS MAX_DAY_CREDITS,
                   ROUND(MEDIAN(s.CR), 2) AS MEDIAN_DAY_CREDITS,
                   ROUND(SUM(IFF(s.CR > n.CAP_CR * COALESCE(c.THRESHOLD_NUM, 2) AND (s.Z IS NULL OR s.Z >= n.Z_MIN), s.CR, 0)) * MAX(p.AI_PRICE), 2) AS WOULD_RAISE_USD
            FROM scored s
            CROSS JOIN knob n
            CROSS JOIN clk k
            CROSS JOIN px p
            JOIN cfg c ON c.RULE_ID = 'COST_AI_USER_RUNAWAY'
            GROUP BY s.USER_NAME
        )
SELECT a.USER_NAME,
       COALESCE(NULLIF(DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(a.USER_NAME), 'UNKNOWN'), 'ALL') AS EVENT_COMPANY,
       a.ACTIVE_DAYS_90, a.OVER_CAP_1X, a.OVER_CAP_2X, a.WOULD_RAISE, a.WOULD_RAISE_NO_BASELINE,
       a.FIRST_RUN_RAISES, a.MAX_DAY_CREDITS, a.MEDIAN_DAY_CREDITS, a.WOULD_RAISE_USD
FROM agg a
ORDER BY a.WOULD_RAISE DESC, a.OVER_CAP_1X DESC, a.USER_NAME;

-- P163.2 FACT_AI_USAGE_DAILY depth and who each source is booked to. Functions rows booked to ACCOUNT prove
--        AI_RUNAWAY_INCLUDE_FUNCTIONS changes nothing today (the arm skips ACCOUNT and UNKNOWN).
SELECT f.SOURCE,
       IFF(f.USER_NAME IN ('ACCOUNT', 'UNKNOWN'), f.USER_NAME, 'a named user') AS BOOKED_TO,
       MIN(f.DAY) AS FIRST_DAY, MAX(f.DAY) AS LAST_DAY, COUNT(DISTINCT f.DAY) AS DAYS,
       COUNT(DISTINCT f.USER_NAME) AS USERS, ROUND(SUM(f.CREDITS), 2) AS CREDITS
FROM DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY f
GROUP BY f.SOURCE, IFF(f.USER_NAME IN ('ACCOUNT', 'UNKNOWN'), f.USER_NAME, 'a named user')
ORDER BY f.SOURCE, BOOKED_TO;

-- P163.3 SEC_TRUST_REGRESSION replayed over the last 30 days: every rise, plus the latest row per scanner (does
--        any scanner run at all?), its snapshot days and its zero days (the loader books a scanner missing
--        from FINDINGS as 0, so a return from 0 reads as a rise). IN_FIRST_RUN = dated today or yesterday.
WITH clk AS (
            SELECT CONVERT_TIMEZONE('America/Chicago', CURRENT_TIMESTAMP())::DATE AS TODAY
        ),
        snap AS (
            SELECT t.SCANNER_ID, t.SCANNER_NAME, UPPER(t.SEVERITY) AS SEV, t.DAY, t.SCANNED_AT,
                   t.TOTAL_AT_RISK_COUNT AS CUR_N,
                   LAG(t.TOTAL_AT_RISK_COUNT) OVER (PARTITION BY t.SCANNER_ID ORDER BY t.DAY) AS PRIOR_N,
                   LAG(t.DAY) OVER (PARTITION BY t.SCANNER_ID ORDER BY t.DAY) AS PRIOR_DAY
            FROM DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT t
            CROSS JOIN clk k
            WHERE t.DAY >= DATEADD('day', -60, k.TODAY)
        ),
        thr AS (     -- the rule row as seeded by V163, or its seed value before the apply
            SELECT COALESCE(MAX(IFF(c.ENABLED, c.THRESHOLD_NUM, NULL)), 1) AS THRESHOLD_NUM
            FROM (SELECT 1 AS ONE) o
            LEFT JOIN DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG c ON c.RULE_ID = 'SEC_TRUST_REGRESSION'
        ),
        r AS (
            SELECT s.SCANNER_ID, s.SCANNER_NAME, s.SEV, s.DAY, s.PRIOR_DAY, s.PRIOR_N, s.CUR_N,
                   ROW_NUMBER() OVER (PARTITION BY s.SCANNER_ID ORDER BY s.DAY DESC) AS RN,
                   COUNT(*) OVER (PARTITION BY s.SCANNER_ID) AS SNAPSHOT_DAYS,
                   SUM(IFF(s.CUR_N = 0, 1, 0)) OVER (PARTITION BY s.SCANNER_ID) AS ZERO_DAYS
            FROM snap s
        )
SELECT r.SCANNER_ID, r.SCANNER_NAME, r.SEV, r.DAY, r.PRIOR_DAY, r.PRIOR_N, r.CUR_N, r.SNAPSHOT_DAYS, r.ZERO_DAYS,
       IFF(r.RN = 1, 'LATEST', '') AS LATEST_ROW,
       (r.PRIOR_N IS NOT NULL AND r.CUR_N > 0 AND r.CUR_N - r.PRIOR_N >= COALESCE(t.THRESHOLD_NUM, 1) AND r.SEV IN ('CRITICAL', 'HIGH')) AS WOULD_RAISE,
       (r.DAY >= DATEADD('day', -1, k.TODAY)) AS IN_FIRST_RUN,
       IFF(r.PRIOR_N = 0 AND r.CUR_N > 0, 'rise from a 0 day', '') AS NOTE
FROM r
CROSS JOIN thr t
CROSS JOIN clk k
WHERE r.DAY >= DATEADD('day', -30, k.TODAY)
  AND (r.RN = 1 OR (r.PRIOR_N IS NOT NULL AND r.CUR_N > r.PRIOR_N))
ORDER BY r.SCANNER_ID, r.DAY;

-- #####################################################################
--  V164 PREFLIGHT  (from outputs/gen_v164.py; previews snowflake/migrations/V164__notify_actionable_lines_escalation.sql)
-- #####################################################################
-- ======================================================================================================
-- V164 (Next-Fifty #40) PREFLIGHT -- READ-ONLY. Run BEFORE applying V164; changes nothing, sends nothing.
-- ======================================================================================================
-- P164.1 The email leg. OVERWATCH_EMAIL must be ENABLED and carry DEFAULT_RECIPIENTS: the escalation email is sent
--        with the notification-integration send, which goes to the integration's DEFAULT_RECIPIENTS (no address is
--        in git or in SETTINGS). BOOLEANS ONLY -- this grid never shows an address.
--        expect: ENABLED TRUE, DEFAULT_RECIPIENTS_SET TRUE (DEFAULT_SUBJECT_SET TRUE is nicer: the subject line).
--        If DEFAULT_RECIPIENTS_SET is FALSE: set it in Snowsight (docs/EMAIL_RECIPIENT_RUNBOOK.md, requirement 4),
--        or seed ('ESCALATE_EMAIL_INTEGRATION', '') before the apply for a Teams-only escalation.
DESC INTEGRATION OVERWATCH_EMAIL;
SELECT BOOLOR_AGG("property" = 'ENABLED' AND UPPER(TRIM("property_value")) = 'TRUE') AS ENABLED,
       BOOLOR_AGG("property" = 'DEFAULT_RECIPIENTS'
                  AND LOWER(COALESCE(TRIM("property_value"), '')) NOT IN ('', '[]', 'null')) AS DEFAULT_RECIPIENTS_SET,
       BOOLOR_AGG("property" = 'DEFAULT_SUBJECT'
                  AND LOWER(COALESCE(TRIM("property_value"), '')) NOT IN ('', '[]', 'null')) AS DEFAULT_SUBJECT_SET,
       BOOLOR_AGG("property" = 'ALLOWED_RECIPIENTS'
                  AND LOWER(COALESCE(TRIM("property_value"), '')) NOT IN ('', '[]', 'null')) AS ALLOWED_RECIPIENTS_SET
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
--        The proc runs as its owner (SNOW_ACCOUNTADMINS), which needs USAGE on the integration.
--        expect: SNOW_ACCOUNTADMINS_CAN_USE TRUE. FALSE is not final when SNOW_ACCOUNTADMINS inherits a role that
--        holds USAGE (the native email alerts it owns already send through this integration).
SHOW GRANTS ON INTEGRATION OVERWATCH_EMAIL;
SELECT BOOLOR_AGG("grantee_name" = 'SNOW_ACCOUNTADMINS' AND "privilege" IN ('USAGE', 'OWNERSHIP'))
           AS SNOW_ACCOUNTADMINS_CAN_USE,
       MAX(IFF("privilege" = 'OWNERSHIP', "grantee_name", NULL)) AS OWNER_ROLE
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- P164.2 First-run escalation census: V164's OWN capture text (binds swapped for the k columns; the ESCALATED_AT
--        line dropped -- the column does not exist before the apply). Every row escalates on the first hourly run
--        after the apply; WOULD_SEND_FIRST_RUN = inside that run's 3000-char batch (the rest follow on later runs;
--        route-delivered events fill the batch first, EMAIL_ONLY rows after them). REPOST_TO = the enabled routes
--        that delivered it (the Teams re-post); EMAIL_LEG = the email goes too.
--        expect: only events you WANT re-posted and emailed. Acknowledge or resolve stale ones first, or seed
--        ('ESCALATE_AFTER_MIN', '0') before the apply and turn it on later in Admin > Settings.
--        NOT LISTED HERE: the CRITICAL takeovers V162's first hourly scan raises (they do not exist yet); they
--        escalate about 2-3h after the apply too. PREFLIGHT P162.4 lists them: decide on both grids together.
WITH k AS (
    SELECT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS NOW_TS,
           COALESCE(TRY_TO_NUMBER(TRIM(COALESCE(MAX(IFF(KEY = 'ESCALATE_AFTER_MIN', VALUE, NULL)), '120'))), 0) AS AFTER_MIN,
           COALESCE(MAX(IFF(KEY = 'ESCALATE_EMAIL_INTEGRATION', VALUE, NULL)), 'OVERWATCH_EMAIL') AS EMAIL_INTEGRATION
    FROM DBA_MAINT_DB.OVERWATCH.SETTINGS
    WHERE KEY IN ('ESCALATE_AFTER_MIN', 'ESCALATE_EMAIL_INTEGRATION')
),
rp AS (
    SELECT d.EVENT_ID, LISTAGG(DISTINCT r.INTEGRATION_NAME, ', ') AS REPOST_TO
    FROM DBA_MAINT_DB.OVERWATCH.ALERT_DELIVERIES d
    JOIN DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES r ON r.ROUTE_ID = d.ROUTE_ID AND r.ENABLED
    GROUP BY d.EVENT_ID
),
cand AS (
    SELECT e.EVENT_ID, e.RULE_ID, e.COMPANY, e.RAISED_AT, e.NOTIFIED_AT, LEFT(e.TITLE, 120) AS TITLE,
           DATEDIFF('minute', COALESCE(e.NOTIFIED_AT, e.RAISED_AT), k.NOW_TS) AS UNACKED_MIN,
           COALESCE(TRIM(k.EMAIL_INTEGRATION), '') <> '' AS EMAIL_LEG, IFF(rd.EVENT_ID IS NULL, 1, 0) AS EMAIL_ONLY,
           SUM(LEN(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('ESCALATED (unacked ' || DATEDIFF('minute', COALESCE(e.NOTIFIED_AT, e.RAISED_AT), k.NOW_TS) || ' min) ' || '[' || e.SEVERITY || '] ' || LEFT(e.TITLE, 140) || ' | ' || e.COMPANY || IFF(COALESCE(TRIM(TRANSLATE(e.DETAIL, CHR(10) || CHR(13) || CHR(9), '   ')), '') = '', '', ' | ' || LEFT(TRIM(TRANSLATE(e.DETAIL, CHR(10) || CHR(13) || CHR(9), '   ')), 100)) || ' | event ' || e.EVENT_ID, CHR(92), CHR(92) || CHR(92)), CHR(34), CHR(92) || CHR(34)), CHR(10), CHR(92) || 'n'), CHR(13), ''), CHR(9), CHR(92) || 't')) + 2)
             OVER (ORDER BY IFF(rd.EVENT_ID IS NULL, 1, 0), e.RAISED_AT ASC, e.EVENT_ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) - 2 AS CUM_LEN
                FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e
                JOIN DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG c ON c.RULE_ID = e.RULE_ID
                LEFT JOIN (SELECT DISTINCT d.EVENT_ID
                           FROM DBA_MAINT_DB.OVERWATCH.ALERT_DELIVERIES d
                           JOIN DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES r
                             ON r.ROUTE_ID = d.ROUTE_ID AND r.ENABLED) rd
                  ON rd.EVENT_ID = e.EVENT_ID
                CROSS JOIN k
                WHERE e.SEVERITY = 'CRITICAL'
                  AND e.STATUS = 'OPEN'
                  AND e.ACK_AT IS NULL
                  AND e.RAISED_AT >= DATEADD('day', -7, k.NOW_TS)
                  AND COALESCE(e.NOTIFIED_AT, e.RAISED_AT) <= DATEADD('minute', -1 * k.AFTER_MIN, k.NOW_TS)
                  AND NOT EXISTS (SELECT 1
                                  FROM DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS m
                                  JOIN DBA_MAINT_DB.OVERWATCH.INCIDENTS i ON i.INCIDENT_ID = m.INCIDENT_ID
                                  WHERE m.MEMBER_KIND = 'ALERT' AND m.REF_ID = e.EVENT_ID
                                    AND (i.ACK_AT >= m.LINKED_AT
                                         OR (i.STATUS = 'MITIGATED' AND i.MITIGATED_AT >= m.LINKED_AT
                                             AND COALESCE(i.MITIGATED_BY, '') <> 'SP_INCIDENT_AUTODECLARE')
                                         OR (i.STATUS = 'RESOLVED' AND i.RESOLVED_AT >= m.LINKED_AT)))
                  AND NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT a
                                  WHERE a.EVENT_ID = e.EVENT_ID AND a.ACTION = 'SNOOZE')
                  AND NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS s
                                  WHERE s.RULE_ID = e.RULE_ID
                                    AND s.RESOLUTION_KIND = 'SNOOZE_SUPPRESSED'
                                    AND s.RAISED_AT < e.RAISED_AT
                                    AND s.RESOLVED_AT >= e.RAISED_AT
                                    AND IFF(SUBSTR(s.DEDUPE_KEY, -11, 1) = '|'
                                              AND TRY_TO_DATE(RIGHT(s.DEDUPE_KEY, 10)) IS NOT NULL,
                                            LEFT(s.DEDUPE_KEY, LENGTH(s.DEDUPE_KEY) - 11), s.DEDUPE_KEY)
                                        = IFF(SUBSTR(e.DEDUPE_KEY, -11, 1) = '|'
                                              AND TRY_TO_DATE(RIGHT(e.DEDUPE_KEY, 10)) IS NOT NULL,
                                            LEFT(e.DEDUPE_KEY, LENGTH(e.DEDUPE_KEY) - 11), e.DEDUPE_KEY))
                  AND (COALESCE(TRIM(k.EMAIL_INTEGRATION), '') <> '' OR rd.EVENT_ID IS NOT NULL)
                  AND k.AFTER_MIN > 0
)
SELECT x.EVENT_ID, x.RULE_ID, x.COMPANY, x.RAISED_AT, x.NOTIFIED_AT, x.UNACKED_MIN,
       COALESCE(rp.REPOST_TO, '(no route delivered it: email only)') AS REPOST_TO, x.EMAIL_LEG, x.EMAIL_ONLY,
       x.CUM_LEN <= 3000 AS WOULD_SEND_FIRST_RUN, x.TITLE
FROM cand x
LEFT JOIN rp ON rp.EVENT_ID = x.EVENT_ID
ORDER BY x.EMAIL_ONLY, x.RAISED_AT, x.EVENT_ID;

-- P164.3 Line length and throughput over 30 days of real deliveries: today's line vs the V164 line, and how many
--        runs (route x hour) would have needed more than max_batches = 6 batches with the longer line.
--        expect: RUNS_THAT_WOULD_SPILL 0 (a spill only delays the rest to the next hourly run; lever: max_batches).
WITH ev AS (
    SELECT d.ROUTE_ID, DATE_TRUNC('hour', d.SENT_AT) AS RUN_HOUR, e.EVENT_ID,
           LEN(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('[' || e.SEVERITY || '] ' || LEFT(e.TITLE, 140), CHR(92), CHR(92) || CHR(92)), CHR(34), CHR(92) || CHR(34)), CHR(10), CHR(92) || 'n'), CHR(13), ''), CHR(9), CHR(92) || 't')) AS OLD_LEN,
           LEN(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('[' || e.SEVERITY || '] ' || LEFT(e.TITLE, 140) || ' | ' || e.COMPANY || IFF(COALESCE(TRIM(TRANSLATE(e.DETAIL, CHR(10) || CHR(13) || CHR(9), '   ')), '') = '', '', ' | ' || LEFT(TRIM(TRANSLATE(e.DETAIL, CHR(10) || CHR(13) || CHR(9), '   ')), 100)) || ' | event ' || e.EVENT_ID, CHR(92), CHR(92) || CHR(92)), CHR(34), CHR(92) || CHR(34)), CHR(10), CHR(92) || 'n'), CHR(13), ''), CHR(9), CHR(92) || 't')) AS NEW_LEN
    FROM DBA_MAINT_DB.OVERWATCH.ALERT_DELIVERIES d
    JOIN DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e ON e.EVENT_ID = d.EVENT_ID
    WHERE d.SENT_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
),
per_run AS (
    SELECT ROUTE_ID, RUN_HOUR, COUNT(*) AS N,
           CEIL((SUM(OLD_LEN) + 2 * COUNT(*)) / 3000) AS OLD_BATCHES,
           CEIL((SUM(NEW_LEN) + 2 * COUNT(*)) / 3000) AS NEW_BATCHES
    FROM ev
    GROUP BY ROUTE_ID, RUN_HOUR
),
per_route AS (
    SELECT ROUTE_ID, ROUND(AVG(OLD_LEN)) AS AVG_LINE_TODAY, ROUND(AVG(NEW_LEN)) AS AVG_LINE_NEW,
           MAX(NEW_LEN) AS MAX_LINE_NEW
    FROM ev
    GROUP BY ROUTE_ID
)
SELECT p.ROUTE_ID, r.INTEGRATION_NAME, COUNT(*) AS RUNS_WITH_SENDS, MAX(p.N) AS PEAK_EVENTS_ONE_RUN,
       MAX(p.OLD_BATCHES) AS PEAK_BATCHES_TODAY, MAX(p.NEW_BATCHES) AS PEAK_BATCHES_NEW,
       COUNT_IF(p.NEW_BATCHES > 6) AS RUNS_THAT_WOULD_SPILL,
       MAX(a.AVG_LINE_TODAY) AS AVG_LINE_TODAY, MAX(a.AVG_LINE_NEW) AS AVG_LINE_NEW,
       MAX(a.MAX_LINE_NEW) AS MAX_LINE_NEW
FROM per_run p
JOIN per_route a ON a.ROUTE_ID = p.ROUTE_ID
LEFT JOIN DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES r ON r.ROUTE_ID = p.ROUTE_ID
GROUP BY p.ROUTE_ID, r.INTEGRATION_NAME
ORDER BY RUNS_THAT_WOULD_SPILL DESC, PEAK_EVENTS_ONE_RUN DESC;

-- P164.4 Cadence and routes: TASK_ALERT_NOTIFY started (state = started, predecessor TASK_ALERT_SCAN), and the
--        enabled routes the re-post can reach (a route re-posts only events it delivered itself).
SHOW TASKS LIKE 'TASK_ALERT_NOTIFY' IN SCHEMA DBA_MAINT_DB.OVERWATCH;
SELECT ROUTE_ID, FAMILY, MIN_SEVERITY, INTEGRATION_NAME, COALESCE(COMPANY_FILTER, 'ALL') AS COMPANY_FILTER,
       DELIVER_DIGEST
FROM DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES
WHERE ENABLED
ORDER BY ROUTE_ID;

-- #####################################################################
--  V165 PREFLIGHT  (from outputs/gen_v165.py; previews snowflake/migrations/V165__daily_digest_grounding.sql)
-- #####################################################################
-- PREFLIGHT_WAVE4 -- V165 section (READ-ONLY). Run before applying V165; changes nothing.
-- What the grids answer: P165.1a-e today's digest state (what V165 replaces); P165.2 V165's FACTS and templated
-- digest rendered from the live exec board, with V165's figure check (REGEXP_SUBSTR_ALL + FLATTEN, their first use
-- in this repo) run on the live engine; P165.3 (OPTIONAL, about 5 small Cortex calls) the new prompt drafted 5
-- times, each draft checked exactly as V165 will.

-- P165.1a the last 14 digests. expect one row a day; UNAVAILABLE TRUE = a Cortex failure that V112 sent as the body.
SELECT DIGEST_DATE, MODEL, LENGTH(BODY) AS BODY_LEN, STARTSWITH(BODY, 'Digest unavailable') AS UNAVAILABLE,
       LEFT(BODY, 300) AS BODY_START, CREATED_AT
  FROM DBA_MAINT_DB.OVERWATCH.DAILY_DIGEST
 ORDER BY DIGEST_DATE DESC
 LIMIT 14;

-- P165.1b the digest task, 14 days (ACCOUNT_USAGE, up to ~45 min behind). expect SUCCEEDED; RETURN_VALUE is NULL (a
--         task that CALLs a proc does not publish the proc's return string -- the V160.6 finding).
SELECT SCHEDULED_TIME, STATE, RETURN_VALUE, ERROR_MESSAGE
  FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
 WHERE DATABASE_NAME = 'DBA_MAINT_DB' AND SCHEMA_NAME = 'OVERWATCH' AND NAME = 'TASK_DAILY_DIGEST'
   AND SCHEDULED_TIME >= DATEADD('day', -14, CURRENT_TIMESTAMP())
 ORDER BY SCHEDULED_TIME DESC;

-- P165.1c digest ledger rows, 30 days, by type. expect none, or digest_send_failed / digest_undelivered if a route failed.
SELECT ERROR_TYPE, COUNT(*) AS N, MAX(LOGGED_AT) AS LAST_AT, MAX(LEFT(ERROR_MESSAGE, 200)) AS SAMPLE
  FROM DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG
 WHERE PAGE = 'DailyDigest' AND LOGGED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
 GROUP BY ERROR_TYPE
 ORDER BY N DESC;

-- P165.1d the digest-eligible routes (the V112 cursor). expect the HIGH Teams route.
SELECT r.ROUTE_ID, r.FAMILY, r.MIN_SEVERITY, r.INTEGRATION_NAME, r.DELIVER_DIGEST
  FROM DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES r
 WHERE r.ENABLED AND r.DELIVER_DIGEST AND UPPER(COALESCE(r.MIN_SEVERITY, '')) <> 'CRITICAL'
 ORDER BY r.ROUTE_ID;

-- P165.2 V165's FACTS and templated digest, rendered from the live exec board, and V165's figure check run on it
--        (RUN 1: the template, built only from the facts, expect GROUNDING_OK TRUE and FIGURES_CHECKED > 0) and on a
--        negative control (RUN 2: a figure no fact can match, expect GROUNDING_OK FALSE and UNGROUNDED '999999 critical').
--        TEMPLATED_BODY shows the mismatch wording; a Cortex failure changes only its first sentence.
--        COUNT_IF_ON_EMPTY expect 0: the proc counts a draft with no figures as grounded on that.
WITH kpi AS (
        SELECT (MAX(IFF(METRIC = 'CREDITS', VALUE_USD, NULL)))::NUMBER(38,2) AS F_SPEND_USD,
               (MAX(IFF(METRIC = 'CREDITS', VALUE, NULL)))::NUMBER(38,2) AS F_CREDITS,
               (MAX(IFF(METRIC = 'QUERIES', VALUE, NULL)))::NUMBER(38,0) AS F_QUERIES,
               (MAX(IFF(METRIC = 'FAILED_QUERIES', VALUE, NULL)))::NUMBER(38,0) AS F_FAILED_Q,
               (MAX(IFF(METRIC = 'QUEUED_MINUTES', VALUE, NULL)))::NUMBER(38,1) AS F_QUEUED_MIN,
               (MAX(IFF(METRIC = 'SPILL_GB', VALUE, NULL)))::NUMBER(38,2) AS F_SPILL_GB,
               (MAX(IFF(METRIC = 'TASK_RUNS', VALUE, NULL)))::NUMBER(38,0) AS F_TASK_RUNS,
               (MAX(IFF(METRIC = 'TASK_FAILURES', VALUE, NULL)))::NUMBER(38,0) AS F_TASK_FAIL
    FROM DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD
    WHERE COMPANY = 'ALL' AND WINDOW_DAYS = 7 AND PANEL = 'KPI'
    ),
    al AS (
        SELECT COUNT_IF(SEVERITY = 'CRITICAL' AND STATUS IN ('OPEN','ACK')) AS A_OPEN_CRIT,
               COUNT_IF(SEVERITY = 'HIGH' AND STATUS IN ('OPEN','ACK')) AS A_OPEN_HIGH,
               COUNT_IF(RAISED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())) AS A_RAISED_24H
        FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS
    ),
    b AS (SELECT kpi.*, al.* FROM kpi CROSS JOIN al),
    kr AS (
        SELECT b.*,
               (ROUND(100 * b.F_FAILED_Q / NULLIF(b.F_QUERIES, 0), 2))::NUMBER(38,2) AS F_FAILED_Q_PCT,
               (ROUND(100 * b.F_TASK_FAIL / NULLIF(b.F_TASK_RUNS, 0), 2))::NUMBER(38,2) AS F_TASK_FAIL_PCT
        FROM b
    ),
    k AS (
        SELECT kr.*,
               'WINDOW_DAYS=7; SPEND_USD=' || COALESCE(TO_VARCHAR(kr.F_SPEND_USD), 'n/a')
          || '; CREDITS=' || COALESCE(TO_VARCHAR(kr.F_CREDITS), 'n/a')
          || '; QUERIES=' || COALESCE(TO_VARCHAR(kr.F_QUERIES), 'n/a')
          || '; FAILED_QUERIES=' || COALESCE(TO_VARCHAR(kr.F_FAILED_Q), 'n/a')
          || '; FAILED_QUERY_PCT=' || COALESCE(TO_VARCHAR(kr.F_FAILED_Q_PCT), 'n/a')
          || '; QUERY_SUCCESS_PCT=' || COALESCE(TO_VARCHAR(100 - kr.F_FAILED_Q_PCT), 'n/a')
          || '; QUEUED_MINUTES=' || COALESCE(TO_VARCHAR(kr.F_QUEUED_MIN), 'n/a')
          || '; SPILL_GB=' || COALESCE(TO_VARCHAR(kr.F_SPILL_GB), 'n/a')
          || '; TASK_RUNS=' || COALESCE(TO_VARCHAR(kr.F_TASK_RUNS), 'n/a')
          || '; TASK_FAILURES=' || COALESCE(TO_VARCHAR(kr.F_TASK_FAIL), 'n/a')
          || '; TASK_FAILURE_PCT=' || COALESCE(TO_VARCHAR(kr.F_TASK_FAIL_PCT), 'n/a')
          || '; TASK_SUCCESS_PCT=' || COALESCE(TO_VARCHAR(100 - kr.F_TASK_FAIL_PCT), 'n/a')
          || '; ' || 'ALERT_WINDOW_HOURS=24; OPEN_CRITICAL_ALERTS=' || kr.A_OPEN_CRIT
           || '; OPEN_HIGH_ALERTS=' || kr.A_OPEN_HIGH || '; ALERTS_RAISED_24H=' || kr.A_RAISED_24H AS FACTS
        FROM kr
    ),
    tpl AS (
        SELECT 'Templated digest (not AI-written): '
             || IFF(FALSE IS NULL,
                    'Cortex returned no digest this morning, so OVERWATCH sent the exec-board facts directly.',
                    'the AI draft stated figures that do not match the exec-board facts, so OVERWATCH sent the facts directly.')
             || CHR(10) || CHR(10)
             || 'Last 7 days, all companies: spend ' || COALESCE('$' || TRIM(TO_VARCHAR(k.F_SPEND_USD, '999,999,999,990.00')), 'n/a')
             || ' (' || COALESCE(TRIM(TO_VARCHAR(k.F_CREDITS, '999,999,999,990.00')), 'n/a') || ' credits); '
             || COALESCE(TRIM(TO_VARCHAR(k.F_QUERIES, '999,999,999,990')), 'n/a') || ' queries, '
             || COALESCE(TRIM(TO_VARCHAR(k.F_FAILED_Q, '999,999,999,990')), 'n/a') || ' failed ('
             || COALESCE(TO_VARCHAR(k.F_FAILED_Q_PCT), 'n/a') || '%); '
             || COALESCE(TRIM(TO_VARCHAR(k.F_QUEUED_MIN, '999,999,999,990.0')), 'n/a') || ' minutes queued; '
             || COALESCE(TRIM(TO_VARCHAR(k.F_SPILL_GB, '999,999,999,990.00')), 'n/a') || ' GB spilled to remote storage; '
             || COALESCE(TRIM(TO_VARCHAR(k.F_TASK_RUNS, '999,999,999,990')), 'n/a') || ' task runs, '
             || COALESCE(TRIM(TO_VARCHAR(k.F_TASK_FAIL, '999,999,999,990')), 'n/a') || ' failed ('
             || COALESCE(TO_VARCHAR(k.F_TASK_FAIL_PCT), 'n/a') || '%).'
             || CHR(10) || CHR(10)
             || 'Alerts: ' || k.A_OPEN_CRIT || ' critical and ' || k.A_OPEN_HIGH || ' high open; '
             || k.A_RAISED_24H || ' raised in the last 24 hours.'
             || CHR(10) || CHR(10)
             || 'Focus: ' || CASE WHEN k.A_OPEN_CRIT > 0 THEN 'clear the ' || k.A_OPEN_CRIT || ' open critical alert(s) first.'
                                  WHEN k.A_OPEN_HIGH > 0 THEN 'work the ' || k.A_OPEN_HIGH || ' open high alert(s).'
                                  WHEN COALESCE(k.F_TASK_FAIL, 0) > 0 THEN 'review the ' || k.F_TASK_FAIL || ' failed task run(s).'
                                  ELSE 'nothing is open at critical or high; no action is needed today.' END AS BODY
        FROM k
    ),
    drafts AS (
        SELECT 1 AS RUN_ID, 'template' AS DRAFT_KIND, t.BODY, REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(t.BODY, '[0-9]{4}-[0-9]{2}-[0-9]{2}([ T][0-9]{1,2}:[0-9]{2}(:[0-9]{2})?)?', ' '), '[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?', ' '), '[A-Za-z_]+[0-9][A-Za-z0-9_]*', ' '), '[(][0-9]{1,2}[)]|#[0-9]{1,2}', ' '), '^[ *#]*[0-9]{1,2}[.)] ', ' ', 1, 0, 'm') AS CLEAN FROM tpl t
        UNION ALL
        SELECT 2, 'negative control', c.BODY, REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(c.BODY, '[0-9]{4}-[0-9]{2}-[0-9]{2}([ T][0-9]{1,2}:[0-9]{2}(:[0-9]{2})?)?', ' '), '[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?', ' '), '[A-Za-z_]+[0-9][A-Za-z0-9_]*', ' '), '[(][0-9]{1,2}[)]|#[0-9]{1,2}', ' '), '^[ *#]*[0-9]{1,2}[.)] ', ' ', 1, 0, 'm')
        FROM (SELECT 'There are 999999 critical alerts open.' AS BODY) c
    ),
    gr AS (
        SELECT g.RUN_ID, COUNT(*) AS FIGURES_CHECKED, COUNT_IF(NOT g.MATCHED) AS N_BAD,
               NULLIF(LEFT(LISTAGG(IFF(g.MATCHED, NULL, g.TOK), ', ') WITHIN GROUP (ORDER BY g.POS), 1000), '') AS UNGROUNDED
        FROM (
            SELECT t.RUN_ID, t.TOK, MIN(t.POS) AS POS, COUNT(f.FVAL) > 0 AS MATCHED
            FROM (
                SELECT u.RUN_ID, u.POS, u.TOK, u.UNIT, u.KEYWORD,
                       u.NUM_VAL * u.SCALE AS VAL,
                       GREATEST(0.5 * POWER(10, -u.DECIMALS) * u.SCALE, 0.005 * u.NUM_VAL * u.SCALE) AS TOL
                FROM (
                    SELECT w.RUN_ID, w.POS, w.TOK,
                           TRY_TO_DOUBLE(REPLACE(w.NUM, ',', '')) AS NUM_VAL,
                           IFF(CONTAINS(w.NUM, '.'), LENGTH(SPLIT_PART(w.NUM, '.', 2)), 0) AS DECIMALS,
                           CASE WHEN STARTSWITH(w.TOK, '$') THEN 'usd'
                                WHEN CONTAINS(w.TOK, '%') OR w.WORD IN ('percent', 'pct') THEN 'pct'
                                ELSE 'num' END AS UNIT,
                           CASE WHEN w.WORD IN ('k', 'thousand') THEN 1000
                                WHEN w.WORD IN ('m', 'mm', 'mn', 'million') THEN 1000000
                                WHEN w.WORD IN ('b', 'bn', 'billion') THEN 1000000000
                                ELSE 1 END AS SCALE,
                           CASE WHEN w.WORD LIKE 'credit%' THEN 'CREDIT'
                                WHEN w.WORD = 'critical' THEN 'CRITICAL'
                                WHEN w.WORD = 'high' THEN 'HIGH'
                                WHEN w.WORD LIKE 'minute%' THEN 'MINUTE'
                                WHEN w.WORD = 'gb' THEN '_GB'
                                WHEN w.WORD LIKE 'quer%' THEN 'QUER'
                                WHEN w.WORD LIKE 'fail%' THEN 'FAIL'
                                WHEN w.WORD LIKE 'task%' THEN 'TASK'
                                WHEN w.WORD LIKE 'alert%' THEN 'ALERT'
                                WHEN w.WORD LIKE 'hour%' THEN 'HOUR'
                                WHEN w.WORD LIKE 'day%' THEN 'DAY'
                                ELSE NULL END AS KEYWORD
                    FROM (
                        SELECT d.RUN_ID, x.INDEX AS POS, TRIM(x.VALUE::VARCHAR) AS TOK,
                               REGEXP_SUBSTR(x.VALUE::VARCHAR, '[0-9][0-9,]*([.][0-9]+)?') AS NUM,
                               LOWER(REGEXP_SUBSTR(x.VALUE::VARCHAR, '[A-Za-z]+')) AS WORD
                        FROM drafts d, TABLE(FLATTEN(INPUT => REGEXP_SUBSTR_ALL(d.CLEAN,
                             '[$]?([0-9]{1,3}(,[0-9]{3})+|[0-9]+)([.][0-9]+)?( ?[a-z]+)?( ?%)?', 1, 1, 'i'))) x
                    ) w
                ) u
            ) t
            LEFT JOIN (
                SELECT SPLIT_PART(p.VALUE::VARCHAR, '=', 1) AS FKEY,
                       TRY_TO_DOUBLE(SPLIT_PART(p.VALUE::VARCHAR, '=', 2)) AS FVAL
                FROM k, TABLE(FLATTEN(INPUT => REGEXP_SUBSTR_ALL(k.FACTS, '[A-Z][A-Z0-9_]*=[0-9]+([.][0-9]+)?'))) p
            ) f
              ON (t.UNIT = 'num' OR (t.UNIT = 'usd' AND ENDSWITH(f.FKEY, '_USD'))
                                 OR (t.UNIT = 'pct' AND ENDSWITH(f.FKEY, '_PCT')))
             AND (t.KEYWORD IS NULL OR CONTAINS(f.FKEY, t.KEYWORD))
             AND ABS(f.FVAL - t.VAL) <= t.TOL * 1.000000001
            GROUP BY t.RUN_ID, t.TOK
        ) g
        GROUP BY g.RUN_ID
    )
SELECT d.RUN_ID, d.DRAFT_KIND, COALESCE(gr.FIGURES_CHECKED, 0) AS FIGURES_CHECKED, COALESCE(gr.N_BAD, 0) AS N_BAD,
       gr.UNGROUNDED, COALESCE(gr.N_BAD, 0) = 0 AS GROUNDING_OK, k.FACTS, d.BODY AS TEMPLATED_BODY,
       (SELECT COUNT_IF(TRUE) FROM drafts z WHERE FALSE) AS COUNT_IF_ON_EMPTY
  FROM drafts d
  CROSS JOIN k
  LEFT JOIN gr ON gr.RUN_ID = d.RUN_ID
 ORDER BY d.RUN_ID;

-- P165.1e digest sends, 13 days (NOTIFICATION_HISTORY takes START_TIME and at most 336h), around the 07:20 CT run.
--         expect SUCCESS rows; none at all, or FAILED ones, confirm the unescaped-JSON card defect V165 fixes. Runs
--         after P165.2 so an unreadable function stops nothing else.
SELECT CONVERT_TIMEZONE('America/Chicago', CREATED)::TIMESTAMP_NTZ AS CREATED_CT, INTEGRATION_NAME, STATUS,
       LEFT(ERROR_MESSAGE, 200) AS ERROR_MESSAGE
  FROM TABLE(DBA_MAINT_DB.INFORMATION_SCHEMA.NOTIFICATION_HISTORY(
           START_TIME => DATEADD('day', -13, CURRENT_TIMESTAMP()), RESULT_LIMIT => 10000))
 WHERE INTEGRATION_NAME IN (SELECT r.INTEGRATION_NAME FROM DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES r
                             WHERE r.ENABLED AND r.DELIVER_DIGEST AND UPPER(COALESCE(r.MIN_SEVERITY, '')) <> 'CRITICAL')
   AND HOUR(CONVERT_TIMEZONE('America/Chicago', CREATED)) = 7
   AND MINUTE(CONVERT_TIMEZONE('America/Chicago', CREATED)) BETWEEN 15 AND 45
 ORDER BY CREATED DESC;

-- P165.3 OPTIONAL (about 5 small Cortex calls on CORTEX_MODEL; skip it by stopping here). The new prompt, drafted 5
--        times, each draft checked exactly as V165 will. WOULD_SEND 'TEMPLATE' is the expected template rate.
WITH kpi AS (
        SELECT (MAX(IFF(METRIC = 'CREDITS', VALUE_USD, NULL)))::NUMBER(38,2) AS F_SPEND_USD,
               (MAX(IFF(METRIC = 'CREDITS', VALUE, NULL)))::NUMBER(38,2) AS F_CREDITS,
               (MAX(IFF(METRIC = 'QUERIES', VALUE, NULL)))::NUMBER(38,0) AS F_QUERIES,
               (MAX(IFF(METRIC = 'FAILED_QUERIES', VALUE, NULL)))::NUMBER(38,0) AS F_FAILED_Q,
               (MAX(IFF(METRIC = 'QUEUED_MINUTES', VALUE, NULL)))::NUMBER(38,1) AS F_QUEUED_MIN,
               (MAX(IFF(METRIC = 'SPILL_GB', VALUE, NULL)))::NUMBER(38,2) AS F_SPILL_GB,
               (MAX(IFF(METRIC = 'TASK_RUNS', VALUE, NULL)))::NUMBER(38,0) AS F_TASK_RUNS,
               (MAX(IFF(METRIC = 'TASK_FAILURES', VALUE, NULL)))::NUMBER(38,0) AS F_TASK_FAIL
    FROM DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD
    WHERE COMPANY = 'ALL' AND WINDOW_DAYS = 7 AND PANEL = 'KPI'
    ),
    al AS (
        SELECT COUNT_IF(SEVERITY = 'CRITICAL' AND STATUS IN ('OPEN','ACK')) AS A_OPEN_CRIT,
               COUNT_IF(SEVERITY = 'HIGH' AND STATUS IN ('OPEN','ACK')) AS A_OPEN_HIGH,
               COUNT_IF(RAISED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())) AS A_RAISED_24H
        FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS
    ),
    b AS (SELECT kpi.*, al.* FROM kpi CROSS JOIN al),
    kr AS (
        SELECT b.*,
               (ROUND(100 * b.F_FAILED_Q / NULLIF(b.F_QUERIES, 0), 2))::NUMBER(38,2) AS F_FAILED_Q_PCT,
               (ROUND(100 * b.F_TASK_FAIL / NULLIF(b.F_TASK_RUNS, 0), 2))::NUMBER(38,2) AS F_TASK_FAIL_PCT
        FROM b
    ),
    k AS (
        SELECT kr.*,
               'WINDOW_DAYS=7; SPEND_USD=' || COALESCE(TO_VARCHAR(kr.F_SPEND_USD), 'n/a')
          || '; CREDITS=' || COALESCE(TO_VARCHAR(kr.F_CREDITS), 'n/a')
          || '; QUERIES=' || COALESCE(TO_VARCHAR(kr.F_QUERIES), 'n/a')
          || '; FAILED_QUERIES=' || COALESCE(TO_VARCHAR(kr.F_FAILED_Q), 'n/a')
          || '; FAILED_QUERY_PCT=' || COALESCE(TO_VARCHAR(kr.F_FAILED_Q_PCT), 'n/a')
          || '; QUERY_SUCCESS_PCT=' || COALESCE(TO_VARCHAR(100 - kr.F_FAILED_Q_PCT), 'n/a')
          || '; QUEUED_MINUTES=' || COALESCE(TO_VARCHAR(kr.F_QUEUED_MIN), 'n/a')
          || '; SPILL_GB=' || COALESCE(TO_VARCHAR(kr.F_SPILL_GB), 'n/a')
          || '; TASK_RUNS=' || COALESCE(TO_VARCHAR(kr.F_TASK_RUNS), 'n/a')
          || '; TASK_FAILURES=' || COALESCE(TO_VARCHAR(kr.F_TASK_FAIL), 'n/a')
          || '; TASK_FAILURE_PCT=' || COALESCE(TO_VARCHAR(kr.F_TASK_FAIL_PCT), 'n/a')
          || '; TASK_SUCCESS_PCT=' || COALESCE(TO_VARCHAR(100 - kr.F_TASK_FAIL_PCT), 'n/a')
          || '; ' || 'ALERT_WINDOW_HOURS=24; OPEN_CRITICAL_ALERTS=' || kr.A_OPEN_CRIT
           || '; OPEN_HIGH_ALERTS=' || kr.A_OPEN_HIGH || '; ALERTS_RAISED_24H=' || kr.A_RAISED_24H AS FACTS
        FROM kr
    ),
    m AS (
        SELECT COALESCE(MAX(IFF(KEY = 'CORTEX_MODEL', VALUE, NULL)), 'llama3.1-8b') AS MODEL
        FROM DBA_MAINT_DB.OVERWATCH.SETTINGS
    ),
    raw AS (
        SELECT SEQ4() + 1 AS RUN_ID,
               SNOWFLAKE.CORTEX.COMPLETE(m.MODEL, LEFT(
        'You are a senior Snowflake DBA writing the morning digest for ALFA/Trexis leadership. '
        || 'Use ONLY the FACTS below (the last 7 days, all companies; alert counts are open now or raised in the last 24 hours). '
        || 'Every number you write must be a FACT value, copied or rounded (thousands separators are fine): never calculate '
        || 'totals, averages, differences or new percentages, and never write dates or times. Dollar amounts come only from '
        || '*_USD facts and percentages only from *_PCT facts; CREDITS are Snowflake credits, not dollars. Write units in full '
        || '(credits, minutes, GB). Write three short unnumbered paragraphs: platform health and spend in plain language; '
        || 'what needs attention today and why; one recommended focus. No preamble. '
        || 'FACTS: ' || COALESCE(k.FACTS, 'none') || '.',
        6000)) AS BODY
        FROM TABLE(GENERATOR(ROWCOUNT => 5)) CROSS JOIN m CROSS JOIN k
    ),
    drafts AS (
        SELECT r.RUN_ID, r.BODY, REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(r.BODY, '[0-9]{4}-[0-9]{2}-[0-9]{2}([ T][0-9]{1,2}:[0-9]{2}(:[0-9]{2})?)?', ' '), '[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?', ' '), '[A-Za-z_]+[0-9][A-Za-z0-9_]*', ' '), '[(][0-9]{1,2}[)]|#[0-9]{1,2}', ' '), '^[ *#]*[0-9]{1,2}[.)] ', ' ', 1, 0, 'm') AS CLEAN FROM raw r
    ),
    gr AS (
        SELECT g.RUN_ID, COUNT(*) AS FIGURES_CHECKED, COUNT_IF(NOT g.MATCHED) AS N_BAD,
               NULLIF(LEFT(LISTAGG(IFF(g.MATCHED, NULL, g.TOK), ', ') WITHIN GROUP (ORDER BY g.POS), 1000), '') AS UNGROUNDED
        FROM (
            SELECT t.RUN_ID, t.TOK, MIN(t.POS) AS POS, COUNT(f.FVAL) > 0 AS MATCHED
            FROM (
                SELECT u.RUN_ID, u.POS, u.TOK, u.UNIT, u.KEYWORD,
                       u.NUM_VAL * u.SCALE AS VAL,
                       GREATEST(0.5 * POWER(10, -u.DECIMALS) * u.SCALE, 0.005 * u.NUM_VAL * u.SCALE) AS TOL
                FROM (
                    SELECT w.RUN_ID, w.POS, w.TOK,
                           TRY_TO_DOUBLE(REPLACE(w.NUM, ',', '')) AS NUM_VAL,
                           IFF(CONTAINS(w.NUM, '.'), LENGTH(SPLIT_PART(w.NUM, '.', 2)), 0) AS DECIMALS,
                           CASE WHEN STARTSWITH(w.TOK, '$') THEN 'usd'
                                WHEN CONTAINS(w.TOK, '%') OR w.WORD IN ('percent', 'pct') THEN 'pct'
                                ELSE 'num' END AS UNIT,
                           CASE WHEN w.WORD IN ('k', 'thousand') THEN 1000
                                WHEN w.WORD IN ('m', 'mm', 'mn', 'million') THEN 1000000
                                WHEN w.WORD IN ('b', 'bn', 'billion') THEN 1000000000
                                ELSE 1 END AS SCALE,
                           CASE WHEN w.WORD LIKE 'credit%' THEN 'CREDIT'
                                WHEN w.WORD = 'critical' THEN 'CRITICAL'
                                WHEN w.WORD = 'high' THEN 'HIGH'
                                WHEN w.WORD LIKE 'minute%' THEN 'MINUTE'
                                WHEN w.WORD = 'gb' THEN '_GB'
                                WHEN w.WORD LIKE 'quer%' THEN 'QUER'
                                WHEN w.WORD LIKE 'fail%' THEN 'FAIL'
                                WHEN w.WORD LIKE 'task%' THEN 'TASK'
                                WHEN w.WORD LIKE 'alert%' THEN 'ALERT'
                                WHEN w.WORD LIKE 'hour%' THEN 'HOUR'
                                WHEN w.WORD LIKE 'day%' THEN 'DAY'
                                ELSE NULL END AS KEYWORD
                    FROM (
                        SELECT d.RUN_ID, x.INDEX AS POS, TRIM(x.VALUE::VARCHAR) AS TOK,
                               REGEXP_SUBSTR(x.VALUE::VARCHAR, '[0-9][0-9,]*([.][0-9]+)?') AS NUM,
                               LOWER(REGEXP_SUBSTR(x.VALUE::VARCHAR, '[A-Za-z]+')) AS WORD
                        FROM drafts d, TABLE(FLATTEN(INPUT => REGEXP_SUBSTR_ALL(d.CLEAN,
                             '[$]?([0-9]{1,3}(,[0-9]{3})+|[0-9]+)([.][0-9]+)?( ?[a-z]+)?( ?%)?', 1, 1, 'i'))) x
                    ) w
                ) u
            ) t
            LEFT JOIN (
                SELECT SPLIT_PART(p.VALUE::VARCHAR, '=', 1) AS FKEY,
                       TRY_TO_DOUBLE(SPLIT_PART(p.VALUE::VARCHAR, '=', 2)) AS FVAL
                FROM k, TABLE(FLATTEN(INPUT => REGEXP_SUBSTR_ALL(k.FACTS, '[A-Z][A-Z0-9_]*=[0-9]+([.][0-9]+)?'))) p
            ) f
              ON (t.UNIT = 'num' OR (t.UNIT = 'usd' AND ENDSWITH(f.FKEY, '_USD'))
                                 OR (t.UNIT = 'pct' AND ENDSWITH(f.FKEY, '_PCT')))
             AND (t.KEYWORD IS NULL OR CONTAINS(f.FKEY, t.KEYWORD))
             AND ABS(f.FVAL - t.VAL) <= t.TOL * 1.000000001
            GROUP BY t.RUN_ID, t.TOK
        ) g
        GROUP BY g.RUN_ID
    )
SELECT d.RUN_ID, COALESCE(gr.FIGURES_CHECKED, 0) AS FIGURES_CHECKED, gr.UNGROUNDED,
       IFF(d.BODY IS NOT NULL AND TRIM(d.BODY) <> '' AND COALESCE(gr.N_BAD, 0) = 0, 'AI', 'TEMPLATE') AS WOULD_SEND,
       d.BODY AS AI_DRAFT
  FROM drafts d
  LEFT JOIN gr ON gr.RUN_ID = d.RUN_ID
 ORDER BY d.RUN_ID;

ALTER SESSION UNSET TIMEZONE;
