-- backfill_365.sql — OPT-IN, one-time: load a year of DAILY facts before
-- ACCOUNT_USAGE ages out (365-day retention). Unlocks YoY/QoQ comparisons
-- and materially improves the seasonal/ML forecast engines.
--
-- Idempotent by construction: each INSERT only takes days OLDER than what
-- the fact already holds, so re-running inserts nothing. Aggregations are
-- copies of the standing loaders' logic (SP_LOAD_DAILY_FACTS /
-- SP_LOAD_HOURLY_FACTS) — keep them in sync if a loader changes.
-- FACT_QUERY_HOURLY is deliberately NOT backfilled: a year at hourly x
-- warehouse x database x user grain is large and low-value vs the dailies.
-- Run as a role that can read SNOWFLAKE.ACCOUNT_USAGE and write the schema.
-- Expect a few minutes on WH_ALFA_OVERWATCH.

INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY
    (DAY, SERVICE_TYPE, CREDITS_COMPUTE, CREDITS_CLOUD_SVCS, CREDITS_ADJUSTMENT, CREDITS_USED, CREDITS_BILLED)
SELECT
    USAGE_DATE,
    UPPER(COALESCE(SERVICE_TYPE, 'UNKNOWN')),
    SUM(COALESCE(CREDITS_USED_COMPUTE, 0)),
    SUM(COALESCE(CREDITS_USED_CLOUD_SERVICES, 0)),
    SUM(COALESCE(CREDITS_ADJUSTMENT_CLOUD_SERVICES, 0)),
    SUM(COALESCE(CREDITS_USED, 0)),
    SUM(COALESCE(CREDITS_BILLED,
        GREATEST(0, COALESCE(CREDITS_USED, 0) + COALESCE(CREDITS_ADJUSTMENT_CLOUD_SERVICES, 0))))
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -365, CURRENT_DATE())
  AND USAGE_DATE < COALESCE((SELECT MIN(DAY) FROM DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY),
                            CURRENT_DATE())
GROUP BY 1, 2;

INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY
    (DAY, WAREHOUSE_NAME, COMPANY, CREDITS_COMPUTE, CREDITS_TOTAL)
SELECT
    DATE(START_TIME),
    WAREHOUSE_NAME,
    DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(WAREHOUSE_NAME),
    SUM(COALESCE(CREDITS_USED_COMPUTE, CREDITS_USED)),
    SUM(COALESCE(CREDITS_USED, 0))
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -365, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND DATE(START_TIME) < COALESCE((SELECT MIN(DAY) FROM DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY),
                                  CURRENT_DATE())
GROUP BY 1, 2, 3;

INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY
    (DAY, DATABASE_NAME, SCHEMA_NAME, TASK_NAME, COMPANY, RUNS, FAILED, AVG_SEC, LAST_STATE, LAST_ERROR)
SELECT
    DATE(QUERY_START_TIME),
    DATABASE_NAME,
    SCHEMA_NAME,
    NAME,
    DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME),
    COUNT(*),
    SUM(IFF(STATE = 'FAILED', 1, 0)),
    AVG(DATEDIFF('second', QUERY_START_TIME, COMPLETED_TIME)),
    MAX_BY(STATE, QUERY_START_TIME),
    MAX_BY(LEFT(COALESCE(ERROR_MESSAGE, ''), 500), QUERY_START_TIME)
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -365, CURRENT_DATE())
  AND DATE(QUERY_START_TIME) < COALESCE((SELECT MIN(DAY) FROM DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY),
                                        CURRENT_DATE())
GROUP BY 1, 2, 3, 4, 5;

INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY
    (DAY, USER_NAME, COMPANY, LOGINS, FAILED_LOGINS, PASSWORD_LOGINS)
SELECT
    DATE(EVENT_TIMESTAMP),
    USER_NAME,
    DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(USER_NAME),
    COUNT(*),
    SUM(IFF(IS_SUCCESS = 'NO', 1, 0)),
    SUM(IFF(FIRST_AUTHENTICATION_FACTOR = 'PASSWORD' AND IS_SUCCESS = 'YES', 1, 0))
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('day', -365, CURRENT_DATE())
  AND DATE(EVENT_TIMESTAMP) < COALESCE((SELECT MIN(DAY) FROM DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY),
                                       CURRENT_DATE())
GROUP BY 1, 2, 3;

INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY
    (DAY, DATABASE_NAME, COMPANY, DB_BYTES, FAILSAFE_BYTES)
SELECT
    USAGE_DATE,
    DATABASE_NAME,
    DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME),
    AVG(COALESCE(AVERAGE_DATABASE_BYTES, 0)),
    AVG(COALESCE(AVERAGE_FAILSAFE_BYTES, 0))
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -365, CURRENT_DATE())
  AND USAGE_DATE < COALESCE((SELECT MIN(DAY) FROM DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY),
                            CURRENT_DATE())
GROUP BY 1, 2, 3;

-- Verify: earliest day per fact should now be ~a year back.
SELECT 'FACT_METERING_DAILY' AS FACT, MIN(DAY) AS EARLIEST, COUNT(*) AS ROWS_ FROM DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY
UNION ALL SELECT 'FACT_WAREHOUSE_DAILY', MIN(DAY), COUNT(*) FROM DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY
UNION ALL SELECT 'FACT_TASK_DAILY', MIN(DAY), COUNT(*) FROM DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY
UNION ALL SELECT 'FACT_LOGIN_DAILY', MIN(DAY), COUNT(*) FROM DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY
UNION ALL SELECT 'FACT_STORAGE_DAILY', MIN(DAY), COUNT(*) FROM DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY;

-- ---------------------------------------------------------------------------
-- V027 mart family backfill (same loader codepath as the tasks — one truth).
-- QUERY_HISTORY-derived marts see at most ~365d. The two high-cardinality
-- marts (query families, cost allocation) default to 90d here on purpose:
-- widen deliberately if you accept the scan cost.
-- ---------------------------------------------------------------------------
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_MARTS_V27('HOURLY', 90);
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_MARTS_V27('DAILY', 365);
-- Optional full-year sweep for the cheap daily marts (wh efficiency, graphs):
-- CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_MARTS_V27('HOURLY', 365);

