-- roles.sql — OVERWATCH access roles. Run after migrations, as SECURITYADMIN
-- (role creation/grants) plus ACCOUNTADMIN for IMPORTED PRIVILEGES.

CREATE ROLE IF NOT EXISTS OVERWATCH_MONITOR
    COMMENT = 'Read-only OVERWATCH telemetry viewer';
CREATE ROLE IF NOT EXISTS OVERWATCH_OPERATOR
    COMMENT = 'OVERWATCH_MONITOR + settings/alert/action lifecycle writes';

-- ACCOUNT_USAGE access (required for live fallbacks and loaders' owner role).
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE OVERWATCH_MONITOR;

-- App objects: read for monitor.
-- NOTE: DBA_MAINT_DB.OVERWATCH is shared with the previous app's objects, so
-- ALL/FUTURE grants below cover those tables too. Intentional (owner
-- decision); tighten to per-table grants if that ever stops being acceptable.
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(VARCHAR) TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(VARCHAR) TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(VARCHAR) TO ROLE OVERWATCH_MONITOR;

-- Error sink: monitor may write errors (best-effort observability).
GRANT INSERT ON TABLE DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG TO ROLE OVERWATCH_MONITOR;

-- Compute for interactive use.
GRANT USAGE ON WAREHOUSE WH_ALFA_OVERWATCH TO ROLE OVERWATCH_MONITOR;

-- Operator: monitor + lifecycle writes. No DDL, no task control.
-- Per-user preferences (V013): every viewer writes their OWN rows
-- (the app always scopes to CURRENT_USER()); convenience, not security.
GRANT SELECT, INSERT, UPDATE, DELETE ON DBA_MAINT_DB.OVERWATCH.USER_PREFS TO ROLE OVERWATCH_MONITOR;
-- Usage analytics (V016): every viewer logs their own page visits.
GRANT INSERT ON DBA_MAINT_DB.OVERWATCH.APP_USAGE TO ROLE OVERWATCH_MONITOR;
GRANT INSERT ON DBA_MAINT_DB.OVERWATCH.APP_QUERY_TELEMETRY TO ROLE OVERWATCH_MONITOR;  -- V021 fleet telemetry

GRANT ROLE OVERWATCH_MONITOR TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.SETTINGS        TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS    TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT         ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT     TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG    TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE    TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER  TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT         ON TABLE DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE, DELETE ON TABLE DBA_MAINT_DB.OVERWATCH.DEPT_BUDGETS TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE, DELETE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES TO ROLE OVERWATCH_OPERATOR;

-- Audit tables are APPEND-ONLY for operators: history cannot be rewritten
-- by the people it audits. (Owner-role members technically still can —
-- that residual risk is documented in DEPLOYMENT.md.)
REVOKE UPDATE, DELETE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT     FROM ROLE OVERWATCH_OPERATOR;
REVOKE UPDATE, DELETE ON TABLE DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG FROM ROLE OVERWATCH_OPERATOR;

-- Role hierarchy (owner decision 2026-07): DBA work runs as
-- SNOW_ACCOUNTADMINS / SNOW_SYSADMINS, so both inherit the operator role.
GRANT ROLE OVERWATCH_OPERATOR TO ROLE SNOW_SYSADMINS;
GRANT ROLE OVERWATCH_OPERATOR TO ROLE SNOW_ACCOUNTADMINS;

-- Viewer roles (uncomment and adapt as read-only access is rolled out):
-- GRANT ROLE OVERWATCH_MONITOR  TO ROLE SNOW_PRI_GFR_PRD_ALFA_DTI;
-- GRANT ROLE OVERWATCH_MONITOR  TO ROLE SNOW_PRI_GFR_PRD_ALFA_PDMWMGMT;

SELECT 'roles applied' AS STATUS;
