-- teardown.sql — drop OVERWATCH objects for a clean drop-and-restore cycle.
--
-- SAFETY MODEL
--   * DBA_MAINT_DB.OVERWATCH is SHARED with the previous app's objects.
--     This script NEVER drops the schema or database — only the objects the
--     V001..V005 migrations create, each by fully qualified name.
--   * Section A (default): rebuildable objects only — tasks, procs, functions,
--     views, transient fact/mart tables. Re-running V001..V005 restores them
--     and the loaders repopulate from ACCOUNT_USAGE. No operator data is lost.
--   * Section B (commented out): OPERATOR DATA — settings, alert lifecycle,
--     action queue, savings ledger, audit/error logs. Only uncomment for a
--     true factory reset, and take the clone backups first.
--   * Section C (commented out): shared infrastructure — warehouse, resource
--     monitor, Streamlit app object, OVERWATCH_STAGE (app files live on
--     it — dropping it breaks the deployed app), roles.
--
-- RESTORE
--   1. Re-run snowflake/migrations/V001..V005 in order, then roles.sql.
--   2. Run snowflake/validate.sql — every row should be OK.
--   3. Accidentally dropped a permanent table? Time Travel has your back:
--        UNDROP TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
--      (works within the retention window; transient tables have 0-1 days).
--
-- Run as the deployment role that owns the objects (see DEPLOYMENT.md).

-- ===========================================================================
-- 0. PREFLIGHT — stop all scheduled work before dropping anything
-- ===========================================================================
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY       SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY        SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_EXEC_BOARD SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN        SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN_DAILY  SUSPEND;  -- V062 C9
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_NOTIFY      SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_DAILY_DIGEST      SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_VERIFY_SAVINGS    SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LEDGER_AUTOBOOK   SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SNAPSHOT_FRESHNESS SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_STORAGE_TRUTH SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_OBJECT_COST SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_APP_COST SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_QUERY_TELEMETRY SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_DRILL SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_QH_EXTRACT SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_OPS_DIAG_HOURLY SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_NIGHTLY_RECONCILE SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PLATFORM_SCORE_DAILY SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_SECURITY_FACTS SUSPEND;  -- V075
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SLO_BREACH_SCAN SUSPEND;  -- V085
ALTER ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_NEW_EVENTS  SUSPEND;
ALTER ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_STALE_FACTS SUSPEND;

-- ===========================================================================
-- A. REBUILDABLE OBJECTS (safe teardown — the default)
-- ===========================================================================

-- A1. Task chain (children first, then roots)
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_EXEC_BOARD;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN_DAILY;  -- V062 C9
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_NOTIFY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_DAILY_DIGEST;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_VERIFY_SAVINGS;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LEDGER_AUTOBOOK;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SNAPSHOT_FRESHNESS;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_QUERY_TELEMETRY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_DRILL;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CHANGE_IMPACT_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_WAREHOUSE_CHANGE_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_SECURITY_FACTS;  -- V075 child
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SLO_BREACH_SCAN;  -- V085 child
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_HOURLY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_DAILY;
-- V041 loader pass (children before the roots below)
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_OPS_DIAG_HOURLY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_QH_EXTRACT;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_NIGHTLY_RECONCILE;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PLATFORM_SCORE_DAILY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ANOMALY_SWEEP;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_FACTS;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_BACKUP_OPERATOR;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CANARY_SENTINEL;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_ML_FORECAST;  -- opt-in script
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_STORAGE_TRUTH;  -- V046
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_OBJECT_COST;  -- V048
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_APP_COST;  -- V077

-- A2. Native alert objects (opt-in delivery templates)
DROP ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_NEW_EVENTS;
DROP ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_STALE_FACTS;

-- A3. Procedures
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_HOURLY_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_DAILY_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_REFRESH_EXEC_BOARD();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ALERT_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ALERT_SCAN_DAILY();  -- V062 C9
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_SLO_BREACH_SCAN();  -- V085
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_NOTIFY_WEBHOOK();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_DAILY_DIGEST();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_VERIFY_IDLE_SAVINGS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CHANGE_IMPACT_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_WAREHOUSE_CHANGE_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LEDGER_AUTOBOOK();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_SNAPSHOT_FRESHNESS();
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SOURCE_FRESHNESS_STATE;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_STORAGE_TRUTH(FLOAT);  -- V046
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_OBJECT_COST(FLOAT);  -- V048
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_APP_COST(FLOAT);  -- V077
-- V051 action layer (scoped slice)
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ALERT_LIFECYCLE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ACTION_LIFECYCLE(VARCHAR, VARCHAR, VARCHAR, DATE, DATE, VARCHAR, VARCHAR, VARCHAR);  -- V074
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_VERIFY_EXPERIMENT(VARCHAR, VARCHAR, NUMBER, VARCHAR, VARCHAR, VARCHAR);  -- V081
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_SECURITY_FACTS(FLOAT);  -- V075
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OW_ACTION_INTENTS;  -- V051 idempotency ledger (rebuildable)
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_MARTS_V27(VARCHAR, FLOAT);
-- V041 loader pass
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_QH_EXTRACT(FLOAT);
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_OPS_DIAG(FLOAT);
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_PLATFORM_SCORE(FLOAT);
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_NIGHTLY_RECONCILE();
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OW_QH_EXTRACT;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OW_LOAD_WATERMARKS;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_COST_ALLOC_XDIM_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_OPS_DIAG_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_PLATFORM_SCORE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OW_EXEC_BOARD_STAGE;
-- V032 incident object: operator history (PRESERVED — no DROP here,
-- deliberately; uncomment only if you truly mean to erase the record):
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENTS;          -- lifecycle history
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS;   -- evidence links
-- Derived V032 objects drop for real:
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENT_PROPOSALS;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_INCIDENT_AUTODECLARE();
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_INCIDENT_AUTODECLARE;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CHANGE_ATTRIBUTION();
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CHANGE_ATTRIBUTION;

-- V027 marts: all rebuildable from ACCOUNT_USAGE (real drops, not preserved)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_WAREHOUSE_EFFICIENCY_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_QUERY_FAMILY_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_ROLE_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_SCHEMA_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_COST_ALLOCATION_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_TASK_GRAPH_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_TASK_NODE_DAILY;  -- V058 (per-node timing; loaded by SP_LOAD_MARTS_V27 arm [6b])
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SECURITY_POSTURE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_INCIDENT_TIMELINE;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_TAG_COVERAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_LOCK_WAIT_MART(FLOAT);
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(FLOAT);
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PATTERN_COST_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_CLOUD_SVC_DAILY;  -- V055 (loaded by SP_LOAD_QH_EXTRACT cascade, no own task)
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_CLOUD_SVC_MART();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ANOMALY_SWEEP();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_PURGE_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_BACKUP_OPERATOR_TABLES();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CANARY_SENTINEL();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_REFRESH_ML_FORECAST();  -- opt-in script
DROP DYNAMIC TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SPEND_ROLLUP_DT;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FORECAST_ML_DAILY;  -- opt-in script
-- Weekly *_BAK_LAST clones (SP_BACKUP_OPERATOR_TABLES) are safe to drop anytime.

-- A4. Functions
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(VARCHAR);
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(VARCHAR);
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(VARCHAR);

-- A5. Views
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SOURCE_FRESHNESS;
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_STATUS;
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.V_SECURITY_EXCEPTION_QUEUE;  -- V075
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.V_SECURITY_TRUST_DELTA;  -- V075

-- A6. Transient facts + marts (rebuilt from ACCOUNT_USAGE by the loaders)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY;  -- V075
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE;  -- V075
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT;  -- V075
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_ACCOUNT_DAILY;  -- V046
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY;  -- V048
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_APP_COST_DAILY;  -- V077
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DAILY_DIGEST;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SAVINGS_VERIFICATION_RUNS;

-- ===========================================================================
-- B. OPERATOR DATA — DESTRUCTIVE. Uncomment only for a factory reset.
--    Take the clone backups FIRST; they are your Time-Travel-independent copy.
-- ===========================================================================

-- B0. Backups (run these, verify row counts, then proceed)
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SETTINGS_BAK_20260707       CLONE DBA_MAINT_DB.OVERWATCH.SETTINGS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE_BAK_20260707  CLONE DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT_BAK_20260707    CLONE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG_BAK_20260707  CLONE DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.EVIDENCE_LINKS_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.EVIDENCE_LINKS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ENTITY_CATALOG_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.ENTITY_CATALOG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.USER_WATCHLIST_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.USER_WATCHLIST;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.OPTIMIZATION_EXPERIMENTS_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.OPTIMIZATION_EXPERIMENTS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SLO_OBJECTIVES_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.SLO_OBJECTIVES;

-- B1. Drops (order irrelevant; nothing references these)
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY;  -- frozen baselines are NOT rebuildable
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.WAREHOUSE_CHANGE_REGISTRY;  -- frozen baselines are NOT rebuildable
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.WAREHOUSE_CONFIG_SNAPSHOT;  -- change-detection history
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.USER_PREFS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DEPT_BUDGETS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_USAGE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.CANARY_RESULTS;
-- DROP STAGE IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_STAGE;  -- app files live here
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SETTINGS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.EVIDENCE_LINKS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ENTITY_CATALOG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.USER_WATCHLIST;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OPTIMIZATION_EXPERIMENTS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SLO_OBJECTIVES;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_QUERY_TELEMETRY;  -- V021 telemetry (rebuildable)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_DELIVERIES;  -- V022 delivery ledger
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OW_SENDER_LEASE;  -- V064 webhook single-flight lease (#26)

-- Opt-in script artifacts (2026-07-08 audit: these previously survived a
-- full teardown — the user's "do we drop email integrations?" catch).
DROP SNOWFLAKE.ML.FORECAST IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_SPEND_FORECAST;  -- ml_forecast_option.sql
DROP SECRET IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_WEBHOOK_URL;                    -- webhook_delivery.sql

-- ACCOUNT-LEVEL: notification integrations are not schema objects — run
-- these as ACCOUNTADMIN. IF EXISTS keeps them safe when a recipe was never
-- applied (PagerDuty/finops/email are copy-paste recipes).
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK;            -- webhook_delivery.sql
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_EMAIL;              -- native_alert_templates.sql recipe
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_PAGERDUTY;  -- recipe
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_FINOPS;
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_TEAMS;     -- recipe
DROP SECRET IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_TEAMS_URL;    -- recipe (webhook_delivery.sql)

-- To restore operator data after re-running migrations, INSERT ... SELECT from
-- the *_BAK_* clones (column lists match), then drop the clones.

-- ===========================================================================
-- C. SHARED INFRASTRUCTURE — uncomment only if you really mean it.
-- ===========================================================================
-- The warehouse also serves the Streamlit app; the resource monitor caps it;
-- roles may be granted into your role hierarchy.
-- DROP STREAMLIT IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_APP;
-- ALTER WAREHOUSE IF EXISTS WH_ALFA_ADMIN SET RESOURCE_MONITOR = NULL;  -- already NULL: V045
-- DROP WAREHOUSE IF EXISTS WH_ALFA_ADMIN;
-- DROP RESOURCE MONITOR IF EXISTS OVERWATCH_RM;  -- already dropped by V045 (owner correction)
-- Retired 2026-07-13 (owner: only SNOW_* roles have access) — roles.sql
-- drops these actively; teardown keeps every destructive line commented.
-- DROP ROLE IF EXISTS OVERWATCH_OPERATOR;
-- DROP ROLE IF EXISTS OVERWATCH_MONITOR;

-- ===========================================================================
-- VERIFY — after Section A, only operator-data tables should remain;
-- after A+B, this should return zero rows.
-- ===========================================================================
SELECT TABLE_NAME AS REMAINING_OVERWATCH_OBJECT, TABLE_TYPE
FROM DBA_MAINT_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'OVERWATCH'
  AND TABLE_NAME IN (
      'MART_EXEC_BOARD', 'MART_SOURCE_FRESHNESS',
      'FACT_METERING_DAILY', 'FACT_WAREHOUSE_DAILY', 'FACT_QUERY_HOURLY',
      'FACT_TASK_DAILY', 'FACT_LOGIN_DAILY', 'FACT_STORAGE_DAILY',
      'SETTINGS', 'COMPANY_SCOPE', 'SCHEMA_VERSION', 'APP_ERROR_LOG',
      'ALERT_CONFIG', 'ALERT_EVENTS', 'ALERT_AUDIT', 'OBJECT_CHANGE_REGISTRY',
      'WAREHOUSE_CHANGE_REGISTRY', 'WAREHOUSE_CONFIG_SNAPSHOT',
      'ALERT_ROUTES', 'REMEDIATION_LOG', 'USER_PREFS',
      'DEPT_BUDGETS', 'APP_USAGE', 'CANARY_RESULTS',
      'ACTION_QUEUE', 'SAVINGS_LEDGER',
      'PIPELINE_SLA_CONFIG', 'PIPELINE_SLA_STATUS',
      'DAILY_DIGEST', 'SAVINGS_VERIFICATION_RUNS', 'DEPARTMENT_MAP',
      'ACTION_ACTIVITY', 'EVIDENCE_LINKS', 'ENTITY_CATALOG', 'USER_WATCHLIST',
      'OPTIMIZATION_EXPERIMENTS', 'SLO_OBJECTIVES',
      'FACT_SECURITY_LOGIN_DAILY', 'FACT_SECURITY_CHANGE',
      'SECURITY_TRUST_SNAPSHOT'
  )
ORDER BY TABLE_NAME;
