-- teardown.sql — drop OVERWATCH objects for a clean drop-and-restore cycle.
--
-- SAFETY MODEL
--   * DBA_MAINT_DB.OVERWATCH is SHARED with the previous app's objects.
--     This script NEVER drops the schema or database — only the objects the
--     V001..V005 migrations create, each by fully qualified name.
--   * Section A (default): rebuildable objects only — tasks, procs, functions,
--     views, transient fact/mart tables. Re-running V001..V005 restores them
--     and the loaders repopulate from ACCOUNT_USAGE. No operator data is lost.
--   * Section B (commented out): OPERATOR DATA — settings, alert lifecycle,
--     action queue, savings ledger, audit/error logs. Only uncomment for a
--     true factory reset, and take the clone backups first.
--   * Section C (commented out): shared infrastructure — warehouse, resource
--     monitor, Streamlit app object, OVERWATCH_STAGE (app files live on
--     it — dropping it breaks the deployed app), roles.
--
-- RESTORE
--   1. Re-run snowflake/migrations/V001..V005 in order, then roles.sql.
--   2. Run snowflake/validate.sql — every row should be OK.
--   3. Accidentally dropped a permanent table? Time Travel has your back:
--        UNDROP TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
--      (works within the retention window; transient tables have 0-1 days).
--
-- Run as the deployment role that owns the objects (see DEPLOYMENT.md).

-- ===========================================================================
-- 0. PREFLIGHT — stop all scheduled work before dropping anything
-- ===========================================================================
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY       SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY        SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_EXEC_BOARD SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN        SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_NOTIFY      SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_DAILY_DIGEST      SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_VERIFY_SAVINGS    SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LEDGER_AUTOBOOK   SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_QUERY_TELEMETRY SUSPEND;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_DRILL SUSPEND;
ALTER ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_NEW_EVENTS  SUSPEND;
ALTER ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_STALE_FACTS SUSPEND;

-- ===========================================================================
-- A. REBUILDABLE OBJECTS (safe teardown — the default)
-- ===========================================================================

-- A1. Task chain (children first, then roots)
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_EXEC_BOARD;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_NOTIFY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_DAILY_DIGEST;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_VERIFY_SAVINGS;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LEDGER_AUTOBOOK;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_QUERY_TELEMETRY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ALERT_DRILL;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CHANGE_IMPACT_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_WAREHOUSE_CHANGE_SCAN;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_HOURLY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_DAILY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_ANOMALY_SWEEP;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PURGE_FACTS;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_BACKUP_OPERATOR;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CANARY_SENTINEL;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_ML_FORECAST;  -- opt-in script
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY;
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY;

-- A2. Native alert objects (opt-in delivery templates)
DROP ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_NEW_EVENTS;
DROP ALERT IF EXISTS DBA_MAINT_DB.OVERWATCH.NATIVE_ALERT_STALE_FACTS;

-- A3. Procedures
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_HOURLY_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_DAILY_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_REFRESH_EXEC_BOARD();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ALERT_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_NOTIFY_WEBHOOK();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_DAILY_DIGEST();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_VERIFY_IDLE_SAVINGS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CHANGE_IMPACT_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_WAREHOUSE_CHANGE_SCAN();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LEDGER_AUTOBOOK();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_MARTS_V27(VARCHAR, FLOAT);
-- V032 incident object: operator history (PRESERVED — no DROP here,
-- deliberately; uncomment only if you truly mean to erase the record):
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENTS;          -- lifecycle history
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS;   -- evidence links
-- Derived V032 objects drop for real:
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENT_PROPOSALS;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_INCIDENT_AUTODECLARE();
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_INCIDENT_AUTODECLARE;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CHANGE_ATTRIBUTION();
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_CHANGE_ATTRIBUTION;

-- V027 marts: all rebuildable from ACCOUNT_USAGE (real drops, not preserved)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_WAREHOUSE_EFFICIENCY_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_QUERY_FAMILY_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_ROLE_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_SCHEMA_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_COST_ALLOCATION_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_TASK_GRAPH_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SECURITY_POSTURE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_INCIDENT_TIMELINE;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_TAG_COVERAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_LOCK_WAIT_MART(FLOAT);
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(FLOAT);
DROP TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PATTERN_COST_DAILY;
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_ANOMALY_SWEEP();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_PURGE_FACTS();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_BACKUP_OPERATOR_TABLES();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_CANARY_SENTINEL();
DROP PROCEDURE IF EXISTS DBA_MAINT_DB.OVERWATCH.SP_REFRESH_ML_FORECAST();  -- opt-in script
DROP DYNAMIC TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SPEND_ROLLUP_DT;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FORECAST_ML_DAILY;  -- opt-in script
-- Weekly *_BAK_LAST clones (SP_BACKUP_OPERATOR_TABLES) are safe to drop anytime.

-- A4. Functions
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(VARCHAR);
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(VARCHAR);
DROP FUNCTION IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(VARCHAR);

-- A5. Views
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_SOURCE_FRESHNESS;
DROP VIEW IF EXISTS DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_STATUS;

-- A6. Transient facts + marts (rebuilt from ACCOUNT_USAGE by the loaders)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DAILY_DIGEST;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SAVINGS_VERIFICATION_RUNS;

-- ===========================================================================
-- B. OPERATOR DATA — DESTRUCTIVE. Uncomment only for a factory reset.
--    Take the clone backups FIRST; they are your Time-Travel-independent copy.
-- ===========================================================================

-- B0. Backups (run these, verify row counts, then proceed)
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SETTINGS_BAK_20260707       CLONE DBA_MAINT_DB.OVERWATCH.SETTINGS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE_BAK_20260707  CLONE DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT_BAK_20260707    CLONE DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE_BAK_20260707   CLONE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG_BAK_20260707  CLONE DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG;
-- CREATE TABLE DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP_BAK_20260707 CLONE DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP;

-- B1. Drops (order irrelevant; nothing references these)
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.OBJECT_CHANGE_REGISTRY;  -- frozen baselines are NOT rebuildable
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.WAREHOUSE_CHANGE_REGISTRY;  -- frozen baselines are NOT rebuildable
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.WAREHOUSE_CONFIG_SNAPSHOT;  -- change-detection history
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_ROUTES;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.USER_PREFS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DEPT_BUDGETS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_USAGE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.CANARY_RESULTS;
-- DROP STAGE IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_STAGE;  -- app files live here
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_CONFIG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_AUDIT;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.COMPANY_SCOPE;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SETTINGS;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG;
-- DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.DEPARTMENT_MAP;
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.APP_QUERY_TELEMETRY;  -- V021 telemetry (rebuildable)
DROP TABLE IF EXISTS DBA_MAINT_DB.OVERWATCH.ALERT_DELIVERIES;  -- V022 delivery ledger

-- Opt-in script artifacts (2026-07-08 audit: these previously survived a
-- full teardown — the user's "do we drop email integrations?" catch).
DROP SNOWFLAKE.ML.FORECAST IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_SPEND_FORECAST;  -- ml_forecast_option.sql
DROP SECRET IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_WEBHOOK_URL;                    -- webhook_delivery.sql

-- ACCOUNT-LEVEL: notification integrations are not schema objects — run
-- these as ACCOUNTADMIN. IF EXISTS keeps them safe when a recipe was never
-- applied (PagerDuty/finops/email are copy-paste recipes).
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK;            -- webhook_delivery.sql
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_EMAIL;              -- native_alert_templates.sql recipe
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_PAGERDUTY;  -- recipe
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_FINOPS;
DROP NOTIFICATION INTEGRATION IF EXISTS OVERWATCH_WEBHOOK_TEAMS;     -- recipe

-- To restore operator data after re-running migrations, INSERT ... SELECT from
-- the *_BAK_* clones (column lists match), then drop the clones.

-- ===========================================================================
-- C. SHARED INFRASTRUCTURE — uncomment only if you really mean it.
-- ===========================================================================
-- The warehouse also serves the Streamlit app; the resource monitor caps it;
-- roles may be granted into your role hierarchy.
-- DROP STREAMLIT IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_APP;
-- ALTER WAREHOUSE IF EXISTS WH_ALFA_OVERWATCH SET RESOURCE_MONITOR = NULL;
-- DROP WAREHOUSE IF EXISTS WH_ALFA_OVERWATCH;
-- DROP RESOURCE MONITOR IF EXISTS OVERWATCH_RM;
-- DROP ROLE IF EXISTS OVERWATCH_OPERATOR;
-- DROP ROLE IF EXISTS OVERWATCH_MONITOR;

-- ===========================================================================
-- VERIFY — after Section A, only operator-data tables should remain;
-- after A+B, this should return zero rows.
-- ===========================================================================
SELECT TABLE_NAME AS REMAINING_OVERWATCH_OBJECT, TABLE_TYPE
FROM DBA_MAINT_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'OVERWATCH'
  AND TABLE_NAME IN (
      'MART_EXEC_BOARD', 'MART_SOURCE_FRESHNESS',
      'FACT_METERING_DAILY', 'FACT_WAREHOUSE_DAILY', 'FACT_QUERY_HOURLY',
      'FACT_TASK_DAILY', 'FACT_LOGIN_DAILY', 'FACT_STORAGE_DAILY',
      'SETTINGS', 'COMPANY_SCOPE', 'SCHEMA_VERSION', 'APP_ERROR_LOG',
      'ALERT_CONFIG', 'ALERT_EVENTS', 'ALERT_AUDIT', 'OBJECT_CHANGE_REGISTRY',
      'WAREHOUSE_CHANGE_REGISTRY', 'WAREHOUSE_CONFIG_SNAPSHOT',
      'ALERT_ROUTES', 'REMEDIATION_LOG', 'USER_PREFS',
      'DEPT_BUDGETS', 'APP_USAGE', 'CANARY_RESULTS',
      'ACTION_QUEUE', 'SAVINGS_LEDGER',
      'PIPELINE_SLA_CONFIG', 'PIPELINE_SLA_STATUS',
      'DAILY_DIGEST', 'SAVINGS_VERIFICATION_RUNS', 'DEPARTMENT_MAP'
  )
ORDER BY TABLE_NAME;
