"""House law 1, enforced for EVERY forward generator (R1-297).

CLAUDE.md law 1: a re-derived migration is generated by outputs/gen_vNNN.py and its test regenerates and
byte-compares it. 65 generators had that test; 23 never ran anywhere (gen_v091, v101-v113, v115, v117,
v129, v130, v132, v133, v137, v140-v142, v146, v147), so an edit to one of those migrations -- or to its
generator -- passed CI (dropping V130's `OR P_VERIFIED_USD <= 0` proof guard stayed green). This runs
every outputs/gen_v*.py, so a new generator is covered the day it lands; the per-file regen tests stay.

Each generator resolves ROOT = parents[1] and writes its migration in place (most honor a VNNN_OUT
override, six do not), so it runs against a scratch MIRROR of snowflake/migrations, never the repo: its
own target is deleted first, the run must recreate it with the checked-in text (read_text -- the older
generators write CRLF on Windows; the content is what is locked), and no other migration may change.
Every write is fenced to the mirror (a generator that resolves ROOT anywhere else fails here instead of
rewriting another checkout -- gen_v091 did, R1-272). In-process (runpy) keeps all of them under ~2s.
"""

from __future__ import annotations

import io
import os
import re
import runpy
import shutil
import sys
from contextlib import redirect_stdout
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_MIG = _ROOT / "snowflake" / "migrations"
_GENERATORS = sorted((_ROOT / "outputs").glob("gen_v*.py"))


def _target(gen: Path) -> str:
    """gen_vNNN[a].py -> the one migration VNNN__*.sql it writes."""
    n = int(re.match(r"gen_v(\d+)", gen.stem).group(1))
    hits = sorted(p.name for p in _MIG.glob(f"V{n:03d}__*.sql"))
    assert len(hits) == 1, f"{gen.name}: expected exactly one V{n:03d}__*.sql, found {hits}"
    return hits[0]


@pytest.fixture(scope="module")
def mirror(tmp_path_factory):
    root = tmp_path_factory.mktemp("generator_mirror")
    shutil.copytree(_MIG, root / "snowflake" / "migrations")
    (root / "outputs").mkdir()
    return root


def test_the_sweep_sees_every_generator():
    assert len(_GENERATORS) >= 88
    assert {g.name for g in _GENERATORS} >= {"gen_v091.py", "gen_v101.py", "gen_v130.py", "gen_v147.py",
                                             "gen_v165.py", "gen_v166.py", "gen_v167.py", "gen_v168.py",
                                             "gen_v169.py", "gen_v170.py", "gen_v171.py", "gen_v172.py"}


@pytest.mark.parametrize("gen", _GENERATORS, ids=lambda p: p.stem)
def test_generator_regenerates_its_migration(gen, mirror, monkeypatch):
    src = gen.read_text(encoding="utf-8")
    assert "ROOT = Path(__file__).resolve().parents[1]" in src, (
        f"{gen.name}: resolve ROOT from the generator's own file, never a hardcoded checkout path")
    target = _target(gen)
    mig = mirror / "snowflake" / "migrations"
    before = {p.name: (p.stat().st_size, p.stat().st_mtime_ns) for p in mig.iterdir()}
    (mig / target).unlink()
    script = mirror / "outputs" / gen.name
    shutil.copy2(gen, script)
    for key in [k for k in os.environ if k.upper().endswith("_OUT")]:
        monkeypatch.delenv(key)    # VNNN_OUT / PREFLIGHT_OUT / PART_B_OUT: the in-tree default only
    real_write, real_open = Path.write_text, Path.open
    escaped: list[str] = []

    def _fence(path: Path) -> None:
        if not path.resolve().is_relative_to(mirror.resolve()):
            escaped.append(str(path))
            raise PermissionError(f"{gen.name} wrote outside its mirror: {path}")

    def fenced_write(self, *args, **kwargs):
        _fence(self)
        return real_write(self, *args, **kwargs)

    def fenced_open(self, mode="r", *args, **kwargs):
        if any(c in mode for c in "wax+"):           # gen_v152 / gen_v159 write through Path.open
            _fence(self)
        return real_open(self, mode, *args, **kwargs)

    monkeypatch.setattr(Path, "write_text", fenced_write)
    monkeypatch.setattr(Path, "open", fenced_open)
    saved_path = list(sys.path)
    try:
        with redirect_stdout(io.StringIO()):
            runpy.run_path(str(script), run_name="__main__")
    except SystemExit as exc:                      # a generator's own count-assert exits non-zero
        assert exc.code in (0, None), f"{gen.name} exited {exc.code}"
    finally:
        sys.path[:] = saved_path                   # gen_v079 prepends its ROOT for an app import
        monkeypatch.setattr(Path, "write_text", real_write)
        monkeypatch.setattr(Path, "open", real_open)
        # restore the checked-in text so one bad generator cannot cascade into the next
        regenerated = (mig / target).read_text(encoding="utf-8") if (mig / target).exists() else None
        shutil.copy2(_MIG / target, mig / target)
    assert not escaped, escaped
    assert regenerated is not None, f"{gen.name} did not write {target}"
    assert regenerated == (_MIG / target).read_text(encoding="utf-8"), (
        f"{target} drifted from its forward-generation -- edit {gen.name}, regenerate, "
        "never hand-edit the migration.")
    after = {p.name: (p.stat().st_size, p.stat().st_mtime_ns) for p in mig.iterdir() if p.name != target}
    assert after == {k: v for k, v in before.items() if k != target}, (
        f"{gen.name} touched a migration other than {target}")
