-- V002__facts.sql — app warehouse + resource monitor, compact fact tables,
-- bounded MERGE load procs, and the scheduled task chain root.
-- Idempotent. Adjust OVERWATCH_RM quota before running if 30 cr/mo is wrong.

-- ---------------------------------------------------------------------------
-- Dedicated compute with a hard monthly cap (the monitoring app must never
-- become the cost problem it monitors).
-- ---------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS OVERWATCH_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'OVERWATCH app + telemetry tasks. Keep XSMALL.';

CREATE RESOURCE MONITOR IF NOT EXISTS OVERWATCH_RM
    WITH CREDIT_QUOTA = 30
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE OVERWATCH_WH SET RESOURCE_MONITOR = OVERWATCH_RM;

-- ---------------------------------------------------------------------------
-- Fact tables (transient: rebuildable from ACCOUNT_USAGE)
-- ---------------------------------------------------------------------------
CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_METERING_DAILY (
    DAY                DATE          NOT NULL,
    SERVICE_TYPE       VARCHAR(100)  NOT NULL,
    CREDITS_COMPUTE    NUMBER(18,6),
    CREDITS_CLOUD_SVCS NUMBER(18,6),
    CREDITS_ADJUSTMENT NUMBER(18,6),
    CREDITS_USED       NUMBER(18,6),
    CREDITS_BILLED     NUMBER(18,6),
    LOAD_TS            TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_WAREHOUSE_DAILY (
    DAY             DATE          NOT NULL,
    WAREHOUSE_NAME  VARCHAR(200)  NOT NULL,
    COMPANY         VARCHAR(40)   NOT NULL,
    CREDITS_COMPUTE NUMBER(18,6),
    CREDITS_TOTAL   NUMBER(18,6),
    LOAD_TS         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_QUERY_HOURLY (
    HOUR_TS         TIMESTAMP_NTZ NOT NULL,
    WAREHOUSE_NAME  VARCHAR(200),
    DATABASE_NAME   VARCHAR(200),
    USER_NAME       VARCHAR(200),
    COMPANY         VARCHAR(40)   NOT NULL,
    QUERY_COUNT     NUMBER(12,0),
    FAILED_COUNT    NUMBER(12,0),
    ELAPSED_SEC_SUM NUMBER(18,3),
    P95_ELAPSED_SEC NUMBER(18,3),
    QUEUED_SEC_SUM  NUMBER(18,3),
    SPILL_REMOTE_GB NUMBER(18,4),
    LOAD_TS         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_TASK_DAILY (
    DAY           DATE          NOT NULL,
    DATABASE_NAME VARCHAR(200),
    SCHEMA_NAME   VARCHAR(200),
    TASK_NAME     VARCHAR(300)  NOT NULL,
    COMPANY       VARCHAR(40)   NOT NULL,
    RUNS          NUMBER(12,0),
    FAILED        NUMBER(12,0),
    AVG_SEC       NUMBER(18,3),
    LAST_STATE    VARCHAR(60),
    LAST_ERROR    VARCHAR(500),
    LOAD_TS       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_LOGIN_DAILY (
    DAY             DATE          NOT NULL,
    USER_NAME       VARCHAR(200)  NOT NULL,
    COMPANY         VARCHAR(40)   NOT NULL,
    LOGINS          NUMBER(12,0),
    FAILED_LOGINS   NUMBER(12,0),
    PASSWORD_LOGINS NUMBER(12,0),
    LOAD_TS         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH.MART.FACT_STORAGE_DAILY (
    DAY           DATE          NOT NULL,
    DATABASE_NAME VARCHAR(200)  NOT NULL,
    COMPANY       VARCHAR(40)   NOT NULL,
    DB_BYTES      NUMBER(24,0),
    FAILSAFE_BYTES NUMBER(24,0),
    LOAD_TS       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------------
-- Hourly loader: query facts (48h re-scan) + warehouse daily (3d re-scan)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE OVERWATCH.MART.SP_LOAD_HOURLY_FACTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    DELETE FROM OVERWATCH.MART.FACT_QUERY_HOURLY
     WHERE HOUR_TS >= DATEADD('hour', -48, CURRENT_TIMESTAMP());

    INSERT INTO OVERWATCH.MART.FACT_QUERY_HOURLY
        (HOUR_TS, WAREHOUSE_NAME, DATABASE_NAME, USER_NAME, COMPANY, QUERY_COUNT,
         FAILED_COUNT, ELAPSED_SEC_SUM, P95_ELAPSED_SEC, QUEUED_SEC_SUM, SPILL_REMOTE_GB)
    SELECT
        DATE_TRUNC('hour', START_TIME),
        WAREHOUSE_NAME,
        DATABASE_NAME,
        USER_NAME,
        OVERWATCH.CORE.COMPANY_FOR_WAREHOUSE(WAREHOUSE_NAME),
        COUNT(*),
        SUM(IFF(EXECUTION_STATUS = 'FAIL', 1, 0)),
        SUM(COALESCE(TOTAL_ELAPSED_TIME, 0)) / 1000,
        APPROX_PERCENTILE(TOTAL_ELAPSED_TIME / 1000, 0.95),
        SUM(COALESCE(QUEUED_OVERLOAD_TIME, 0) + COALESCE(QUEUED_PROVISIONING_TIME, 0)) / 1000,
        SUM(COALESCE(BYTES_SPILLED_TO_REMOTE_STORAGE, 0)) / POWER(1024, 3)
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('hour', -48, CURRENT_TIMESTAMP())
    GROUP BY 1, 2, 3, 4, 5;

    MERGE INTO OVERWATCH.MART.FACT_WAREHOUSE_DAILY t
    USING (
        SELECT
            DATE(START_TIME) AS DAY,
            WAREHOUSE_NAME,
            OVERWATCH.CORE.COMPANY_FOR_WAREHOUSE(WAREHOUSE_NAME) AS COMPANY,
            SUM(COALESCE(CREDITS_USED_COMPUTE, CREDITS_USED)) AS CREDITS_COMPUTE,
            SUM(COALESCE(CREDITS_USED, 0)) AS CREDITS_TOTAL
        FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD('day', -3, CURRENT_DATE())
        GROUP BY 1, 2, 3
    ) s
    ON t.DAY = s.DAY AND t.WAREHOUSE_NAME = s.WAREHOUSE_NAME
    WHEN MATCHED THEN UPDATE SET
        COMPANY = s.COMPANY, CREDITS_COMPUTE = s.CREDITS_COMPUTE,
        CREDITS_TOTAL = s.CREDITS_TOTAL, LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (DAY, WAREHOUSE_NAME, COMPANY, CREDITS_COMPUTE, CREDITS_TOTAL)
        VALUES (s.DAY, s.WAREHOUSE_NAME, s.COMPANY, s.CREDITS_COMPUTE, s.CREDITS_TOTAL);

    RETURN 'hourly facts loaded';
END;
$$;

-- ---------------------------------------------------------------------------
-- Daily loader: metering-daily (5d re-scan, adjustment applied), tasks,
-- logins, storage (3d re-scans)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE OVERWATCH.MART.SP_LOAD_DAILY_FACTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO OVERWATCH.MART.FACT_METERING_DAILY t
    USING (
        SELECT
            USAGE_DATE AS DAY,
            UPPER(COALESCE(SERVICE_TYPE, 'UNKNOWN')) AS SERVICE_TYPE,
            SUM(COALESCE(CREDITS_USED_COMPUTE, 0)) AS CREDITS_COMPUTE,
            SUM(COALESCE(CREDITS_USED_CLOUD_SERVICES, 0)) AS CREDITS_CLOUD_SVCS,
            SUM(COALESCE(CREDITS_ADJUSTMENT_CLOUD_SERVICES, 0)) AS CREDITS_ADJUSTMENT,
            SUM(COALESCE(CREDITS_USED, 0)) AS CREDITS_USED,
            SUM(COALESCE(CREDITS_BILLED,
                GREATEST(0, COALESCE(CREDITS_USED, 0) + COALESCE(CREDITS_ADJUSTMENT_CLOUD_SERVICES, 0)))) AS CREDITS_BILLED
        FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
        WHERE USAGE_DATE >= DATEADD('day', -5, CURRENT_DATE())
        GROUP BY 1, 2
    ) s
    ON t.DAY = s.DAY AND t.SERVICE_TYPE = s.SERVICE_TYPE
    WHEN MATCHED THEN UPDATE SET
        CREDITS_COMPUTE = s.CREDITS_COMPUTE, CREDITS_CLOUD_SVCS = s.CREDITS_CLOUD_SVCS,
        CREDITS_ADJUSTMENT = s.CREDITS_ADJUSTMENT, CREDITS_USED = s.CREDITS_USED,
        CREDITS_BILLED = s.CREDITS_BILLED, LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (DAY, SERVICE_TYPE, CREDITS_COMPUTE, CREDITS_CLOUD_SVCS, CREDITS_ADJUSTMENT, CREDITS_USED, CREDITS_BILLED)
        VALUES (s.DAY, s.SERVICE_TYPE, s.CREDITS_COMPUTE, s.CREDITS_CLOUD_SVCS, s.CREDITS_ADJUSTMENT, s.CREDITS_USED, s.CREDITS_BILLED);

    DELETE FROM OVERWATCH.MART.FACT_TASK_DAILY WHERE DAY >= DATEADD('day', -3, CURRENT_DATE());
    INSERT INTO OVERWATCH.MART.FACT_TASK_DAILY
        (DAY, DATABASE_NAME, SCHEMA_NAME, TASK_NAME, COMPANY, RUNS, FAILED, AVG_SEC, LAST_STATE, LAST_ERROR)
    SELECT
        DATE(QUERY_START_TIME),
        DATABASE_NAME,
        SCHEMA_NAME,
        NAME,
        OVERWATCH.CORE.COMPANY_FOR_DATABASE(DATABASE_NAME),
        COUNT(*),
        SUM(IFF(STATE = 'FAILED', 1, 0)),
        AVG(DATEDIFF('second', QUERY_START_TIME, COMPLETED_TIME)),
        MAX_BY(STATE, QUERY_START_TIME),
        MAX_BY(LEFT(COALESCE(ERROR_MESSAGE, ''), 500), QUERY_START_TIME)
    FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
    WHERE QUERY_START_TIME >= DATEADD('day', -3, CURRENT_DATE())
    GROUP BY 1, 2, 3, 4, 5;

    DELETE FROM OVERWATCH.MART.FACT_LOGIN_DAILY WHERE DAY >= DATEADD('day', -3, CURRENT_DATE());
    INSERT INTO OVERWATCH.MART.FACT_LOGIN_DAILY
        (DAY, USER_NAME, COMPANY, LOGINS, FAILED_LOGINS, PASSWORD_LOGINS)
    SELECT
        DATE(EVENT_TIMESTAMP),
        USER_NAME,
        OVERWATCH.CORE.COMPANY_FOR_USER(USER_NAME),
        COUNT(*),
        SUM(IFF(IS_SUCCESS = 'NO', 1, 0)),
        SUM(IFF(FIRST_AUTHENTICATION_FACTOR = 'PASSWORD' AND IS_SUCCESS = 'YES', 1, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
    WHERE EVENT_TIMESTAMP >= DATEADD('day', -3, CURRENT_DATE())
    GROUP BY 1, 2, 3;

    DELETE FROM OVERWATCH.MART.FACT_STORAGE_DAILY WHERE DAY >= DATEADD('day', -3, CURRENT_DATE());
    INSERT INTO OVERWATCH.MART.FACT_STORAGE_DAILY
        (DAY, DATABASE_NAME, COMPANY, DB_BYTES, FAILSAFE_BYTES)
    SELECT
        USAGE_DATE,
        DATABASE_NAME,
        OVERWATCH.CORE.COMPANY_FOR_DATABASE(DATABASE_NAME),
        AVG(COALESCE(AVERAGE_DATABASE_BYTES, 0)),
        AVG(COALESCE(AVERAGE_FAILSAFE_BYTES, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
    WHERE USAGE_DATE >= DATEADD('day', -3, CURRENT_DATE())
    GROUP BY 1, 2, 3;

    RETURN 'daily facts loaded';
END;
$$;

-- ---------------------------------------------------------------------------
-- Task chain roots (children are added by V003/V004 with AFTER)
-- ---------------------------------------------------------------------------
CREATE TASK IF NOT EXISTS OVERWATCH.MART.TASK_LOAD_HOURLY
    WAREHOUSE = OVERWATCH_WH
    SCHEDULE = 'USING CRON 7 * * * * America/Chicago'
    COMMENT = 'Hourly query/warehouse facts; exec board + alert scan chain after this.'
AS
    CALL OVERWATCH.MART.SP_LOAD_HOURLY_FACTS();

CREATE TASK IF NOT EXISTS OVERWATCH.MART.TASK_LOAD_DAILY
    WAREHOUSE = OVERWATCH_WH
    SCHEDULE = 'USING CRON 45 6 * * * America/Chicago'
    COMMENT = 'Daily metering (billed w/ adjustment), tasks, logins, storage.'
AS
    CALL OVERWATCH.MART.SP_LOAD_DAILY_FACTS();

-- Tasks are created suspended; V003 resumes the chain after children exist.

MERGE INTO OVERWATCH.CORE.SCHEMA_VERSION t
USING (SELECT 2 AS VERSION, 'facts: warehouse+monitor, 6 fact tables, loaders, task roots' AS DESCRIPTION) s
ON t.VERSION = s.VERSION
WHEN NOT MATCHED THEN INSERT (VERSION, DESCRIPTION) VALUES (s.VERSION, s.DESCRIPTION);

SELECT 'V002 applied' AS STATUS;
