-- V005__actions.sql — owner-routed action queue + verified savings ledger.
-- Permanent tables: this is operator-entered evidence that must survive
-- mart rebuilds. Idempotent.

CREATE TABLE IF NOT EXISTS OVERWATCH.CORE.ACTION_QUEUE (
    ACTION_ID    VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    CREATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    COMPANY      VARCHAR(40)   NOT NULL DEFAULT 'ALL',
    SEVERITY     VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',   -- CRITICAL|HIGH|MEDIUM|LOW
    TITLE        VARCHAR(300)  NOT NULL,
    DETAIL       VARCHAR(2000),
    OWNER        VARCHAR(200)  NOT NULL DEFAULT 'DBA',
    STATUS       VARCHAR(30)   NOT NULL DEFAULT 'OPEN',     -- OPEN|IN_PROGRESS|DONE|DROPPED
    DUE_DATE     DATE,
    SOURCE       VARCHAR(120),                              -- page/rule that raised it
    PROOF_SQL    VARCHAR(4000),
    ESTIMATED_USD NUMBER(18,2),
    UPDATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY   VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

-- Savings ledger: ESTIMATED -> VERIFIED (with proof) or REJECTED.
-- Estimated and verified dollars are never summed together anywhere.
CREATE TABLE IF NOT EXISTS OVERWATCH.CORE.SAVINGS_LEDGER (
    ITEM_ID      VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    ACTION_ID    VARCHAR(80),
    CREATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DESCRIPTION  VARCHAR(500)  NOT NULL,
    STATE        VARCHAR(20)   NOT NULL DEFAULT 'ESTIMATED',  -- ESTIMATED|VERIFIED|REJECTED
    ESTIMATED_USD NUMBER(18,2),
    VERIFIED_USD NUMBER(18,2),
    VERIFIED_AT  TIMESTAMP_NTZ,
    VERIFIED_BY  VARCHAR(200),
    PROOF_SQL    VARCHAR(4000),
    NOTES        VARCHAR(2000)
);

MERGE INTO OVERWATCH.CORE.SCHEMA_VERSION t
USING (SELECT 5 AS VERSION, 'actions: owner-routed action queue + verified savings ledger' AS DESCRIPTION) s
ON t.VERSION = s.VERSION
WHEN NOT MATCHED THEN INSERT (VERSION, DESCRIPTION) VALUES (s.VERSION, s.DESCRIPTION);

SELECT 'V005 applied' AS STATUS;
