-- V006__pipeline_sla.sql — metadata-driven pipeline freshness SLAs.
-- Ported from the original OVERWATCH pipeline SLA contract. Idempotent.
--
-- DBAs register critical tables + a max age; the status view scores them
-- against ACCOUNT_USAGE.TABLES.LAST_ALTERED (metadata lag up to ~2h — the
-- app labels it). No Streamlit code changes needed to add/remove tables.

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG (
    DATABASE_NAME VARCHAR(200) NOT NULL,
    SCHEMA_NAME   VARCHAR(200) NOT NULL,
    TABLE_NAME    VARCHAR(200) NOT NULL,
    MAX_AGE_HOURS NUMBER(6,1)  NOT NULL DEFAULT 24,
    OWNER         VARCHAR(200) NOT NULL DEFAULT 'Data Engineering',
    ENABLED       BOOLEAN      NOT NULL DEFAULT TRUE,
    UPDATED_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY    VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

-- Example rows (add real ones via the Operations > Pipeline SLA tab):
-- INSERT INTO DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG
--     (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, MAX_AGE_HOURS, OWNER)
-- VALUES ('ALFA_EDW_PROD', 'DW', 'FACT_POLICY', 6, 'ALFA EDW Team');

CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_STATUS AS
SELECT
    C.DATABASE_NAME,
    C.SCHEMA_NAME,
    C.TABLE_NAME,
    C.OWNER,
    C.MAX_AGE_HOURS,
    T.LAST_ALTERED,
    ROUND(DATEDIFF('minute', T.LAST_ALTERED, CURRENT_TIMESTAMP()) / 60.0, 1) AS HOURS_SINCE,
    IFF(T.LAST_ALTERED IS NOT NULL
        AND DATEDIFF('minute', T.LAST_ALTERED, CURRENT_TIMESTAMP()) / 60.0 <= C.MAX_AGE_HOURS,
        TRUE, FALSE) AS SLA_MET
FROM DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG C
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLES T
       ON T.TABLE_CATALOG = C.DATABASE_NAME
      AND T.TABLE_SCHEMA = C.SCHEMA_NAME
      AND T.TABLE_NAME = C.TABLE_NAME
      AND T.DELETED IS NULL
WHERE C.ENABLED;

GRANT SELECT ON TABLE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON VIEW DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_STATUS TO ROLE OVERWATCH_MONITOR;
GRANT INSERT, UPDATE, DELETE ON TABLE DBA_MAINT_DB.OVERWATCH.PIPELINE_SLA_CONFIG TO ROLE OVERWATCH_OPERATOR;

MERGE INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION t
USING (SELECT 6 AS VERSION, 'pipeline sla: config table + freshness status view' AS DESCRIPTION) s
ON t.VERSION = s.VERSION
WHEN NOT MATCHED THEN INSERT (VERSION, DESCRIPTION) VALUES (s.VERSION, s.DESCRIPTION);

SELECT 'V006 applied' AS STATUS;
