-- V032__incident_object.sql — the incident object (docs/design/V029_INCIDENT_OBJECT.md).
--
-- Operators work INCIDENTS; the app stored fragments. Two small PERMANENT
-- operator-curated tables roll alerts, task failures, warehouse changes,
-- DDL, deploys and remediations into one lifecycle object. Owner decisions
-- 2026-07-10: auto-declare CRITICALs ON (one incident per dedupe family per
-- 24h, SETTINGS toggle), reopen window 14 days, declare/close DBA-only.
--
-- Lineage (Codex r6 #6): REMEDIATION_LOG gains EVENT_ID/INCIDENT_ID and
-- SAVINGS_LEDGER gains REMEDIATION_ID — additive, never retroactive.
--
-- Births: manual declare (Control Room), auto-declare for CRITICALs
-- (SP_INCIDENT_AUTODECLARE, chained after TASK_LOAD_HOURLY), and the
-- INCIDENT_PROPOSALS view — suggestions only, a human confirms; nothing
-- is grouped silently.
--
-- The design doc's IS_RERUN scan rider closes as ALREADY-SAFE: rerun rows
-- persist RENDER_MS NULL (V027) and the OPS_SLOW_RENDER arm has filtered
-- RENDER_MS IS NOT NULL since V017 — reruns cannot pollute the sentinel.
--
-- Idempotent. Apply IN ORDER after V031. Re-run roles.sql (operator DML
-- grants on the two new tables).

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

EXECUTE IMMEDIATE $$
DECLARE
    v INT;
    not_ready EXCEPTION (-20032, 'BLOCKED: SCHEMA_VERSION < 31 - run migrations in order (see DEPLOYMENT.md)');
BEGIN
    SELECT COALESCE(MAX(VERSION), 0) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 31) THEN
        RAISE not_ready;
    END IF;
    RETURN 'ok';
END;
$$;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENTS (
    INCIDENT_ID     VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    TITLE           VARCHAR(300)  NOT NULL,
    SEVERITY        VARCHAR(10)   NOT NULL,
    STATUS          VARCHAR(12)   NOT NULL DEFAULT 'OPEN',
    COMPANY         VARCHAR(40)   NOT NULL DEFAULT 'ALL',
    DETECTED_AT     TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    STARTED_AT      TIMESTAMP_NTZ,
    ACK_AT          TIMESTAMP_NTZ,
    MITIGATED_AT    TIMESTAMP_NTZ,
    RESOLVED_AT     TIMESTAMP_NTZ,
    ROOT_CAUSE_KIND VARCHAR(30),
    ROOT_CAUSE_NOTE VARCHAR(2000),
    OWNER           VARCHAR(200),
    REOPENED_FROM   VARCHAR(80),
    DECLARED_BY     VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER(),
    UPDATED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS (
    INCIDENT_ID  VARCHAR(80)   NOT NULL,
    MEMBER_KIND  VARCHAR(20)   NOT NULL,
    REF_ID       VARCHAR(300)  NOT NULL,
    EVIDENCE_TS  TIMESTAMP_NTZ,
    AUTO_LINKED  BOOLEAN       NOT NULL DEFAULT FALSE,
    LINKED_BY    VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER(),
    LINKED_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- Lineage: joins, not notes text. Additive; historical rows stay NULL.
ALTER TABLE DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG ADD COLUMN IF NOT EXISTS EVENT_ID VARCHAR(80);
ALTER TABLE DBA_MAINT_DB.OVERWATCH.REMEDIATION_LOG ADD COLUMN IF NOT EXISTS INCIDENT_ID VARCHAR(80);
ALTER TABLE DBA_MAINT_DB.OVERWATCH.SAVINGS_LEDGER  ADD COLUMN IF NOT EXISTS REMEDIATION_ID VARCHAR(80);

-- Owner-decided defaults (Admin-editable data, not code).
MERGE INTO DBA_MAINT_DB.OVERWATCH.SETTINGS t
USING (SELECT 'INCIDENT_AUTO_DECLARE_CRITICAL' AS KEY, 'TRUE' AS VALUE) s
ON t.KEY = s.KEY
WHEN NOT MATCHED THEN INSERT (KEY, VALUE) VALUES (s.KEY, s.VALUE);

MERGE INTO DBA_MAINT_DB.OVERWATCH.SETTINGS t
USING (SELECT 'INCIDENT_REOPEN_DAYS' AS KEY, '14' AS VALUE) s
ON t.KEY = s.KEY
WHEN NOT MATCHED THEN INSERT (KEY, VALUE) VALUES (s.KEY, s.VALUE);

-- Proposals: suggestions ONLY — open alert families (48h) not yet members,
-- with nearby warehouse changes counted. A human confirms in the app.
CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.INCIDENT_PROPOSALS AS
WITH open_alerts AS (
    SELECT e.EVENT_ID, e.RULE_ID, e.COMPANY, e.SEVERITY, e.TITLE, e.RAISED_AT,
           SPLIT_PART(COALESCE(e.DEDUPE_KEY, e.EVENT_ID), '|', 1) AS FAMILY
    FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e
    WHERE e.STATUS IN ('OPEN', 'ACK')
      AND e.RAISED_AT >= DATEADD('day', -2, CURRENT_TIMESTAMP())
      AND NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS m
                      WHERE m.MEMBER_KIND = 'ALERT' AND m.REF_ID = e.EVENT_ID)
)
SELECT FAMILY || '|' || COMPANY AS PROPOSAL_KEY,
       MAX_BY(TITLE, RAISED_AT) AS SUGGESTED_TITLE,
       DECODE(MAX(CASE UPPER(SEVERITY) WHEN 'CRITICAL' THEN 3 WHEN 'HIGH' THEN 2 ELSE 1 END),
              3, 'CRITICAL', 2, 'HIGH', 'MEDIUM') AS SEVERITY,
       COMPANY,
       MIN(RAISED_AT) AS FIRST_TS,
       MAX(RAISED_AT) AS LAST_TS,
       COUNT(*) AS ALERTS,
       (SELECT COUNT(*) FROM DBA_MAINT_DB.OVERWATCH.WAREHOUSE_CHANGE_REGISTRY w
         WHERE w.CHANGE_SEEN_AT BETWEEN DATEADD('minute', -30, MIN(RAISED_AT))
                                    AND DATEADD('minute',  30, MAX(RAISED_AT))) AS NEARBY_WH_CHANGES
FROM open_alerts
GROUP BY FAMILY, COMPANY;

-- Auto-declare CRITICALs: one incident per dedupe family per 24h; members
-- attach AUTO_LINKED; a family already represented in an open incident
-- never doubles. SETTINGS toggle read at runtime.
CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_INCIDENT_AUTODECLARE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    enabled VARCHAR;
    made INT DEFAULT 0;
BEGIN
    SELECT COALESCE(MAX(VALUE), 'TRUE') INTO :enabled
    FROM DBA_MAINT_DB.OVERWATCH.SETTINGS WHERE KEY = 'INCIDENT_AUTO_DECLARE_CRITICAL';
    IF (UPPER(:enabled) <> 'TRUE') THEN
        RETURN 'auto-declare off';
    END IF;

    CREATE OR REPLACE TEMPORARY TABLE _OW_AUTODECL AS
    WITH crit AS (
        SELECT e.EVENT_ID, e.COMPANY, e.SEVERITY, e.TITLE, e.RAISED_AT,
               SPLIT_PART(COALESCE(e.DEDUPE_KEY, e.EVENT_ID), '|', 1) AS FAMILY
        FROM DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e
        WHERE UPPER(e.SEVERITY) = 'CRITICAL'
          AND e.STATUS IN ('OPEN', 'ACK')
          AND e.RAISED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
          AND NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS m
                          WHERE m.MEMBER_KIND = 'ALERT' AND m.REF_ID = e.EVENT_ID)
    )
    SELECT UUID_STRING() AS INCIDENT_ID, FAMILY, COMPANY,
           MAX_BY(TITLE, RAISED_AT) AS TITLE,
           MIN(RAISED_AT) AS FIRST_TS
    FROM crit c
    WHERE NOT EXISTS (
        SELECT 1
        FROM DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS m
        JOIN DBA_MAINT_DB.OVERWATCH.INCIDENTS i ON i.INCIDENT_ID = m.INCIDENT_ID
        JOIN DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS a ON a.EVENT_ID = m.REF_ID
        WHERE m.MEMBER_KIND = 'ALERT'
          AND i.STATUS IN ('OPEN', 'MITIGATED')
          AND SPLIT_PART(COALESCE(a.DEDUPE_KEY, a.EVENT_ID), '|', 1) = c.FAMILY
    )
    GROUP BY FAMILY, COMPANY;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.INCIDENTS
        (INCIDENT_ID, TITLE, SEVERITY, STATUS, COMPANY, DETECTED_AT, STARTED_AT,
         ROOT_CAUSE_KIND, DECLARED_BY)
    SELECT INCIDENT_ID, LEFT('Auto: ' || TITLE, 300), 'CRITICAL', 'OPEN', COMPANY,
           CURRENT_TIMESTAMP(), FIRST_TS, 'UNKNOWN', 'SP_INCIDENT_AUTODECLARE'
    FROM _OW_AUTODECL;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.INCIDENT_MEMBERS
        (INCIDENT_ID, MEMBER_KIND, REF_ID, EVIDENCE_TS, AUTO_LINKED, LINKED_BY)
    SELECT d.INCIDENT_ID, 'ALERT', e.EVENT_ID, e.RAISED_AT, TRUE, 'SP_INCIDENT_AUTODECLARE'
    FROM _OW_AUTODECL d
    JOIN DBA_MAINT_DB.OVERWATCH.ALERT_EVENTS e
      ON e.COMPANY = d.COMPANY
     AND UPPER(e.SEVERITY) = 'CRITICAL'
     AND e.STATUS IN ('OPEN', 'ACK')
     AND e.RAISED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
     AND SPLIT_PART(COALESCE(e.DEDUPE_KEY, e.EVENT_ID), '|', 1) = d.FAMILY;

    SELECT COUNT(*) INTO :made FROM _OW_AUTODECL;
    RETURN 'auto-declared ' || :made || ' incident(s)';
END;
$$;

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY SUSPEND;

CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_INCIDENT_AUTODECLARE
    WAREHOUSE = WH_ALFA_OVERWATCH
    AFTER DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_INCIDENT_AUTODECLARE();

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_INCIDENT_AUTODECLARE RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_HOURLY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_REFRESH_EXEC_BOARD RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY RESUME;

MERGE INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION t
USING (SELECT 32 AS VERSION,
       'incident object: INCIDENTS/INCIDENT_MEMBERS + lineage + proposals + auto-declare' AS DESCRIPTION) s
ON t.VERSION = s.VERSION
WHEN NOT MATCHED THEN INSERT (VERSION, DESCRIPTION) VALUES (s.VERSION, s.DESCRIPTION);
