-- V035: MART_LOCK_WAIT_DAILY — move the LOCK_WAIT_HISTORY scans off page views.
-- Live finding 2026-07-10 (Joe's Heaviest-queries panel): the lock-contention
-- reads scan 46-56 GB and run 74-259s EACH — LOCK_WAIT_HISTORY is enormous in
-- this account. A page view must never pay that. The daily task pays it once,
-- on a 3-day increment (small partitions); the panel reads the mart.
-- Company derives from the object's database (COMPANY_FOR_DATABASE), applied
-- OUTSIDE the aggregation per the V030 shape law.
-- Apply AFTER V034. Idempotent (MERGE); safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 34) THEN
        RAISE EXCEPTION (-20035, 'V035 requires V034 first — apply migrations in order.');
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY (
    DAY DATE NOT NULL,
    DATABASE_NAME VARCHAR(200) NOT NULL,
    SCHEMA_NAME VARCHAR(200) NOT NULL,
    OBJECT_NAME VARCHAR(400) NOT NULL,
    LOCK_TYPE VARCHAR(50) NOT NULL,
    COMPANY VARCHAR(50),
    WAIT_EVENTS NUMBER(12,0),
    ACQUIRED_WAIT_SEC NUMBER(18,0),
    NEVER_ACQUIRED NUMBER(12,0),
    LAST_SEEN TIMESTAMP_NTZ,
    LOAD_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_LOCK_WAIT_MART(DAYS_BACK FLOAT)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
-- Failures surface in TASK_HISTORY and the task retries next day — no
-- swallow, no partial state (MERGE is idempotent on the day grain).
BEGIN
    MERGE INTO DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY t
    USING (
        SELECT g.DAY, g.DATABASE_NAME, g.SCHEMA_NAME, g.OBJECT_NAME, g.LOCK_TYPE,
               DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(g.DATABASE_NAME) AS COMPANY,
               g.WAIT_EVENTS, g.ACQUIRED_WAIT_SEC, g.NEVER_ACQUIRED, g.LAST_SEEN
        FROM (
            SELECT CAST(REQUESTED_AT AS DATE) AS DAY,
                   COALESCE(DATABASE_NAME, 'NONE') AS DATABASE_NAME,
                   COALESCE(SCHEMA_NAME, 'NONE') AS SCHEMA_NAME,
                   COALESCE(OBJECT_NAME, 'NONE') AS OBJECT_NAME,
                   COALESCE(LOCK_TYPE, 'NONE') AS LOCK_TYPE,
                   COUNT(*) AS WAIT_EVENTS,
                   SUM(IFF(ACQUIRED_AT IS NOT NULL,
                           DATEDIFF('second', REQUESTED_AT, ACQUIRED_AT), 0)) AS ACQUIRED_WAIT_SEC,
                   COUNT_IF(ACQUIRED_AT IS NULL) AS NEVER_ACQUIRED,
                   MAX(REQUESTED_AT) AS LAST_SEEN
            FROM SNOWFLAKE.ACCOUNT_USAGE.LOCK_WAIT_HISTORY
            WHERE REQUESTED_AT >= DATEADD('day', -1 * :DAYS_BACK, CURRENT_DATE())
            GROUP BY 1, 2, 3, 4, 5
        ) g
    ) s
    ON t.DAY = s.DAY AND t.DATABASE_NAME = s.DATABASE_NAME
       AND t.SCHEMA_NAME = s.SCHEMA_NAME AND t.OBJECT_NAME = s.OBJECT_NAME
       AND t.LOCK_TYPE = s.LOCK_TYPE
    WHEN MATCHED THEN UPDATE SET
        t.COMPANY = s.COMPANY, t.WAIT_EVENTS = s.WAIT_EVENTS,
        t.ACQUIRED_WAIT_SEC = s.ACQUIRED_WAIT_SEC, t.NEVER_ACQUIRED = s.NEVER_ACQUIRED,
        t.LAST_SEEN = s.LAST_SEEN, t.LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (DAY, DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME, LOCK_TYPE, COMPANY,
         WAIT_EVENTS, ACQUIRED_WAIT_SEC, NEVER_ACQUIRED, LAST_SEEN)
    VALUES (s.DAY, s.DATABASE_NAME, s.SCHEMA_NAME, s.OBJECT_NAME, s.LOCK_TYPE, s.COMPANY,
            s.WAIT_EVENTS, s.ACQUIRED_WAIT_SEC, s.NEVER_ACQUIRED, s.LAST_SEEN);
    RETURN 'OK';
END;
$$;

-- One-time backfill (45d, the panel's widest window), then 3d daily increments.
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_LOCK_WAIT_MART(45);

CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.MART_SOURCE_FRESHNESS AS
SELECT 'FACT_QUERY_HOURLY' AS SOURCE_NAME, MAX(LOAD_TS) AS LAST_LOAD_TS, COUNT(*) AS ROW_COUNT,
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0 AS HOURS_SINCE_LOAD
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_WAREHOUSE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY
UNION ALL
SELECT 'FACT_METERING_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY
UNION ALL
SELECT 'FACT_TASK_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY
UNION ALL
SELECT 'FACT_LOGIN_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY
UNION ALL
SELECT 'FACT_STORAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY
UNION ALL
SELECT 'MART_EXEC_BOARD', MAX(REFRESHED_AT), COUNT(*),
       DATEDIFF('minute', MAX(REFRESHED_AT), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD
UNION ALL
SELECT 'MART_WAREHOUSE_EFFICIENCY_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_WAREHOUSE_EFFICIENCY_DAILY
UNION ALL
SELECT 'MART_QUERY_FAMILY_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_QUERY_FAMILY_DAILY
UNION ALL
SELECT 'FACT_QUERY_ROLE_HOURLY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_ROLE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_SCHEMA_HOURLY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_SCHEMA_HOURLY
UNION ALL
SELECT 'MART_COST_ALLOCATION_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_COST_ALLOCATION_DAILY
UNION ALL
SELECT 'MART_TASK_GRAPH_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_TASK_GRAPH_DAILY
UNION ALL
SELECT 'MART_SECURITY_POSTURE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_SECURITY_POSTURE_DAILY
UNION ALL
SELECT 'MART_INCIDENT_TIMELINE', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_INCIDENT_TIMELINE
UNION ALL
SELECT 'FACT_AI_USAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY
UNION ALL
SELECT 'MART_TAG_COVERAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_TAG_COVERAGE_DAILY
UNION ALL
SELECT 'MART_LOCK_WAIT_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY;

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY SUSPEND;

CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY
    WAREHOUSE = WH_ALFA_OVERWATCH
    AFTER DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_LOCK_WAIT_MART(3);

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY RESUME;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 35 AS VERSION, 'MART_LOCK_WAIT_DAILY + SP_LOAD_LOCK_WAIT_MART + TASK_LOCK_WAIT_DAILY (page views never scan LOCK_WAIT_HISTORY again)' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 35);
