-- V036: MART_PATTERN_COST_DAILY - measured $ per repeated statement pattern.
-- Owner ask (2026-07-11, after seeing the Trexis POC): "a visual of bad code
-- and how it could cost us silently." Theirs estimates; ours joins
-- QUERY_ATTRIBUTION_HISTORY (measured compute credits) to the parameterized
-- hash, so a cheap query run thousands of times shows its REAL bill.
-- Company via COMPANY_FOR_WAREHOUSE outside the aggregation (V030 shape law).
-- Apply AFTER V035. Idempotent (MERGE); safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20036, 'V036 requires V035 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 35) THEN
        RAISE not_ready;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY (
    DAY DATE NOT NULL,
    QUERY_HASH VARCHAR(64) NOT NULL,
    COMPANY VARCHAR(50) NOT NULL,
    RUNS NUMBER(12,0),
    CREDITS_ATTRIBUTED NUMBER(18,6),
    USERS NUMBER(12,0),
    LOAD_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(DAYS_BACK FLOAT)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY t
    USING (
        SELECT m.DAY, m.QUERY_HASH, m.COMPANY,
               SUM(m.RUNS) AS RUNS,
               SUM(m.CREDITS_ATTRIBUTED) AS CREDITS_ATTRIBUTED,
               SUM(m.USERS) AS USERS
        FROM (
            SELECT g.DAY, g.QUERY_HASH,
                   DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(g.WAREHOUSE_NAME) AS COMPANY,
                   g.RUNS, g.CREDITS_ATTRIBUTED, g.USERS
            FROM (
                SELECT CAST(q.START_TIME AS DATE) AS DAY,
                       q.QUERY_PARAMETERIZED_HASH AS QUERY_HASH,
                       COALESCE(q.WAREHOUSE_NAME, 'NONE') AS WAREHOUSE_NAME,
                       COUNT(*) AS RUNS,
                       SUM(a.CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_ATTRIBUTED,
                       COUNT(DISTINCT q.USER_NAME) AS USERS
                FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY a
                JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q
                  ON q.QUERY_ID = a.QUERY_ID
                 AND q.START_TIME >= DATEADD('day', -1 * :DAYS_BACK, CURRENT_DATE())
                WHERE a.START_TIME >= DATEADD('day', -1 * :DAYS_BACK, CURRENT_DATE())
                  AND q.QUERY_PARAMETERIZED_HASH IS NOT NULL
                GROUP BY 1, 2, 3
            ) g
        ) m
        GROUP BY 1, 2, 3
    ) s
    ON t.DAY = s.DAY AND t.QUERY_HASH = s.QUERY_HASH AND t.COMPANY = s.COMPANY
    WHEN MATCHED THEN UPDATE SET
        t.RUNS = s.RUNS, t.CREDITS_ATTRIBUTED = s.CREDITS_ATTRIBUTED,
        t.USERS = s.USERS, t.LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (DAY, QUERY_HASH, COMPANY, RUNS, CREDITS_ATTRIBUTED, USERS)
    VALUES (s.DAY, s.QUERY_HASH, s.COMPANY, s.RUNS, s.CREDITS_ATTRIBUTED, s.USERS);
    RETURN 'OK';
END;
$$;

-- One-time backfill (30d; attribution lags ~6h), then 3d daily increments.
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(30);

CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.MART_SOURCE_FRESHNESS AS
SELECT 'FACT_QUERY_HOURLY' AS SOURCE_NAME, MAX(LOAD_TS) AS LAST_LOAD_TS, COUNT(*) AS ROW_COUNT,
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0 AS HOURS_SINCE_LOAD
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_WAREHOUSE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY
UNION ALL
SELECT 'FACT_METERING_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_METERING_DAILY
UNION ALL
SELECT 'FACT_TASK_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_TASK_DAILY
UNION ALL
SELECT 'FACT_LOGIN_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_LOGIN_DAILY
UNION ALL
SELECT 'FACT_STORAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_STORAGE_DAILY
UNION ALL
SELECT 'MART_EXEC_BOARD', MAX(REFRESHED_AT), COUNT(*),
       DATEDIFF('minute', MAX(REFRESHED_AT), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_EXEC_BOARD
UNION ALL
SELECT 'MART_WAREHOUSE_EFFICIENCY_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_WAREHOUSE_EFFICIENCY_DAILY
UNION ALL
SELECT 'MART_QUERY_FAMILY_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_QUERY_FAMILY_DAILY
UNION ALL
SELECT 'FACT_QUERY_ROLE_HOURLY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_ROLE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_SCHEMA_HOURLY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_SCHEMA_HOURLY
UNION ALL
SELECT 'MART_COST_ALLOCATION_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_COST_ALLOCATION_DAILY
UNION ALL
SELECT 'MART_TASK_GRAPH_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_TASK_GRAPH_DAILY
UNION ALL
SELECT 'MART_SECURITY_POSTURE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_SECURITY_POSTURE_DAILY
UNION ALL
SELECT 'MART_INCIDENT_TIMELINE', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_INCIDENT_TIMELINE
UNION ALL
SELECT 'FACT_AI_USAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.FACT_AI_USAGE_DAILY
UNION ALL
SELECT 'MART_TAG_COVERAGE_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_TAG_COVERAGE_DAILY
UNION ALL
SELECT 'MART_LOCK_WAIT_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_LOCK_WAIT_DAILY
UNION ALL
SELECT 'MART_PATTERN_COST_DAILY', MAX(LOAD_TS), COUNT(*),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP()) / 60.0
FROM DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY;

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY SUSPEND;

CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PATTERN_COST_DAILY
    WAREHOUSE = WH_ALFA_OVERWATCH
    AFTER DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(3);

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PATTERN_COST_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY RESUME;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 36 AS VERSION, 'MART_PATTERN_COST_DAILY + SP_LOAD_PATTERN_COST + TASK_PATTERN_COST_DAILY (measured $ per repeated statement pattern)' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 36);
