-- V037: DATABASE_NAME joins MART_PATTERN_COST_DAILY grain (Compare env lens
-- groundwork, owner decision 2026-07-11: "V037 YES - build FIRST while the
-- mart is days old") + the USERS metric becomes honest (Codex r11 #9): V036
-- stored per-warehouse daily distinct users summed, and readers took the max
-- day - neither is window-distinct. The mart now stores a mergeable HLL
-- state (USERS_HLL); readers combine states and estimate, so USERS is a true
-- approximate distinct over any day range at any grain rollup.
-- Company via COMPANY_FOR_WAREHOUSE outside the aggregation (V030 shape law).
-- The mart is days old: CREATE OR REPLACE + a fresh 30d backfill is cheaper
-- than any in-place migration. Apply AFTER V036. Idempotent; safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20037, 'V037 requires V036 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 36) THEN
        RAISE not_ready;
    END IF;
END;
$$;

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY SUSPEND;

CREATE OR REPLACE TABLE DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY (
    DAY DATE NOT NULL,
    QUERY_HASH VARCHAR(64) NOT NULL,
    COMPANY VARCHAR(50) NOT NULL,
    DATABASE_NAME VARCHAR(255) NOT NULL,
    RUNS NUMBER(12,0),
    CREDITS_ATTRIBUTED NUMBER(18,6),
    USERS_HLL BINARY,
    LOAD_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(DAYS_BACK FLOAT)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO DBA_MAINT_DB.OVERWATCH.MART_PATTERN_COST_DAILY t
    USING (
        SELECT m.DAY, m.QUERY_HASH, m.COMPANY, m.DATABASE_NAME,
               SUM(m.RUNS) AS RUNS,
               SUM(m.CREDITS_ATTRIBUTED) AS CREDITS_ATTRIBUTED,
               HLL_COMBINE(m.USERS_HLL) AS USERS_HLL
        FROM (
            SELECT g.DAY, g.QUERY_HASH, g.DATABASE_NAME,
                   DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(g.WAREHOUSE_NAME) AS COMPANY,
                   g.RUNS, g.CREDITS_ATTRIBUTED, g.USERS_HLL
            FROM (
                SELECT CAST(q.START_TIME AS DATE) AS DAY,
                       q.QUERY_PARAMETERIZED_HASH AS QUERY_HASH,
                       COALESCE(q.WAREHOUSE_NAME, 'NONE') AS WAREHOUSE_NAME,
                       COALESCE(q.DATABASE_NAME, 'NONE') AS DATABASE_NAME,
                       COUNT(*) AS RUNS,
                       SUM(a.CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_ATTRIBUTED,
                       HLL_ACCUMULATE(q.USER_NAME) AS USERS_HLL
                FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY a
                JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q
                  ON q.QUERY_ID = a.QUERY_ID
                 AND q.START_TIME >= DATEADD('day', -1 * :DAYS_BACK, CURRENT_DATE())
                WHERE a.START_TIME >= DATEADD('day', -1 * :DAYS_BACK, CURRENT_DATE())
                  AND q.QUERY_PARAMETERIZED_HASH IS NOT NULL
                GROUP BY 1, 2, 3, 4
            ) g
        ) m
        GROUP BY 1, 2, 3, 4
    ) s
    ON t.DAY = s.DAY AND t.QUERY_HASH = s.QUERY_HASH AND t.COMPANY = s.COMPANY
       AND t.DATABASE_NAME = s.DATABASE_NAME
    WHEN MATCHED THEN UPDATE SET
        t.RUNS = s.RUNS, t.CREDITS_ATTRIBUTED = s.CREDITS_ATTRIBUTED,
        t.USERS_HLL = s.USERS_HLL, t.LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (DAY, QUERY_HASH, COMPANY, DATABASE_NAME, RUNS, CREDITS_ATTRIBUTED, USERS_HLL)
    VALUES (s.DAY, s.QUERY_HASH, s.COMPANY, s.DATABASE_NAME, s.RUNS, s.CREDITS_ATTRIBUTED, s.USERS_HLL);
    RETURN 'OK';
END;
$$;

-- Rebuild: the table was recreated empty, so the 30d backfill IS the data.
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_PATTERN_COST(30);

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_PATTERN_COST_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOCK_WAIT_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_DAILY RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_DAILY RESUME;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 37 AS VERSION, 'MART_PATTERN_COST_DAILY v2: DATABASE_NAME grain (Compare env lens) + mergeable HLL user state (honest window-distinct USERS)' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 37);
