-- V039: the CLOUD_SERVICES_ONLY pseudo-warehouse stops being a warehouse.
-- COST_DB reconciliation R1 (docs/design/COSTDB_RECONCILIATION.md): accounts
-- emit a WAREHOUSE_METERING_HISTORY row with WAREHOUSE_ID = 0 for cloud
-- services consumed outside any warehouse. Our fact loader ingested it, so
-- it appeared as a phantom ALFA warehouse: 100% idle in the advisor (nothing
-- to suspend), a row in movers/chargeback-unmapped/Compare, and a slice of
-- the boss chart. The docs-sanctioned filter is WAREHOUSE_ID > 0 (COST_DB
-- carries the same filter with the comment "skip pseudo-VWs").
-- SP_LOAD_HOURLY_FACTS below is derived VERBATIM from V002 with exactly one
-- added predicate (equality-locked in tests). The V27-family mart loader is
-- NOT re-derived here (it is equality-locked to its V028 pair); eff-mart
-- READERS filter by name instead, and the source-side filter joins the next
-- planned V27 re-derivation. Apply AFTER V038. Idempotent; safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20039, 'V039 requires V038 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 38) THEN
        RAISE not_ready;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_HOURLY_FACTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY
     WHERE HOUR_TS >= DATEADD('hour', -48, CURRENT_TIMESTAMP());

    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_QUERY_HOURLY
        (HOUR_TS, WAREHOUSE_NAME, DATABASE_NAME, USER_NAME, COMPANY, QUERY_COUNT,
         FAILED_COUNT, ELAPSED_SEC_SUM, P95_ELAPSED_SEC, QUEUED_SEC_SUM, SPILL_REMOTE_GB)
    SELECT
        DATE_TRUNC('hour', START_TIME),
        WAREHOUSE_NAME,
        DATABASE_NAME,
        USER_NAME,
        DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(WAREHOUSE_NAME),
        COUNT(*),
        SUM(IFF(EXECUTION_STATUS = 'FAIL', 1, 0)),
        SUM(COALESCE(TOTAL_ELAPSED_TIME, 0)) / 1000,
        APPROX_PERCENTILE(TOTAL_ELAPSED_TIME / 1000, 0.95),
        SUM(COALESCE(QUEUED_OVERLOAD_TIME, 0) + COALESCE(QUEUED_PROVISIONING_TIME, 0)) / 1000,
        SUM(COALESCE(BYTES_SPILLED_TO_REMOTE_STORAGE, 0)) / POWER(1024, 3)
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('hour', -48, CURRENT_TIMESTAMP())
    GROUP BY 1, 2, 3, 4, 5;

    MERGE INTO DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY t
    USING (
        SELECT
            DATE(START_TIME) AS DAY,
            WAREHOUSE_NAME,
            DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(WAREHOUSE_NAME) AS COMPANY,
            SUM(COALESCE(CREDITS_USED_COMPUTE, CREDITS_USED)) AS CREDITS_COMPUTE,
            SUM(COALESCE(CREDITS_USED, 0)) AS CREDITS_TOTAL
        FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD('day', -3, CURRENT_DATE())
          AND WAREHOUSE_ID > 0
        GROUP BY 1, 2, 3
    ) s
    ON t.DAY = s.DAY AND t.WAREHOUSE_NAME = s.WAREHOUSE_NAME
    WHEN MATCHED THEN UPDATE SET
        COMPANY = s.COMPANY, CREDITS_COMPUTE = s.CREDITS_COMPUTE,
        CREDITS_TOTAL = s.CREDITS_TOTAL, LOAD_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (DAY, WAREHOUSE_NAME, COMPANY, CREDITS_COMPUTE, CREDITS_TOTAL)
        VALUES (s.DAY, s.WAREHOUSE_NAME, s.COMPANY, s.CREDITS_COMPUTE, s.CREDITS_TOTAL);

    RETURN 'hourly facts loaded';
END;
$$;

DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_WAREHOUSE_DAILY
 WHERE UPPER(WAREHOUSE_NAME) = 'CLOUD_SERVICES_ONLY';

DELETE FROM DBA_MAINT_DB.OVERWATCH.MART_WAREHOUSE_EFFICIENCY_DAILY
 WHERE UPPER(WAREHOUSE_NAME) = 'CLOUD_SERVICES_ONLY';

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 39 AS VERSION, 'pseudo-warehouse filter: CLOUD_SERVICES_ONLY (WAREHOUSE_ID = 0) excluded from the warehouse fact + phantom rows deleted (COST_DB recon R1)' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 39);
