-- V040: freshness becomes a lookup, not a computation (Codex r13 #2 + #3).
-- The health strip and freshness boards read MART_SOURCE_FRESHNESS - a view
-- of 19 MAX(LOAD_TS) + COUNT(*) table aggregates - every 30 seconds per
-- viewer. This migration snapshots that view into a one-row-per-source
-- STATE table every 10 minutes server-side; the app reads the tiny table
-- and computes staleness from LAST_LOAD_TS at render. The view stays as
-- the writer's source and the app's pre-V040 fallback.
-- Apply AFTER V039. Idempotent; safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20040, 'V040 requires V039 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 39) THEN
        RAISE not_ready;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SOURCE_FRESHNESS_STATE (
    SOURCE_NAME  VARCHAR(100) NOT NULL PRIMARY KEY,
    LAST_LOAD_TS TIMESTAMP_NTZ,
    ROW_COUNT    NUMBER(18,0),
    SNAPSHOT_TS  TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_SNAPSHOT_FRESHNESS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO DBA_MAINT_DB.OVERWATCH.SOURCE_FRESHNESS_STATE t
    USING (
        SELECT SOURCE_NAME, LAST_LOAD_TS, ROW_COUNT
        FROM DBA_MAINT_DB.OVERWATCH.MART_SOURCE_FRESHNESS
    ) s
    ON t.SOURCE_NAME = s.SOURCE_NAME
    WHEN MATCHED THEN UPDATE SET
        t.LAST_LOAD_TS = s.LAST_LOAD_TS, t.ROW_COUNT = s.ROW_COUNT,
        t.SNAPSHOT_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (SOURCE_NAME, LAST_LOAD_TS, ROW_COUNT)
    VALUES (s.SOURCE_NAME, s.LAST_LOAD_TS, s.ROW_COUNT);
    RETURN 'OK';
END;
$$;

CALL DBA_MAINT_DB.OVERWATCH.SP_SNAPSHOT_FRESHNESS();

CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SNAPSHOT_FRESHNESS
    WAREHOUSE = WH_ALFA_OVERWATCH
    SCHEDULE = 'USING CRON */10 * * * * America/Chicago'
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_SNAPSHOT_FRESHNESS();

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_SNAPSHOT_FRESHNESS RESUME;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 40 AS VERSION, 'SOURCE_FRESHNESS_STATE + SP_SNAPSHOT_FRESHNESS + 10-min task: freshness is a lookup, not 19 aggregates per health-strip refresh' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 40);
