-- V048: FACT_OBJECT_COST_DAILY — the additive object-cost ledger (Codex
-- architectural item 10 / Phase 2, 2026-07-14). One row per day / object /
-- cost-arm / company, credits additive across arms:
--   QUERY_COMPUTE           measured compute+QAS from QUERY_ATTRIBUTION_HISTORY,
--                           split EQUALLY across the base objects each query
--                           touched (ACCESS_HISTORY) so totals stay additive
--   QUERY_COMPUTE_RESIDUAL  measured credits for queries with no base object
--   CLUSTERING / MV_REFRESH / SERVERLESS_TASK / SNOWPIPE / SEARCH_OPT
--                           direct per-object serverless credits
-- Verified accessible on this account 2026-07-14 (ACCESS_HISTORY present, so
-- the object split is possible; MV/Search-Opt empty today but wired for later).
-- Apply AFTER V047. Idempotent; safe to re-run.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20048, 'V048 requires V047 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 47) THEN
        RAISE not_ready;
    END IF;
END;
$$;

CREATE TRANSIENT TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (
    DAY           DATE          NOT NULL,
    OBJECT_FQN    VARCHAR(600)  NOT NULL,
    OBJECT_DOMAIN VARCHAR(40),
    COST_ARM      VARCHAR(30)   NOT NULL,
    COMPANY       VARCHAR(40),
    CREDITS       NUMBER(24,6),
    LOAD_TS       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_OBJECT_COST(DAYS_BACK FLOAT)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    lo DATE;
BEGIN
    lo := DATEADD('day', -GREATEST(COALESCE(:DAYS_BACK, 3), 1)::INT, CURRENT_DATE());
    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY WHERE DAY >= :lo;

    -- Direct per-object serverless arms -----------------------------------
    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    SELECT START_TIME::DATE, DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TABLE_NAME,
           'TABLE', 'CLUSTERING',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME), SUM(COALESCE(CREDITS_USED, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY
    WHERE START_TIME >= :lo AND CREDITS_USED > 0
    GROUP BY 1, 2, 3, 4, 5;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    SELECT START_TIME::DATE, DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TABLE_NAME,
           'MATERIALIZED_VIEW', 'MV_REFRESH',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME), SUM(COALESCE(CREDITS_USED, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY
    WHERE START_TIME >= :lo AND CREDITS_USED > 0
    GROUP BY 1, 2, 3, 4, 5;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    SELECT START_TIME::DATE, DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TABLE_NAME,
           'TABLE', 'SEARCH_OPT',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME), SUM(COALESCE(CREDITS_USED, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.SEARCH_OPTIMIZATION_HISTORY
    WHERE START_TIME >= :lo AND CREDITS_USED > 0
    GROUP BY 1, 2, 3, 4, 5;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    SELECT START_TIME::DATE, DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TASK_NAME,
           'TASK', 'SERVERLESS_TASK',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME), SUM(COALESCE(CREDITS_USED, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.SERVERLESS_TASK_HISTORY
    WHERE START_TIME >= :lo AND CREDITS_USED > 0
    GROUP BY 1, 2, 3, 4, 5;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    SELECT START_TIME::DATE, PIPE_NAME, 'PIPE', 'SNOWPIPE',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(SPLIT_PART(PIPE_NAME, '.', 1)), SUM(COALESCE(CREDITS_USED, 0))
    FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
    WHERE START_TIME >= :lo AND CREDITS_USED > 0
    GROUP BY 1, 2, 3, 4, 5;

    -- Measured query compute, split EQUALLY across accessed base objects ---
    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    WITH qa AS (
        SELECT QUERY_ID, MIN(START_TIME)::DATE AS DAY,
               SUM(COALESCE(CREDITS_ATTRIBUTED_COMPUTE, 0) + COALESCE(CREDITS_USED_QUERY_ACCELERATION, 0)) AS CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
        WHERE START_TIME >= :lo
        GROUP BY QUERY_ID
        HAVING SUM(COALESCE(CREDITS_ATTRIBUTED_COMPUTE, 0) + COALESCE(CREDITS_USED_QUERY_ACCELERATION, 0)) > 0
    ),
    dedup AS (
        SELECT DISTINCT ah.QUERY_ID,
               f.value:"objectName"::STRING AS OBJECT_FQN,
               f.value:"objectDomain"::STRING AS OBJECT_DOMAIN
        FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
             LATERAL FLATTEN(input => ah.BASE_OBJECTS_ACCESSED) f
        WHERE ah.QUERY_START_TIME >= :lo
          AND f.value:"objectName" IS NOT NULL
          AND f.value:"objectDomain"::STRING IN ('Table', 'Materialized view')
    ),
    counts AS (SELECT QUERY_ID, COUNT(*) AS N FROM dedup GROUP BY QUERY_ID)
    SELECT qa.DAY, d.OBJECT_FQN, UPPER(REPLACE(d.OBJECT_DOMAIN, ' ', '_')), 'QUERY_COMPUTE',
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(SPLIT_PART(d.OBJECT_FQN, '.', 1)),
           SUM(qa.CREDITS / c.N)
    FROM qa
    JOIN dedup d ON d.QUERY_ID = qa.QUERY_ID
    JOIN counts c ON c.QUERY_ID = qa.QUERY_ID
    GROUP BY 1, 2, 3, 4, 5;

    -- Residual: measured credits for queries that touched no base object ---
    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY (DAY, OBJECT_FQN, OBJECT_DOMAIN, COST_ARM, COMPANY, CREDITS)
    WITH qa AS (
        SELECT QUERY_ID, MIN(START_TIME)::DATE AS DAY,
               SUM(COALESCE(CREDITS_ATTRIBUTED_COMPUTE, 0) + COALESCE(CREDITS_USED_QUERY_ACCELERATION, 0)) AS CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
        WHERE START_TIME >= :lo
        GROUP BY QUERY_ID
        HAVING SUM(COALESCE(CREDITS_ATTRIBUTED_COMPUTE, 0) + COALESCE(CREDITS_USED_QUERY_ACCELERATION, 0)) > 0
    ),
    obj_q AS (
        SELECT DISTINCT ah.QUERY_ID
        FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
             LATERAL FLATTEN(input => ah.BASE_OBJECTS_ACCESSED) f
        WHERE ah.QUERY_START_TIME >= :lo
          AND f.value:"objectDomain"::STRING IN ('Table', 'Materialized view')
    )
    SELECT qa.DAY, 'UNATTRIBUTED', 'RESIDUAL', 'QUERY_COMPUTE_RESIDUAL', NULL, SUM(qa.CREDITS)
    FROM qa
    LEFT JOIN obj_q ON obj_q.QUERY_ID = qa.QUERY_ID
    WHERE obj_q.QUERY_ID IS NULL
    GROUP BY 1;

    MERGE INTO DBA_MAINT_DB.OVERWATCH.SOURCE_FRESHNESS_STATE t
    USING (
        SELECT 'FACT_OBJECT_COST_DAILY' AS SOURCE_NAME, MAX(LOAD_TS) AS LAST_LOAD_TS, COUNT(*) AS ROW_COUNT
        FROM DBA_MAINT_DB.OVERWATCH.FACT_OBJECT_COST_DAILY
    ) s
    ON t.SOURCE_NAME = s.SOURCE_NAME
    WHEN MATCHED THEN UPDATE SET t.LAST_LOAD_TS = s.LAST_LOAD_TS, t.ROW_COUNT = s.ROW_COUNT, t.SNAPSHOT_TS = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (SOURCE_NAME, LAST_LOAD_TS, ROW_COUNT) VALUES (s.SOURCE_NAME, s.LAST_LOAD_TS, s.ROW_COUNT);

    RETURN 'OK';
END;
$$;

-- First fill: 14 days (ACCESS_HISTORY x QUERY_ATTRIBUTION is heavy; the daily task keeps 3d fresh).
CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_OBJECT_COST(14);

CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_OBJECT_COST
    WAREHOUSE = WH_ALFA_OVERWATCH
    SCHEDULE = 'USING CRON 45 6 * * * America/Chicago'
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_OBJECT_COST(3);

ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_OBJECT_COST RESUME;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 48 AS VERSION,
       'FACT_OBJECT_COST_DAILY additive object-cost ledger: measured query compute+QAS split across accessed base objects (ACCESS_HISTORY) + residual, plus direct clustering/MV/serverless-task/snowpipe/search-opt arms; daily task (Codex architectural Phase 2)' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 48);
