-- V074__operating_workbench_foundation.sql
--
-- Persistent operating-workbench records for the closed-loop workflow:
-- signal -> evidence -> owner -> action -> experiment -> verified outcome.
-- Existing ACTION_QUEUE rows remain authoritative. This migration only widens
-- that table and adds operator-owned records around it; no telemetry mart or
-- scheduled task is changed.
--
-- Owner applies in Snowsight after V073. The app never runs this migration.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20074, 'V074 requires V073 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 73) THEN
        RAISE not_ready;
    END IF;
END;
$$;

-- ACTION_QUEUE already owns status, owner and due date. Add only the context
-- needed to route a work item back to its source and explain its disposition.
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS DEFER_UNTIL DATE;
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS COMPLETED_AT TIMESTAMP_NTZ;
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS RESOLUTION_NOTE VARCHAR(4000);
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS SOURCE_ENTITY_TYPE VARCHAR(40);
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS SOURCE_ENTITY_KEY VARCHAR(500);
ALTER TABLE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    ADD COLUMN IF NOT EXISTS CONFIDENCE FLOAT;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY (
    ACTIVITY_ID   VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    ACTION_ID     VARCHAR(80)   NOT NULL,
    ACTIVITY_TYPE VARCHAR(30)   NOT NULL,
    FROM_STATUS   VARCHAR(30),
    TO_STATUS     VARCHAR(30),
    OWNER_NAME    VARCHAR(200),
    DUE_DATE      DATE,
    DEFER_UNTIL   DATE,
    NOTE          VARCHAR(4000),
    REQUEST_KEY   VARCHAR(160),
    CREATED_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY    VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.EVIDENCE_LINKS (
    LINK_ID       VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    FROM_TYPE     VARCHAR(40)   NOT NULL,
    FROM_ID       VARCHAR(500)  NOT NULL,
    TO_TYPE       VARCHAR(40)   NOT NULL,
    TO_ID         VARCHAR(500)  NOT NULL,
    RELATIONSHIP  VARCHAR(80)   NOT NULL,
    LABEL         VARCHAR(500),
    QUERY_ID      VARCHAR(80),
    EVIDENCE_NOTE VARCHAR(4000),
    CREATED_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY    VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.ENTITY_CATALOG (
    ENTITY_TYPE  VARCHAR(40)   NOT NULL,
    ENTITY_KEY   VARCHAR(500)  NOT NULL,
    LABEL        VARCHAR(500),
    COMPANY      VARCHAR(40)   NOT NULL DEFAULT 'ALL',
    TEAM         VARCHAR(200),
    OWNER_NAME   VARCHAR(200),
    STEWARD      VARCHAR(200),
    ON_CALL      VARCHAR(500),
    CRITICALITY  VARCHAR(20)   NOT NULL DEFAULT 'STANDARD',
    DATA_PRODUCT VARCHAR(300),
    SLO_NAME     VARCHAR(300),
    NOTES        VARCHAR(4000),
    UPDATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY   VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER(),
    PRIMARY KEY (ENTITY_TYPE, ENTITY_KEY)
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.USER_WATCHLIST (
    VIEWER_NAME VARCHAR(200)  NOT NULL,
    ENTITY_TYPE VARCHAR(40)   NOT NULL,
    ENTITY_KEY  VARCHAR(500)  NOT NULL,
    LABEL       VARCHAR(500),
    CREATED_AT  TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (VIEWER_NAME, ENTITY_TYPE, ENTITY_KEY)
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.OPTIMIZATION_EXPERIMENTS (
    EXPERIMENT_ID       VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    ACTION_ID           VARCHAR(80),
    ENTITY_TYPE         VARCHAR(40)   NOT NULL,
    ENTITY_KEY          VARCHAR(500)  NOT NULL,
    TITLE               VARCHAR(500)  NOT NULL,
    HYPOTHESIS          VARCHAR(4000) NOT NULL,
    BASELINE_NOTE       VARCHAR(4000),
    TARGET_NOTE         VARCHAR(4000),
    ROLLBACK_CONDITION  VARCHAR(4000),
    OBSERVATION_END     DATE,
    STATUS              VARCHAR(30)   NOT NULL DEFAULT 'PLANNED',
    RESULT_NOTE         VARCHAR(4000),
    VERIFIED_USD        NUMBER(18,2),
    CREATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER(),
    UPDATED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY          VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SLO_OBJECTIVES (
    SLO_ID           VARCHAR(80)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    NAME             VARCHAR(300)  NOT NULL,
    ENTITY_TYPE      VARCHAR(40)   NOT NULL,
    ENTITY_KEY       VARCHAR(500)  NOT NULL,
    METRIC_KEY       VARCHAR(160)  NOT NULL,
    COMPARATOR       VARCHAR(4)    NOT NULL DEFAULT '>=',
    TARGET_VALUE     FLOAT         NOT NULL,
    ERROR_BUDGET_PCT FLOAT         NOT NULL DEFAULT 1,
    WINDOW_DAYS      NUMBER(6,0)   NOT NULL DEFAULT 30,
    OWNER_NAME       VARCHAR(200),
    ACTIVE           BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTES            VARCHAR(4000),
    UPDATED_AT       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY       VARCHAR(200)  NOT NULL DEFAULT CURRENT_USER()
);

-- One call atomically updates the work item and appends its audit/comment row.
-- REQUEST_KEY makes a Streamlit double-submit idempotent.
CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_ACTION_LIFECYCLE(
    P_ACTION_ID VARCHAR,
    P_STATUS VARCHAR,
    P_OWNER VARCHAR,
    P_DUE_DATE DATE,
    P_DEFER_UNTIL DATE,
    P_NOTE VARCHAR,
    P_ACTOR VARCHAR,
    P_REQUEST_KEY VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    seen NUMBER DEFAULT 0;
    matched NUMBER DEFAULT 0;
    old_status VARCHAR;
    next_status VARCHAR;
BEGIN
    IF (P_ACTION_ID IS NULL OR TRIM(P_ACTION_ID) = '') THEN
        RETURN 'INVALID: action id is required';
    END IF;
    IF (P_STATUS IS NOT NULL AND TRIM(P_STATUS) <> ''
        AND UPPER(TRIM(P_STATUS)) NOT IN ('OPEN', 'IN_PROGRESS', 'DONE', 'DROPPED')) THEN
        RETURN 'INVALID: unsupported status';
    END IF;
    IF (P_REQUEST_KEY IS NOT NULL AND TRIM(P_REQUEST_KEY) <> '') THEN
        SELECT COUNT(*) INTO :seen
        FROM DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY
        WHERE REQUEST_KEY = :P_REQUEST_KEY;
        IF (seen > 0) THEN
            RETURN 'DUPLICATE: request already applied';
        END IF;
    END IF;

    SELECT COUNT(*), MAX(STATUS) INTO :matched, :old_status
    FROM DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    WHERE ACTION_ID = :P_ACTION_ID;
    IF (matched = 0) THEN
        RETURN 'NOT_FOUND: action id';
    END IF;
    next_status := COALESCE(NULLIF(UPPER(TRIM(P_STATUS)), ''), old_status);

    BEGIN TRANSACTION;
    UPDATE DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
       SET STATUS = :next_status,
           OWNER = COALESCE(NULLIF(TRIM(:P_OWNER), ''), OWNER),
           DUE_DATE = COALESCE(:P_DUE_DATE, DUE_DATE),
           DEFER_UNTIL = COALESCE(:P_DEFER_UNTIL, DEFER_UNTIL),
           RESOLUTION_NOTE = IFF(:next_status IN ('DONE', 'DROPPED')
                                 AND NULLIF(TRIM(:P_NOTE), '') IS NOT NULL,
                                 :P_NOTE, RESOLUTION_NOTE),
           COMPLETED_AT = IFF(:next_status IN ('DONE', 'DROPPED'),
                              COALESCE(COMPLETED_AT, CURRENT_TIMESTAMP()), NULL),
           UPDATED_AT = CURRENT_TIMESTAMP(),
           UPDATED_BY = COALESCE(NULLIF(TRIM(:P_ACTOR), ''), CURRENT_USER())
     WHERE ACTION_ID = :P_ACTION_ID;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.ACTION_ACTIVITY
        (ACTION_ID, ACTIVITY_TYPE, FROM_STATUS, TO_STATUS, OWNER_NAME,
         DUE_DATE, DEFER_UNTIL, NOTE, REQUEST_KEY, CREATED_BY)
    SELECT :P_ACTION_ID,
           IFF(:next_status = :old_status, 'COMMENT', 'TRANSITION'),
           :old_status, :next_status, NULLIF(TRIM(:P_OWNER), ''),
           :P_DUE_DATE, :P_DEFER_UNTIL, NULLIF(TRIM(:P_NOTE), ''),
           NULLIF(TRIM(:P_REQUEST_KEY), ''),
           COALESCE(NULLIF(TRIM(:P_ACTOR), ''), CURRENT_USER());
    COMMIT;
    RETURN 'OK: action updated';
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 74 AS VERSION,
       'Operating workbench foundation: ACTION_QUEUE lifecycle context, atomic audited SP_ACTION_LIFECYCLE, evidence links, entity ownership catalog, personal watchlists, optimization experiments and SLO objectives. No task or mart changes.' AS DESCRIPTION
WHERE NOT EXISTS (SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 74);
