-- V075__security_operating_model.sql
--
-- Security operating model and interactive-workload isolation.
--
-- Adds:
--   * WH_OVERWATCH_APP, a dedicated auto-suspending warehouse for Streamlit reads.
--   * Narrow persistent login/change facts loaded after the shared QH extract.
--   * Trust Center snapshots and a latest-vs-prior delta view.
--   * Identity, egress and client policy tables.
--   * Durable access-review campaigns and audited decisions.
--   * A local exception-queue view that feeds Security without live history scans.
--
-- Owner applies this migration in Snowsight after V074. The app never runs it.

EXECUTE IMMEDIATE
$$
DECLARE
    v NUMBER;
    not_ready EXCEPTION (-20075, 'V075 requires V074 first - apply migrations in order.');
BEGIN
    SELECT MAX(VERSION) INTO :v FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION;
    IF (v < 74) THEN
        RAISE not_ready;
    END IF;
END;
$$;

-- Interactive reads no longer queue behind loader, mart and alert tasks.
-- No resource monitor: owner policy uses cost alerts, never warehouse suspension.
CREATE WAREHOUSE IF NOT EXISTS WH_OVERWATCH_APP
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'OVERWATCH Streamlit interactive reads; ETL remains on WH_ALFA_ADMIN';
ALTER WAREHOUSE WH_OVERWATCH_APP SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 120;

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SECURITY_IDENTITY_POLICY (
    USER_NAME              VARCHAR(200) NOT NULL PRIMARY KEY,
    IDENTITY_TYPE          VARCHAR(20)  NOT NULL DEFAULT 'HUMAN',
    OWNER_NAME             VARCHAR(200),
    EXPECTED_AUTH_METHOD   VARCHAR(80),
    EXPECTED_NETWORK       VARCHAR(500),
    ROTATION_DAYS          NUMBER(6,0),
    EXCEPTION_UNTIL        DATE,
    NOTES                  VARCHAR(4000),
    UPDATED_AT             TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY             VARCHAR(200) NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SECURITY_EGRESS_POLICY (
    POLICY_ID       VARCHAR(80)  NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    COMPANY         VARCHAR(40)  NOT NULL DEFAULT 'ALL',
    TARGET_KIND     VARCHAR(20)  NOT NULL,
    TARGET_PATTERN  VARCHAR(500) NOT NULL,
    OWNER_NAME      VARCHAR(200),
    STATUS          VARCHAR(20)  NOT NULL DEFAULT 'APPROVED',
    EXPIRES_ON      DATE,
    NOTES           VARCHAR(4000),
    UPDATED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY      VARCHAR(200) NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SECURITY_CLIENT_POLICY (
    DRIVER                VARCHAR(200) NOT NULL PRIMARY KEY,
    MIN_APPROVED_VERSION  VARCHAR(80)  NOT NULL,
    WARN_AFTER            DATE,
    OWNER_NAME            VARCHAR(200),
    NOTES                 VARCHAR(4000),
    UPDATED_AT            TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY            VARCHAR(200) NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS (
    CAMPAIGN_ID    VARCHAR(80)  NOT NULL PRIMARY KEY,
    TITLE          VARCHAR(300) NOT NULL,
    COMPANY        VARCHAR(40)  NOT NULL DEFAULT 'ALL',
    STATUS         VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    DUE_DATE       DATE,
    SNAPSHOT_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT     TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY     VARCHAR(200) NOT NULL DEFAULT CURRENT_USER(),
    COMPLETED_AT   TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS (
    ITEM_ID         VARCHAR(80)  NOT NULL PRIMARY KEY,
    CAMPAIGN_ID     VARCHAR(80)  NOT NULL,
    USER_NAME       VARCHAR(200) NOT NULL,
    ROLE_NAME       VARCHAR(200) NOT NULL,
    ACCESS_PATH     VARCHAR(2000),
    OWNER_NAME      VARCHAR(200),
    DECISION        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    REVIEWER        VARCHAR(200),
    DECISION_REASON VARCHAR(4000),
    DECIDED_AT      TIMESTAMP_NTZ,
    SNAPSHOT_AT     TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_DECISION_LOG (
    DECISION_ID     VARCHAR(80)  NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    CAMPAIGN_ID     VARCHAR(80)  NOT NULL,
    ITEM_ID         VARCHAR(80)  NOT NULL,
    DECISION        VARCHAR(20)  NOT NULL,
    DECISION_REASON VARCHAR(4000),
    REVIEWER        VARCHAR(200) NOT NULL,
    DECIDED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY (
    DAY            DATE NOT NULL,
    USER_NAME      VARCHAR(200) NOT NULL,
    COMPANY        VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    CLIENT_IP      VARCHAR(200) NOT NULL DEFAULT '(none)',
    AUTH_FACTOR    VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    ERROR_CATEGORY VARCHAR(80) NOT NULL,
    LOGINS         NUMBER(14,0),
    SUCCESSES      NUMBER(14,0),
    FAILURES       NUMBER(14,0),
    FIRST_SEEN     TIMESTAMP_LTZ,
    LAST_SEEN      TIMESTAMP_LTZ,
    LOAD_TS        TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE (
    QUERY_ID       VARCHAR(64) NOT NULL PRIMARY KEY,
    DAY            DATE NOT NULL,
    EVENT_TS       TIMESTAMP_LTZ NOT NULL,
    USER_NAME      VARCHAR(200),
    ROLE_NAME      VARCHAR(200),
    QUERY_TYPE     VARCHAR(80),
    DATABASE_NAME  VARCHAR(200),
    SCHEMA_NAME    VARCHAR(200),
    COMPANY        VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    CHANGE_KIND    VARCHAR(40),
    RISK_SCORE     NUMBER(5,0),
    RISK_LEVEL     VARCHAR(20),
    QUERY_PREVIEW  VARCHAR(200),
    LOAD_TS        TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT (
    DAY                 DATE NOT NULL,
    SCANNER_ID          VARCHAR(200) NOT NULL,
    SCANNER_NAME        VARCHAR(500),
    SEVERITY            VARCHAR(20),
    TOTAL_AT_RISK_COUNT NUMBER(18,0),
    SCANNED_AT          TIMESTAMP_LTZ,
    LOAD_TS             TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_LOAD_SECURITY_FACTS(DAYS_BACK FLOAT)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    d INT;
    emsg VARCHAR;
    trust_ok BOOLEAN DEFAULT TRUE;
BEGIN
    d := GREATEST(1, LEAST(COALESCE(DAYS_BACK, 3), 180))::INT;

    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY
     WHERE DAY < DATEADD('day', -180, CURRENT_DATE());
    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
     WHERE DAY < DATEADD('day', -180, CURRENT_DATE());
    DELETE FROM DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT
     WHERE DAY < DATEADD('day', -400, CURRENT_DATE());

    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY
     WHERE DAY >= DATEADD('day', -:d, CURRENT_DATE());
    INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY
        (DAY, USER_NAME, COMPANY, CLIENT_IP, AUTH_FACTOR, ERROR_CATEGORY,
         LOGINS, SUCCESSES, FAILURES, FIRST_SEEN, LAST_SEEN)
    SELECT DATE(EVENT_TIMESTAMP),
           COALESCE(USER_NAME, 'UNKNOWN'),
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(COALESCE(USER_NAME, 'UNKNOWN')),
           COALESCE(CLIENT_IP, '(none)'),
           COALESCE(FIRST_AUTHENTICATION_FACTOR, 'UNKNOWN'),
           CASE
             WHEN IS_SUCCESS = 'YES' THEN 'SUCCESS'
             WHEN COALESCE(ERROR_MESSAGE, '') ILIKE '%network%' THEN 'NETWORK POLICY'
             WHEN COALESCE(ERROR_MESSAGE, '') ILIKE '%disabled%' THEN 'DISABLED USER'
             WHEN COALESCE(ERROR_MESSAGE, '') ILIKE '%mfa%' THEN 'MFA'
             WHEN COALESCE(ERROR_MESSAGE, '') ILIKE ANY ('%password%', '%credential%', '%authentication%')
               THEN 'CREDENTIAL'
             ELSE 'OTHER'
           END,
           COUNT(*),
           COUNT_IF(IS_SUCCESS = 'YES'),
           COUNT_IF(IS_SUCCESS = 'NO'),
           MIN(EVENT_TIMESTAMP),
           MAX(EVENT_TIMESTAMP)
    FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
    WHERE EVENT_TIMESTAMP >= DATEADD('day', -:d, CURRENT_DATE())
    GROUP BY 1, 2, 3, 4, 5, 6;

    DELETE FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
     WHERE DAY >= DATEADD('day', -:d, CURRENT_DATE());

    IF (d <= 3) THEN
        INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
            (QUERY_ID, DAY, EVENT_TS, USER_NAME, ROLE_NAME, QUERY_TYPE,
             DATABASE_NAME, SCHEMA_NAME, COMPANY, CHANGE_KIND, RISK_SCORE,
             RISK_LEVEL, QUERY_PREVIEW)
        WITH raw AS (
            SELECT QUERY_ID, DATE(START_TIME) AS DAY, START_TIME AS EVENT_TS,
                   USER_NAME, ROLE_NAME, QUERY_TYPE, DATABASE_NAME, SCHEMA_NAME,
                   CASE
                     WHEN DATABASE_NAME IS NOT NULL
                      AND DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME) <> 'UNKNOWN'
                       THEN DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME)
                     ELSE DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(USER_NAME)
                   END AS COMPANY,
                   CASE
                     WHEN QUERY_TYPE ILIKE 'DROP%' OR QUERY_TYPE ILIKE 'TRUNCATE%' THEN 'DESTRUCTIVE'
                     WHEN QUERY_TYPE IN ('GRANT', 'REVOKE') THEN 'PRIVILEGE'
                     WHEN QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%' THEN 'SECURITY POLICY'
                     WHEN QUERY_TYPE ILIKE 'ALTER%' OR QUERY_TYPE ILIKE 'RENAME%' THEN 'ALTER'
                     ELSE 'CREATE'
                   END AS CHANGE_KIND,
                   LEAST(100,
                     CASE
                       WHEN QUERY_TYPE ILIKE 'DROP%' OR QUERY_TYPE ILIKE 'TRUNCATE%' THEN 90
                       WHEN QUERY_TYPE IN ('GRANT', 'REVOKE') THEN 80
                       WHEN QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%' THEN 85
                       WHEN QUERY_TYPE ILIKE 'ALTER%' OR QUERY_TYPE ILIKE 'RENAME%' THEN 55
                       ELSE 30
                     END
                     + IFF(ROLE_NAME IN ('ACCOUNTADMIN', 'SNOW_ACCOUNTADMINS'), 10, 0)
                     + IFF(COALESCE(DATABASE_NAME, '') ILIKE '%PROD%', 10, 0)
                   ) AS RISK_SCORE,
                   LEFT(QUERY_TEXT, 200) AS QUERY_PREVIEW
            FROM DBA_MAINT_DB.OVERWATCH.OW_QH_EXTRACT
            WHERE START_TIME >= DATEADD('day', -:d, CURRENT_DATE())
              AND EXECUTION_STATUS = 'SUCCESS'
              AND (QUERY_TYPE IN ('CREATE', 'CREATE_TABLE', 'CREATE_VIEW',
                   'CREATE_TABLE_AS_SELECT', 'ALTER', 'ALTER_TABLE_MODIFY_COLUMN',
                   'ALTER_SESSION', 'DROP', 'GRANT', 'REVOKE', 'RENAME',
                   'RENAME_TABLE', 'TRUNCATE_TABLE', 'ALTER_USER', 'CREATE_USER',
                   'DROP_USER', 'CREATE_ROLE', 'ALTER_ROLE', 'DROP_ROLE')
                   OR QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%'
                   OR QUERY_TYPE ILIKE '%ROLE%' OR QUERY_TYPE ILIKE 'DROP%'
                   OR QUERY_TYPE ILIKE 'TRUNCATE%')
        )
        SELECT QUERY_ID, DAY, EVENT_TS, USER_NAME, ROLE_NAME, QUERY_TYPE,
               DATABASE_NAME, SCHEMA_NAME, COMPANY, CHANGE_KIND, RISK_SCORE,
               CASE WHEN RISK_SCORE >= 90 THEN 'CRITICAL'
                    WHEN RISK_SCORE >= 70 THEN 'HIGH'
                    WHEN RISK_SCORE >= 45 THEN 'MEDIUM' ELSE 'LOW' END,
               QUERY_PREVIEW
        FROM raw;
    ELSE
        INSERT INTO DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
            (QUERY_ID, DAY, EVENT_TS, USER_NAME, ROLE_NAME, QUERY_TYPE,
             DATABASE_NAME, SCHEMA_NAME, COMPANY, CHANGE_KIND, RISK_SCORE,
             RISK_LEVEL, QUERY_PREVIEW)
        WITH raw AS (
            SELECT QUERY_ID, DATE(START_TIME) AS DAY, START_TIME AS EVENT_TS,
                   USER_NAME, ROLE_NAME, QUERY_TYPE, DATABASE_NAME, SCHEMA_NAME,
                   CASE
                     WHEN DATABASE_NAME IS NOT NULL
                      AND DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME) <> 'UNKNOWN'
                       THEN DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME)
                     ELSE DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(USER_NAME)
                   END AS COMPANY,
                   CASE
                     WHEN QUERY_TYPE ILIKE 'DROP%' OR QUERY_TYPE ILIKE 'TRUNCATE%' THEN 'DESTRUCTIVE'
                     WHEN QUERY_TYPE IN ('GRANT', 'REVOKE') THEN 'PRIVILEGE'
                     WHEN QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%' THEN 'SECURITY POLICY'
                     WHEN QUERY_TYPE ILIKE 'ALTER%' OR QUERY_TYPE ILIKE 'RENAME%' THEN 'ALTER'
                     ELSE 'CREATE'
                   END AS CHANGE_KIND,
                   LEAST(100,
                     CASE
                       WHEN QUERY_TYPE ILIKE 'DROP%' OR QUERY_TYPE ILIKE 'TRUNCATE%' THEN 90
                       WHEN QUERY_TYPE IN ('GRANT', 'REVOKE') THEN 80
                       WHEN QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%' THEN 85
                       WHEN QUERY_TYPE ILIKE 'ALTER%' OR QUERY_TYPE ILIKE 'RENAME%' THEN 55
                       ELSE 30
                     END
                     + IFF(ROLE_NAME IN ('ACCOUNTADMIN', 'SNOW_ACCOUNTADMINS'), 10, 0)
                     + IFF(COALESCE(DATABASE_NAME, '') ILIKE '%PROD%', 10, 0)
                   ) AS RISK_SCORE,
                   LEFT(QUERY_TEXT, 200) AS QUERY_PREVIEW
            FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
            WHERE START_TIME >= DATEADD('day', -:d, CURRENT_DATE())
              AND EXECUTION_STATUS = 'SUCCESS'
              AND (QUERY_TYPE IN ('CREATE', 'CREATE_TABLE', 'CREATE_VIEW',
                   'CREATE_TABLE_AS_SELECT', 'ALTER', 'ALTER_TABLE_MODIFY_COLUMN',
                   'ALTER_SESSION', 'DROP', 'GRANT', 'REVOKE', 'RENAME',
                   'RENAME_TABLE', 'TRUNCATE_TABLE', 'ALTER_USER', 'CREATE_USER',
                   'DROP_USER', 'CREATE_ROLE', 'ALTER_ROLE', 'DROP_ROLE')
                   OR QUERY_TYPE ILIKE '%POLICY%' OR QUERY_TYPE ILIKE '%USER%'
                   OR QUERY_TYPE ILIKE '%ROLE%' OR QUERY_TYPE ILIKE 'DROP%'
                   OR QUERY_TYPE ILIKE 'TRUNCATE%')
        )
        SELECT QUERY_ID, DAY, EVENT_TS, USER_NAME, ROLE_NAME, QUERY_TYPE,
               DATABASE_NAME, SCHEMA_NAME, COMPANY, CHANGE_KIND, RISK_SCORE,
               CASE WHEN RISK_SCORE >= 90 THEN 'CRITICAL'
                    WHEN RISK_SCORE >= 70 THEN 'HIGH'
                    WHEN RISK_SCORE >= 45 THEN 'MEDIUM' ELSE 'LOW' END,
               QUERY_PREVIEW
        FROM raw;
    END IF;

    BEGIN
        MERGE INTO DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT t
        USING (
            WITH current_findings AS (
                SELECT CURRENT_DATE() AS DAY, SCANNER_ID::VARCHAR AS SCANNER_ID,
                       SCANNER_NAME, UPPER(SEVERITY) AS SEVERITY,
                       TOTAL_AT_RISK_COUNT, CREATED_ON AS SCANNED_AT
                FROM SNOWFLAKE.TRUST_CENTER.FINDINGS
                QUALIFY ROW_NUMBER() OVER (
                    PARTITION BY SCANNER_ID ORDER BY CREATED_ON DESC
                ) = 1
            ), prior AS (
                SELECT SCANNER_ID, SCANNER_NAME, SEVERITY
                FROM DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT
                QUALIFY ROW_NUMBER() OVER (
                    PARTITION BY SCANNER_ID ORDER BY DAY DESC, LOAD_TS DESC
                ) = 1
            )
            SELECT DAY, SCANNER_ID, SCANNER_NAME, SEVERITY,
                   TOTAL_AT_RISK_COUNT, SCANNED_AT
            FROM current_findings
            UNION ALL
            SELECT CURRENT_DATE(), p.SCANNER_ID, p.SCANNER_NAME, p.SEVERITY,
                   0, CURRENT_TIMESTAMP()
            FROM prior p
            WHERE NOT EXISTS (
                SELECT 1 FROM current_findings c WHERE c.SCANNER_ID = p.SCANNER_ID
            )
        ) s
        ON t.DAY = s.DAY AND t.SCANNER_ID = s.SCANNER_ID
        WHEN MATCHED THEN UPDATE SET
            SCANNER_NAME = s.SCANNER_NAME, SEVERITY = s.SEVERITY,
            TOTAL_AT_RISK_COUNT = s.TOTAL_AT_RISK_COUNT,
            SCANNED_AT = s.SCANNED_AT, LOAD_TS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT
            (DAY, SCANNER_ID, SCANNER_NAME, SEVERITY, TOTAL_AT_RISK_COUNT, SCANNED_AT)
        VALUES
            (s.DAY, s.SCANNER_ID, s.SCANNER_NAME, s.SEVERITY,
             s.TOTAL_AT_RISK_COUNT, s.SCANNED_AT);
    EXCEPTION
        WHEN OTHER THEN
            trust_ok := FALSE;
            emsg := SQLERRM;
            INSERT INTO DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG
                (PAGE, ERROR_TYPE, ERROR_MESSAGE, CONTEXT, ROLE_NAME)
            SELECT 'SecurityLoader', 'trust_snapshot_unavailable', :emsg,
                   'Login/change facts loaded; grant TRUST_CENTER_VIEWER for snapshots',
                   CURRENT_ROLE();
    END;

    MERGE INTO DBA_MAINT_DB.OVERWATCH.SOURCE_FRESHNESS_STATE t
    USING (
        SELECT 'FACT_SECURITY_LOGIN_DAILY' AS SOURCE_NAME, MAX(LOAD_TS) AS LAST_LOAD_TS,
               COUNT(*) AS ROW_COUNT, 'OK' AS LOAD_STATUS
          FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY
        UNION ALL
        SELECT 'FACT_SECURITY_CHANGE', MAX(LOAD_TS), COUNT(*), 'OK'
          FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
        UNION ALL
        SELECT 'SECURITY_TRUST_SNAPSHOT', MAX(LOAD_TS), COUNT(*),
               IFF(:trust_ok, 'OK', 'ERROR')
          FROM DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT
    ) s
    ON t.SOURCE_NAME = s.SOURCE_NAME
    WHEN MATCHED THEN UPDATE SET
        LAST_LOAD_TS = s.LAST_LOAD_TS, ROW_COUNT = s.ROW_COUNT,
        SNAPSHOT_TS = CURRENT_TIMESTAMP(), GENERATION = COALESCE(t.GENERATION, 0) + 1,
        STATUS = s.LOAD_STATUS
    WHEN NOT MATCHED THEN INSERT
        (SOURCE_NAME, LAST_LOAD_TS, ROW_COUNT, SNAPSHOT_TS, GENERATION, STATUS)
    VALUES
        (s.SOURCE_NAME, s.LAST_LOAD_TS, s.ROW_COUNT, CURRENT_TIMESTAMP(), 1, s.LOAD_STATUS);

    RETURN 'security facts loaded ' || d || 'd';
END;
$$;

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_CREATE_ACCESS_REVIEW(
    CAMPAIGN_ID VARCHAR, TITLE VARCHAR, COMPANY VARCHAR, DUE_DATE DATE, ACTOR VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    n NUMBER;
    existing_campaign NUMBER;
BEGIN
    SELECT COUNT(*) INTO :existing_campaign
      FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS
     WHERE CAMPAIGN_ID = :CAMPAIGN_ID;
    IF (existing_campaign > 0) THEN
        SELECT COUNT(*) INTO :n
          FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS
         WHERE CAMPAIGN_ID = :CAMPAIGN_ID;
        RETURN 'access review ' || :CAMPAIGN_ID || ' already exists: ' || :n || ' items';
    END IF;

    INSERT INTO DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS
        (CAMPAIGN_ID, TITLE, COMPANY, DUE_DATE, CREATED_BY)
    SELECT :CAMPAIGN_ID, :TITLE, UPPER(COALESCE(NULLIF(:COMPANY, ''), 'ALL')),
           :DUE_DATE, COALESCE(NULLIF(:ACTOR, ''), CURRENT_USER());

    INSERT INTO DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS
        (ITEM_ID, CAMPAIGN_ID, USER_NAME, ROLE_NAME, ACCESS_PATH, OWNER_NAME)
    WITH RECURSIVE role_tree (USER_NAME, EFFECTIVE_ROLE, DEPTH, ACCESS_PATH) AS (
        SELECT g.GRANTEE_NAME, g.ROLE, 0, g.ROLE
        FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS g
        WHERE g.DELETED_ON IS NULL
          AND (UPPER(COALESCE(NULLIF(:COMPANY, ''), 'ALL')) = 'ALL'
               OR UPPER(DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(g.GRANTEE_NAME))
                  = UPPER(:COMPANY))
        UNION ALL
        SELECT r.USER_NAME, h.NAME, r.DEPTH + 1,
               r.ACCESS_PATH || ' -> ' || h.NAME
        FROM role_tree r
        JOIN SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES h
          ON h.GRANTED_ON = 'ROLE' AND h.GRANTEE_NAME = r.EFFECTIVE_ROLE
         AND h.DELETED_ON IS NULL
        WHERE r.DEPTH < 10
          AND POSITION(' -> ' || h.NAME || ' -> '
                       IN ' -> ' || r.ACCESS_PATH || ' -> ') = 0
    )
    SELECT SHA2_HEX(:CAMPAIGN_ID || '|' || r.USER_NAME || '|' || r.EFFECTIVE_ROLE, 256),
           :CAMPAIGN_ID, r.USER_NAME, r.EFFECTIVE_ROLE,
           MAX_BY(r.ACCESS_PATH, r.DEPTH), p.OWNER_NAME
    FROM role_tree r
    LEFT JOIN DBA_MAINT_DB.OVERWATCH.SECURITY_IDENTITY_POLICY p
      ON p.USER_NAME = r.USER_NAME
    WHERE 1 = 1
      AND NOT EXISTS (
          SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS i
          WHERE i.CAMPAIGN_ID = :CAMPAIGN_ID
            AND i.USER_NAME = r.USER_NAME AND i.ROLE_NAME = r.EFFECTIVE_ROLE
      )
    GROUP BY r.USER_NAME, r.EFFECTIVE_ROLE, p.OWNER_NAME;
    SELECT COUNT(*) INTO :n
      FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS
     WHERE CAMPAIGN_ID = :CAMPAIGN_ID;
    UPDATE DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS
       SET STATUS = IFF(:n = 0, 'COMPLETE', 'IN_REVIEW'),
           COMPLETED_AT = IFF(:n = 0, CURRENT_TIMESTAMP(), NULL)
     WHERE CAMPAIGN_ID = :CAMPAIGN_ID;
    RETURN 'access review ' || :CAMPAIGN_ID || ': ' || :n || ' items';
END;
$$;

CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_ACCESS_REVIEW_DECIDE(
    CAMPAIGN_ID VARCHAR, ITEM_ID VARCHAR, DECISION VARCHAR,
    REASON VARCHAR, ACTOR VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    invalid_decision EXCEPTION (-20076, 'Decision must be KEEP, REVOKE or EXCEPTION.');
    item_missing EXCEPTION (-20077, 'Access-review item was not found in this campaign.');
    d VARCHAR;
    n NUMBER;
BEGIN
    d := UPPER(TRIM(:DECISION));
    IF (d NOT IN ('KEEP', 'REVOKE', 'EXCEPTION')) THEN
        RAISE invalid_decision;
    END IF;
    SELECT COUNT(*) INTO :n
      FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS
     WHERE CAMPAIGN_ID = :CAMPAIGN_ID AND ITEM_ID = :ITEM_ID;
    IF (n = 0) THEN
        RAISE item_missing;
    END IF;
    INSERT INTO DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_DECISION_LOG
        (CAMPAIGN_ID, ITEM_ID, DECISION, DECISION_REASON, REVIEWER)
    SELECT :CAMPAIGN_ID, :ITEM_ID, :d, LEFT(COALESCE(:REASON, ''), 4000),
           COALESCE(NULLIF(:ACTOR, ''), CURRENT_USER());
    UPDATE DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS
       SET DECISION = :d,
           REVIEWER = COALESCE(NULLIF(:ACTOR, ''), CURRENT_USER()),
           DECISION_REASON = LEFT(COALESCE(:REASON, ''), 4000),
           DECIDED_AT = CURRENT_TIMESTAMP()
     WHERE CAMPAIGN_ID = :CAMPAIGN_ID AND ITEM_ID = :ITEM_ID;
    UPDATE DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS c
       SET STATUS = IFF(NOT EXISTS (
               SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS i
               WHERE i.CAMPAIGN_ID = c.CAMPAIGN_ID AND i.DECISION = 'PENDING'
           ), 'COMPLETE', 'IN_REVIEW'),
           COMPLETED_AT = IFF(NOT EXISTS (
               SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS i
               WHERE i.CAMPAIGN_ID = c.CAMPAIGN_ID AND i.DECISION = 'PENDING'
           ), CURRENT_TIMESTAMP(), NULL)
     WHERE c.CAMPAIGN_ID = :CAMPAIGN_ID;
    RETURN 'access review decision recorded';
END;
$$;

-- Extend the standing weekly clone job to the operating workbench and security
-- records. The task itself already calls this procedure and needs no surgery.
CREATE OR REPLACE PROCEDURE DBA_MAINT_DB.OVERWATCH.SP_BACKUP_OPERATOR_TABLES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    tables ARRAY DEFAULT [
        'SETTINGS', 'COMPANY_SCOPE', 'ALERT_CONFIG', 'ALERT_EVENTS',
        'ALERT_AUDIT', 'ACTION_QUEUE', 'SAVINGS_LEDGER', 'DEPARTMENT_MAP',
        'ALERT_ROUTES', 'REMEDIATION_LOG', 'USER_PREFS',
        'OBJECT_CHANGE_REGISTRY', 'WAREHOUSE_CHANGE_REGISTRY',
        'WAREHOUSE_CONFIG_SNAPSHOT', 'PIPELINE_SLA_CONFIG', 'DAILY_DIGEST',
        'DEPT_BUDGETS', 'INCIDENTS', 'INCIDENT_MEMBERS', 'ACTION_ACTIVITY',
        'EVIDENCE_LINKS', 'ENTITY_CATALOG', 'USER_WATCHLIST',
        'OPTIMIZATION_EXPERIMENTS', 'SLO_OBJECTIVES',
        'SECURITY_IDENTITY_POLICY', 'SECURITY_EGRESS_POLICY',
        'SECURITY_CLIENT_POLICY', 'ACCESS_REVIEW_CAMPAIGNS',
        'ACCESS_REVIEW_ITEMS', 'ACCESS_REVIEW_DECISION_LOG'
    ];
    tname VARCHAR;
    emsg VARCHAR;
    done INT DEFAULT 0;
    i INT;
BEGIN
    FOR i IN 0 TO ARRAY_SIZE(:tables) - 1 DO
        tname := GET(:tables, i)::VARCHAR;
        BEGIN
            EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE DBA_MAINT_DB.OVERWATCH.' || :tname ||
                              '_BAK_LAST CLONE DBA_MAINT_DB.OVERWATCH.' || :tname;
            done := done + 1;
        EXCEPTION
            WHEN OTHER THEN
                emsg := SQLERRM;
                INSERT INTO DBA_MAINT_DB.OVERWATCH.APP_ERROR_LOG
                    (PAGE, ERROR_TYPE, ERROR_MESSAGE, CONTEXT, ROLE_NAME)
                SELECT 'BackupOperatorTables', 'clone_failed', :emsg,
                       'table ' || :tname || ' (missing on this install is fine)', CURRENT_ROLE();
        END;
    END FOR;
    RETURN 'cloned ' || :done || ' operator table(s) to *_BAK_LAST';
END;
$$;

CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.V_SECURITY_TRUST_DELTA AS
WITH ranked AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY SCANNER_ID ORDER BY DAY DESC) AS DAY_RANK
    FROM DBA_MAINT_DB.OVERWATCH.SECURITY_TRUST_SNAPSHOT
), paired AS (
    SELECT SCANNER_ID,
           MAX(IFF(DAY_RANK = 1, SCANNER_NAME, NULL)) AS SCANNER_NAME,
           MAX(IFF(DAY_RANK = 1, SEVERITY, NULL)) AS SEVERITY,
           MAX(IFF(DAY_RANK = 1, TOTAL_AT_RISK_COUNT, NULL)) AS CURRENT_COUNT,
           MAX(IFF(DAY_RANK = 2, TOTAL_AT_RISK_COUNT, NULL)) AS PRIOR_COUNT,
           MAX(IFF(DAY_RANK = 1, SCANNED_AT, NULL)) AS SCANNED_AT,
           MAX(IFF(DAY_RANK = 1, DAY, NULL)) AS SNAPSHOT_DAY
    FROM ranked
    WHERE DAY_RANK <= 2
    GROUP BY SCANNER_ID
)
SELECT *,
       CURRENT_COUNT - COALESCE(PRIOR_COUNT, 0) AS COUNT_DELTA,
       CASE WHEN PRIOR_COUNT IS NULL THEN 'NEW'
            WHEN CURRENT_COUNT = 0 AND PRIOR_COUNT > 0 THEN 'RESOLVED'
            WHEN CURRENT_COUNT > PRIOR_COUNT THEN 'REGRESSED'
            WHEN CURRENT_COUNT < PRIOR_COUNT THEN 'IMPROVED'
            ELSE 'UNCHANGED' END AS CHANGE_STATE
FROM paired;

CREATE OR REPLACE VIEW DBA_MAINT_DB.OVERWATCH.V_SECURITY_EXCEPTION_QUEUE AS
WITH latest_posture AS (
    SELECT METRIC, VALUE, DAY
    FROM DBA_MAINT_DB.OVERWATCH.MART_SECURITY_POSTURE_DAILY
    QUALIFY DAY = MAX(DAY) OVER ()
), candidates AS (
    SELECT 'IDENTITY' AS DOMAIN, 'ALL' AS COMPANY,
           NULL::VARCHAR AS ACTOR_COMPANY, NULL::VARCHAR AS OBJECT_COMPANY,
           'ALERT' AS ENTITY_TYPE, METRIC AS ENTITY_KEY,
           IFF(METRIC = 'MFA_GAP_USERS', 'HIGH', 'MEDIUM') AS SEVERITY,
           CASE METRIC WHEN 'MFA_GAP_USERS' THEN 'Users with password activity and no MFA'
                       WHEN 'EXPIRED_CRED' THEN 'Expired credentials remain active'
                       ELSE 'Credentials expire within 10 days' END AS TITLE,
           VALUE || ' open exception(s)' AS DETAIL,
           VALUE AS IMPACT_COUNT, DAY::TIMESTAMP_NTZ AS DETECTED_AT, 1.0 AS CONFIDENCE
    FROM latest_posture
    WHERE METRIC IN ('MFA_GAP_USERS', 'EXPIRED_CRED', 'EXPIRING_CRED_10D') AND VALUE > 0
    UNION ALL
    SELECT 'PRIVILEGE', 'ALL', NULL, NULL, 'ALERT', METRIC,
           'HIGH', 'Recent break-glass grants', VALUE || ' grant(s) in 30 days',
           VALUE, DAY::TIMESTAMP_NTZ, 1.0
    FROM latest_posture
    WHERE METRIC = 'BREAKGLASS_GRANTS_30D' AND VALUE > 0
    UNION ALL
    SELECT 'TRUST CENTER', 'ALL', NULL, NULL, 'ALERT', SCANNER_ID,
           COALESCE(SEVERITY, 'MEDIUM'), SCANNER_NAME,
           CURRENT_COUNT || ' entity finding(s); ' || CHANGE_STATE,
           CURRENT_COUNT, SCANNED_AT::TIMESTAMP_NTZ,
           IFF(CHANGE_STATE IN ('NEW', 'REGRESSED'), 1.0, 0.9)
    FROM DBA_MAINT_DB.OVERWATCH.V_SECURITY_TRUST_DELTA
    WHERE CURRENT_COUNT > 0
    UNION ALL
    SELECT 'CHANGE RISK', COMPANY,
           DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(COALESCE(USER_NAME, 'UNKNOWN')),
           IFF(DATABASE_NAME IS NULL, NULL,
               DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(DATABASE_NAME)),
           IFF(DATABASE_NAME IS NULL, 'ALERT', 'OBJECT'),
           COALESCE(DATABASE_NAME || '.' || SCHEMA_NAME, QUERY_ID),
           RISK_LEVEL,
           CHANGE_KIND || ': ' || COALESCE(DATABASE_NAME || '.' || SCHEMA_NAME, QUERY_TYPE),
           COALESCE(USER_NAME, 'unknown') || ' via ' || COALESCE(ROLE_NAME, 'unknown'),
           1, EVENT_TS::TIMESTAMP_NTZ,
           RISK_SCORE / 100.0
    FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_CHANGE
    WHERE EVENT_TS >= DATEADD('day', -7, CURRENT_TIMESTAMP()) AND RISK_SCORE >= 70
    UNION ALL
    SELECT 'ACCESS REVIEW', ar.COMPANY, NULL, NULL, 'ACTION', ar.CAMPAIGN_ID,
           'HIGH', 'Overdue access review: ' || ar.TITLE,
           'Due ' || TO_VARCHAR(ar.DUE_DATE),
           GREATEST(1, (SELECT COUNT(*)
                          FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_ITEMS i
                         WHERE i.CAMPAIGN_ID = ar.CAMPAIGN_ID
                           AND i.DECISION = 'PENDING')),
           COALESCE(ar.DUE_DATE, CURRENT_DATE())::TIMESTAMP_NTZ, 1.0
    FROM DBA_MAINT_DB.OVERWATCH.ACCESS_REVIEW_CAMPAIGNS ar
    WHERE ar.STATUS <> 'COMPLETE' AND ar.DUE_DATE < CURRENT_DATE()
), open_actions AS (
    SELECT SOURCE_ENTITY_TYPE, SOURCE_ENTITY_KEY,
           MAX_BY(ACTION_ID, CREATED_AT) AS ACTION_ID,
           MAX_BY(OWNER, CREATED_AT) AS OWNER,
           MAX_BY(STATUS, CREATED_AT) AS ACTION_STATUS
    FROM DBA_MAINT_DB.OVERWATCH.ACTION_QUEUE
    WHERE STATUS IN ('OPEN', 'IN_PROGRESS')
    GROUP BY 1, 2
)
SELECT c.DOMAIN, c.COMPANY, c.ACTOR_COMPANY, c.OBJECT_COMPANY,
       c.ENTITY_TYPE, c.ENTITY_KEY, c.SEVERITY, c.TITLE, c.DETAIL,
       c.IMPACT_COUNT,
       c.DETECTED_AT, c.CONFIDENCE, a.OWNER, a.ACTION_ID,
       COALESCE(a.ACTION_STATUS, 'UNTRACKED') AS STATUS
FROM candidates c
LEFT JOIN open_actions a
  ON a.SOURCE_ENTITY_TYPE = c.ENTITY_TYPE AND a.SOURCE_ENTITY_KEY = c.ENTITY_KEY;

-- Serialize behind the hourly mart load, instead of adding another sibling on the XS loader warehouse.
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY SUSPEND;
CREATE TASK IF NOT EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_SECURITY_FACTS
    WAREHOUSE = WH_ALFA_ADMIN
    AFTER DBA_MAINT_DB.OVERWATCH.TASK_LOAD_MARTS_V27_HOURLY
AS
    CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_SECURITY_FACTS(3);
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_SECURITY_FACTS RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY RESUME;
SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY');

-- One off-peak first fill. A matched re-run does not repay the 90-day scans;
-- an empty fact still heals if a prior first fill was interrupted.
EXECUTE IMMEDIATE
$$
DECLARE
    applied NUMBER;
    fact_rows NUMBER;
BEGIN
    SELECT COUNT(*) INTO :applied
      FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 75;
    SELECT COUNT(*) INTO :fact_rows
      FROM DBA_MAINT_DB.OVERWATCH.FACT_SECURITY_LOGIN_DAILY;
    IF (applied = 0 OR fact_rows = 0) THEN
        CALL DBA_MAINT_DB.OVERWATCH.SP_LOAD_SECURITY_FACTS(90);
    END IF;
END;
$$;

-- Task-graph law: enable once before first fill and once again at the end.
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_SECURITY_FACTS RESUME;
ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY RESUME;
SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('DBA_MAINT_DB.OVERWATCH.TASK_LOAD_HOURLY');

INSERT INTO DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION (VERSION, DESCRIPTION)
SELECT 75,
       'Security operating model: dedicated WH_OVERWATCH_APP interactive warehouse; persistent login/change facts and Trust Center snapshots loaded serially after the hourly mart task; identity/egress/client policies; durable access-review campaigns and decisions; Trust Center delta and local exception-queue views. Owner-applied, first fill 90d, no resource monitor.'
WHERE NOT EXISTS (
    SELECT 1 FROM DBA_MAINT_DB.OVERWATCH.SCHEMA_VERSION WHERE VERSION = 75
);
