"""Regenerate the Snowflake full-rebuild bundle from its source files.

``render_*`` build each file's text without touching the disk (tests/test_rebuild_replay.py
compares them with the files on disk, so a hand edit of a generated file fails there);
``main()`` writes them.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNOWFLAKE = ROOT / "snowflake"
REBUILD = SNOWFLAKE / "rebuild"
UNDERLINE = "-- ==========================================================================="
# The 01 banner says what running the copy does, so the generator owns it (v4.607 review: the
# preserved "Sections B/C stay commented" banner missed Section B's live tail).
TEARDOWN_BANNER = (
    "-- 01_teardown_rebuildables.sql — BYTE-IDENTICAL copy of snowflake/\n"
    "-- teardown.sql (locked by tests/test_rebuild_bundle.py). Section A runs, and\n"
    "-- so does Section B's live tail (three rebuildable tables, the ML forecast\n"
    "-- model, the webhook secrets and the notification integrations); the rest of\n"
    "-- B and all of C stay commented, so the operator data B lists survives."
)
# 02's header is generated too (R2-001/R2-002/R2-004): it carries the replay shim and says what a
# replay does to kept operator data and to WH_ALFA_ADMIN. {shim} is the generated role block.
MIGRATION_HEADER = """\
-- 02_migrations_V001_V{tip:03d}.sql — GENERATED by outputs/gen_rebuild_bundle.py:
-- the replay shim below, then the {count} migration files byte-concatenated in
-- order (locked by tests/test_rebuild_bundle.py).
-- Snowsight 'Run All' executes top to bottom and HALTS at the first
-- error — exactly the rule from docs/FULL_REBUILD.md. If it halts,
-- read the failing statement, fix, and resume FROM THAT FILE's banner
-- (every file is written to be re-run). Expect several minutes in all: the
-- files that end with a first-fill CALL (the fact and mart seeds) are slow.
--
-- A REPLAY IS NOT A NO-OP ON KEPT OPERATOR DATA. SCHEMA_VERSION already holds
-- every version, so every guard passes and the one-time statements run again:
-- V034 sets every 'ALL' route's COMPANY_FILTER to 'ALFA'; V019/V020/V028,
-- V043/V045, V091 and V157 reset rule flags, thresholds and auto-clear; V001
-- resets COMPANY_SCOPE notes; the seed MERGEs put back the rules, routes,
-- settings, scope and department rows you deleted. After the last file,
-- docs/FULL_REBUILD.md step 3b restores those tables from the 00 clones.
-- V002 also sets WH_ALFA_ADMIN's STATEMENT_TIMEOUT_IN_SECONDS back to 300 and
-- attaches OVERWATCH_RM (30 credits a month, SUSPEND at 100%) until V045 drops
-- it: if Run All stops anywhere in between, detach it first (step 3); step 3b
-- puts back the timeout step 0 recorded.

{shim}
"""
SHIM_TEMPLATE = """\
-- REPLAY SHIM (generated, not a migration). {files} grant to
-- {roles}, the roles retired on 2026-07-13
-- (owner decision: SNOW_ACCOUNTADMINS + SNOW_SYSADMINS only). No migration
-- creates them, so without the lines below Run All stops at {first} on any current
-- or fresh account; 03_roles.sql drops them again. They need the CREATE ROLE
-- privilege: if Run All stops here, nothing else has run yet, so create them as
-- a role that can, resume from the V001 banner, and drop them with that role
-- after 03.
{creates}"""
# 00's CLONE list is maintained by hand; its header is generated so it stays true (R2-004: it said
# the keep-operator-data rebuild never touches these tables).
BACKUP_HEADER = (
    "-- 00_backup_operator_data.sql — zero-cost TRANSIENT clones of every operator\n"
    "-- table. The CLONE list below is maintained by hand (tests/test_rebuild_bundle.py\n"
    "-- locks its coverage); this header is written by outputs/gen_rebuild_bundle.py.\n"
    "-- FIRST change every _20260712 suffix (the CREATEs and the verify below)\n"
    "-- to today's date, then run it, verify the counts, and proceed.\n"
    "-- Not just insurance: on the keep-operator-data path the 02 replay re-runs\n"
    "-- one-time config statements against these tables (route company filters,\n"
    "-- rule flags and thresholds, re-seeded rows), and docs/FULL_REBUILD.md step 3b\n"
    "-- restores SETTINGS, COMPANY_SCOPE, ALERT_CONFIG, ALERT_ROUTES and\n"
    "-- DEPARTMENT_MAP from these clones. Drop them when the rebuild proves out.\n"
    "-- Since V161 there is no scheduled backup: these clones are the only\n"
    "-- copy outside Time Travel. No IF NOT EXISTS: an unedited suffix that\n"
    "-- already exists fails loudly instead of keeping an old clone. After a\n"
    "-- partial run, re-run from the failing CREATE (the earlier clones are\n"
    "-- already today's).\n"
    "-- TRANSIENT: a permanent clone of a transient table (ALERT_EVENTS,\n"
    "-- ACTION_QUEUE, ...) fails, the V089 finding."
)
README_NOTES_BEGIN = "<!-- generated by outputs/gen_rebuild_bundle.py: replay notes -->"
README_NOTES_END = "<!-- end of generated replay notes -->"
README_NOTES = """{begin}
Around the files (docs/FULL_REBUILD.md has the statements):

- **Before 00** (step 0): list the opt-in objects and the live ALERT_ROUTES, and
  record WH_ALFA_ADMIN's STATEMENT_TIMEOUT_IN_SECONDS: V002 sets it back to 300.
- **02**: its generated header re-creates the retired roles {grantors} grant
  to (03 drops them again). If Run All stops between V002 and V045, detach the
  OVERWATCH_RM resource monitor V002 attached before anything else (step 3).
- **Between 02 and 03, if you kept operator data** (step 3b): restore SETTINGS,
  COMPANY_SCOPE, ALERT_CONFIG, ALERT_ROUTES and DEPARTMENT_MAP from the 00
  clones (the replay re-ran one-time config statements on them), close the
  events the replay raised for rules that are off again, and put the
  warehouse timeout back.
- **After 05** (step 7b): re-create the opt-in objects 01 dropped (email alerts,
  drill, ML forecast, notification integrations and secrets) and re-enable the
  routes step 0 listed.
{end}"""


def migrations() -> list[Path]:
    return sorted((SNOWFLAKE / "migrations").glob("V[0-9]*.sql"))


def _tip(paths: list[Path]) -> int:
    return max(int(re.match(r"V(\d+)", path.name).group(1)) for path in paths)


def _uncommented(text: str) -> list[str]:
    return [line for line in text.splitlines() if not line.lstrip().startswith("--")]


def retired_role_grants(paths: list[Path]) -> dict[str, list[str]]:
    """{role: [migration versions]} for every uncommented ``TO ROLE`` target that roles.sql does not
    grant to. Every such role must be one roles.sql retires (``DROP ROLE IF EXISTS``): the replay shim
    re-creates exactly these, and 03_roles.sql drops them again. Anything else stops the generator."""
    roles_sql = (SNOWFLAKE / "roles.sql").read_text(encoding="utf-8")
    live = {m.group(1) for line in _uncommented(roles_sql) for m in re.finditer(r"\bTO ROLE (\w+)", line)}
    retired = set(re.findall(r"^DROP ROLE IF EXISTS (\w+);$", roles_sql, re.M))
    found: dict[str, list[str]] = {}
    for path in paths:
        version = path.name.split("__", 1)[0]
        for line in _uncommented(path.read_text(encoding="utf-8")):
            for m in re.finditer(r"\bTO ROLE (\w+)", line):
                role = m.group(1)
                if role in live:
                    continue
                if role not in retired:
                    raise SystemExit(f"{path.name} grants to {role}, which roles.sql neither grants to "
                                     "nor retires: the replay would stop there. Fix the migration chain "
                                     "or roles.sql before regenerating the bundle.")
                found.setdefault(role, [])
                if version not in found[role]:
                    found[role].append(version)
    return dict(sorted(found.items()))


def _and(items: list[str]) -> str:
    return items[0] if len(items) == 1 else ", ".join(items[:-1]) + " and " + items[-1]


def replay_shim(paths: list[Path]) -> str:
    grants = retired_role_grants(paths)
    if not grants:
        return "-- REPLAY SHIM (generated): no migration grants to a retired role; nothing to create.\n"
    files = sorted({version for versions in grants.values() for version in versions})
    roles = list(grants)
    return SHIM_TEMPLATE.format(files=_and(files), roles=_and(roles), first=files[0],
                                creates="".join(f"CREATE ROLE IF NOT EXISTS {role};\n" for role in roles))


def render_migration_bundle(paths: list[Path] | None = None) -> tuple[str, str]:
    """(file name, text) of 02: the generated header + shim, then every migration between banners."""
    paths = migrations() if paths is None else paths
    tip = _tip(paths)
    parts = [
        f"{UNDERLINE}\n-- >>> {migration.name}\n{UNDERLINE}\n{migration.read_text(encoding='utf-8')}"
        for migration in paths
    ]
    header = MIGRATION_HEADER.format(tip=tip, count=len(paths), shim=replay_shim(paths))
    return f"02_migrations_V001_V{tip:03d}.sql", header + "\n".join(parts)


def render_copy(bundle_name: str, source_name: str, header: str | None = None) -> str:
    if header is None:
        header = (REBUILD / bundle_name).read_text(encoding="utf-8").split("\n\n", 1)[0]
    source = (SNOWFLAKE / source_name).read_text(encoding="utf-8")
    return f"{header}\n\n{source}"


COPIES = (
    ("01_teardown_rebuildables.sql", "teardown.sql", TEARDOWN_BANNER),
    ("03_roles.sql", "roles.sql", None),
    ("04_backfill_365.sql", "backfill_365.sql", None),
    ("05_validate.sql", "validate.sql", None),
)


def render_backup() -> str:
    body = (REBUILD / "00_backup_operator_data.sql").read_text(encoding="utf-8").split("\n\n", 1)[1]
    return f"{BACKUP_HEADER}\n\n{body}"


def readme_notes(paths: list[Path]) -> str:
    grantors = sorted({version for versions in retired_role_grants(paths).values() for version in versions})
    return README_NOTES.format(begin=README_NOTES_BEGIN, end=README_NOTES_END,
                               grantors=_and(grantors) if grantors else "no migration")


def render_readme(paths: list[Path] | None = None) -> str:
    """The runbook README with the migration filename + count in step with the bundle, and the
    generated replay notes block.

    The README is NOT byte-copied like the other bundle files, so before this it drifted
    on every migration (the table still named V117/117 at bundle V121) — a stale runbook
    an operator would follow during a DR rebuild. Rewrite just the migration cell + drop
    the misleading fixed 'generated <date>' heading (avoids date churn). (bug-hunt round 9)
    The notes block between README_NOTES_BEGIN/END is the generator's (R2-004: the README
    gave no step between 02 and 03 for the config the replay rewrites).
    """
    paths = migrations() if paths is None else paths
    maximum, count, notes = _tip(paths), len(paths), readme_notes(paths)
    text = (REBUILD / "README.md").read_text(encoding="utf-8")
    text = re.sub(r"02_migrations_V001_V\d{3}\.sql",
                  f"02_migrations_V001_V{maximum:03d}.sql", text)
    text = re.sub(r"all \d+ migrations", f"all {count} migrations", text)
    text = re.sub(r"# One-shot full rebuild \(generated [^)]*\)",
                  "# One-shot full rebuild (regenerated by outputs/gen_rebuild_bundle.py)", text)
    if README_NOTES_BEGIN in text:
        start = text.index(README_NOTES_BEGIN)
        end = text.index(README_NOTES_END, start) + len(README_NOTES_END)
        text = text[:start] + notes + text[end:]
    else:
        anchor = text.index("These files are GENERATED")
        text = text[:anchor] + notes + "\n\n" + text[anchor:]
    return text


def _write(path: Path, text: str) -> None:
    # newline="\n": the bundle is LF in git (.gitattributes); a Windows run otherwise rewrote every
    # bundle file as CRLF in the working copy, burying the one real change in noise.
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    paths = migrations()
    name, text = render_migration_bundle(paths)
    candidates = sorted(REBUILD.glob("02_migrations_V001_V*.sql"))
    target = REBUILD / name
    _write(target, text)
    for stale in candidates:
        if stale != target:
            stale.unlink()

    for bundle, source, header in COPIES:
        _write(REBUILD / bundle, render_copy(bundle, source, header))
    _write(REBUILD / "00_backup_operator_data.sql", render_backup())
    _write(REBUILD / "README.md", render_readme(paths))


if __name__ == "__main__":
    main()
