"""Regenerate the Snowflake full-rebuild bundle from its source files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNOWFLAKE = ROOT / "snowflake"
REBUILD = SNOWFLAKE / "rebuild"
UNDERLINE = "-- ==========================================================================="
# The 01 banner says what running the copy does, so the generator owns it (v4.607 review: the
# preserved "Sections B/C stay commented" banner missed Section B's live tail).
TEARDOWN_BANNER = (
    "-- 01_teardown_rebuildables.sql — BYTE-IDENTICAL copy of snowflake/\n"
    "-- teardown.sql (locked by tests/test_rebuild_bundle.py). Section A runs, and\n"
    "-- so does Section B's live tail (three rebuildable tables, the ML forecast\n"
    "-- model, the webhook secrets and the notification integrations); the rest of\n"
    "-- B and all of C stay commented, so the operator data B lists survives."
)


def _copy_body(bundle_name: str, source_name: str, header: str | None = None) -> None:
    bundle = REBUILD / bundle_name
    if header is None:
        header = bundle.read_text(encoding="utf-8").split("\n\n", 1)[0]
    source = (SNOWFLAKE / source_name).read_text(encoding="utf-8")
    # newline="\n": the bundle is LF in git (.gitattributes); a Windows run otherwise rewrote every
    # bundle file as CRLF in the working copy, burying the one real change in noise.
    bundle.write_text(f"{header}\n\n{source}", encoding="utf-8", newline="\n")


def _migration_header(previous: Path, maximum: int, count: int) -> str:
    text = previous.read_text(encoding="utf-8")
    marker = f"{UNDERLINE}\n-- >>> V001__core.sql\n{UNDERLINE}\n"
    header = text[: text.index(marker)]
    header = re.sub(r"V001_V\d{3}", f"V001_V{maximum:03d}", header)
    header = re.sub(r"the \d+ migration files", f"the {count} migration files", header)
    return header


def main() -> None:
    migrations = sorted((SNOWFLAKE / "migrations").glob("V[0-9]*.sql"))
    maximum = max(int(re.match(r"V(\d+)", path.name).group(1)) for path in migrations)
    candidates = sorted(REBUILD.glob("02_migrations_V001_V*.sql"))
    previous = candidates[-1]
    target = REBUILD / f"02_migrations_V001_V{maximum:03d}.sql"
    parts = [
        (
            f"{UNDERLINE}\n-- >>> {migration.name}\n{UNDERLINE}\n"
            f"{migration.read_text(encoding='utf-8')}"
        )
        for migration in migrations
    ]
    target.write_text(
        _migration_header(previous, maximum, len(migrations)) + "\n".join(parts),
        encoding="utf-8",
        newline="\n",
    )
    for stale in candidates:
        if stale != target:
            stale.unlink()

    _copy_body("01_teardown_rebuildables.sql", "teardown.sql", TEARDOWN_BANNER)
    for bundle, source in (
        ("03_roles.sql", "roles.sql"),
        ("04_backfill_365.sql", "backfill_365.sql"),
        ("05_validate.sql", "validate.sql"),
    ):
        _copy_body(bundle, source)

    _update_readme(maximum, len(migrations))


def _update_readme(maximum: int, count: int) -> None:
    """Keep the runbook README's migration filename + count in step with the bundle.

    The README is NOT byte-copied like the other bundle files, so before this it drifted
    on every migration (the table still named V117/117 at bundle V121) — a stale runbook
    an operator would follow during a DR rebuild. Rewrite just the migration cell + drop
    the misleading fixed 'generated <date>' heading (avoids date churn). (bug-hunt round 9)
    """
    readme = REBUILD / "README.md"
    text = readme.read_text(encoding="utf-8")
    text = re.sub(r"02_migrations_V001_V\d{3}\.sql",
                  f"02_migrations_V001_V{maximum:03d}.sql", text)
    text = re.sub(r"all \d+ migrations", f"all {count} migrations", text)
    text = re.sub(r"# One-shot full rebuild \(generated [^)]*\)",
                  "# One-shot full rebuild (regenerated by outputs/gen_rebuild_bundle.py)", text)
    readme.write_text(text, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
