-- 03_roles.sql — BYTE-IDENTICAL copy of snowflake/roles.sql (locked by
-- tests/test_rebuild_bundle.py); numbered for the rebuild order.

-- roles.sql — OVERWATCH access (owner decision 2026-07-13: the ONLY roles
-- with access are SNOW_ACCOUNTADMINS and SNOW_SYSADMINS; the old
-- OVERWATCH_MONITOR / OVERWATCH_OPERATOR layer is retired).
-- Run as SNOW_ACCOUNTADMINS (IMPORTED PRIVILEGES needs ACCOUNTADMIN-tier).

-- Retire the old layer if it exists (idempotent).
DROP ROLE IF EXISTS OVERWATCH_OPERATOR;
DROP ROLE IF EXISTS OVERWATCH_MONITOR;

-- ACCOUNT_USAGE access (live fallbacks + ad-hoc reads).
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_ACCOUNTADMINS;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_SYSADMINS;

-- App objects. DBA_MAINT_DB.OVERWATCH is shared with the previous app's
-- objects, so ALL/FUTURE grants cover those too (intentional, owner decision).
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_SYSADMINS;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(VARCHAR) TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_WAREHOUSE(VARCHAR) TO ROLE SNOW_SYSADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(VARCHAR) TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_USER(VARCHAR) TO ROLE SNOW_SYSADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(VARCHAR) TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON FUNCTION DBA_MAINT_DB.OVERWATCH.COMPANY_FOR_DATABASE(VARCHAR) TO ROLE SNOW_SYSADMINS;

-- Compute for interactive use.
GRANT USAGE ON WAREHOUSE WH_ALFA_OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON WAREHOUSE WH_ALFA_OVERWATCH TO ROLE SNOW_SYSADMINS;

SELECT 'roles applied' AS STATUS;
